import type { DecisionGuide } from "./types";

export const ADVANCE_DIRECTIVES: DecisionGuide = {
  slug: "types-of-advance-directives",
  title: "Types of advance directives: which ones do you need?",
  h1: "Types of advance directives, and which ones fit you",
  description:
    "Living will, healthcare power of attorney, POLST, DNR, HIPAA release and state forms compared on one page. Answer six questions to see which fit you.",
  kicker: "Advance directive decision guide",
  art: "HeroPowersOfAttorney",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "Most adults need two advance directives: a healthcare power of attorney, which names who decides for you, and a living will, which states your treatment wishes. Many states combine both in one form. A HIPAA authorization lets family get information. POLST and DNR forms are different. They are medical orders signed with a clinician, usually for people who are seriously ill.",
  takeaways: [
    "Advance directives are documents you sign yourself. POLST and DNR forms are medical orders a clinician signs with you.",
    "A healthcare power of attorney matters most for healthy adults, because no form can foresee every situation.",
    "A living will states your wishes, but paramedics generally follow a POLST or out-of-hospital DNR instead.",
    "POLST is built for people with serious illness or frailty. It is not meant for healthy adults.",
    "Form names, witness rules and notary rules vary by state, so use documents that fit where you live.",
  ],
  noun: "advance directive",
  families: [
    { id: "people", name: "Who speaks and who knows", text: "Name the person who decides for you and the people your doctors may talk to.", tone: "accent" },
    { id: "wishes", name: "Your written wishes", text: "Put your views on life support, comfort care and CPR in writing.", tone: "sage" },
    { id: "combined", name: "All-in-one state form", text: "Many states offer one form that names an agent and records your wishes.", tone: "gold" },
    { id: "orders", name: "Medical orders for serious illness", text: "Signed with a clinician, so hospitals and paramedics can act on them right away.", tone: "clay" },
  ],
  dimensions: [
    { id: "signer", label: "You sign it yourself", help: "Or is it a medical order a clinician signs?" },
    { id: "decider", label: "Names a decision-maker", help: "Does it give a person authority to decide for you?" },
    { id: "wishes", label: "Records treatment wishes", help: "Does it say what care you want or refuse?" },
    { id: "ems", label: "Paramedics act on it", help: "Will 911 crews at home or in an ambulance usually follow it?" },
    { id: "healthy", label: "Fits healthy adults", help: "Does it make sense to sign while you are well?" },
    { id: "formality", label: "Signing steps", help: "Witnesses, notary or a clinician visit. More dots means more steps.", inverse: true },
    { id: "review", label: "How often to review", help: "More dots means it needs updating more often.", inverse: true },
  ],
  options: [
    {
      id: "healthcare-poa",
      name: "Healthcare power of attorney",
      short: "Healthcare agent",
      family: "people",
      icon: "UserCheck",
      what: "A document naming a person, your healthcare agent or proxy, to make medical decisions for you when you cannot make or share them yourself.",
      bestFor: ["Almost any adult with someone they trust", "People who want a person, not a checklist, to handle surprises", "Anyone with early memory changes who can still sign"],
      watchOut: ["Name a backup in case your first choice cannot act", "Tell your agent your wishes before you need them"],
      cells: {
        signer: { level: 3, text: "Yes, you sign" },
        decider: { level: 3, text: "Yes, an agent and backup" },
        wishes: { level: 1, text: "Can add instructions" },
        ems: { level: 0, text: "No, crews follow orders" },
        healthy: { level: 3, text: "Yes, sign while well" },
        formality: { level: 2, text: "Witnesses or notary, by state" },
        review: { level: 1, text: "Every few years" },
      },
      map: { x: 26, y: 30 },
      learn: { href: "/learn/healthcare-directives/healthcare-power-of-attorney", label: "Healthcare power of attorney explained" },
    },
    {
      id: "living-will",
      name: "Living will",
      short: "Living will",
      family: "wishes",
      icon: "ScrollText",
      what: "A written statement of the treatments you would want or refuse if you were terminally ill, permanently unconscious or unable to communicate.",
      bestFor: ["People with clear views on life support or tube feeding", "People with no one they would trust as an agent"],
      watchOut: ["Doctors must interpret it, and real situations rarely match the form", "Paramedics usually do not follow it in an emergency"],
      cells: {
        signer: { level: 3, text: "Yes, you sign" },
        decider: { level: 0, text: "No, unless combined" },
        wishes: { level: 3, text: "Yes, its purpose" },
        ems: { level: 0, text: "Usually not" },
        healthy: { level: 3, text: "Yes, sign while well" },
        formality: { level: 2, text: "Witnesses or notary, by state" },
        review: { level: 1, text: "Every few years" },
      },
      map: { x: 22, y: 80 },
      learn: { href: "/learn/healthcare-directives/living-will", label: "Living wills explained" },
    },
    {
      id: "combined",
      name: "State advance directive form",
      short: "Combined form",
      family: "combined",
      icon: "FileSignature",
      what: "One form, offered in many states, that names your healthcare agent and records your treatment wishes together.",
      bestFor: ["People who want one document instead of several", "Anyone who wants a form hospitals in their state know well"],
      watchOut: ["Fill-in boxes may not capture your values, so add notes", "Forms differ by state, so review it if you move"],
      cells: {
        signer: { level: 3, text: "Yes, you sign" },
        decider: { level: 3, text: "Yes, an agent" },
        wishes: { level: 3, text: "Yes, in the same form" },
        ems: { level: 0, text: "Usually not" },
        healthy: { level: 3, text: "Yes, sign while well" },
        formality: { level: 2, text: "State witness or notary rules" },
        review: { level: 1, text: "Every few years or a move" },
      },
      map: { x: 40, y: 58 },
      learn: { href: "/learn/healthcare-directives", label: "Advance healthcare directives guide" },
    },
    {
      id: "hipaa",
      name: "HIPAA authorization",
      short: "HIPAA release",
      family: "people",
      icon: "Lock",
      what: "A signed form that lets your doctors, hospitals and insurers share your health information with the people you name. It does not let them decide anything.",
      bestFor: ["Families who want to talk with your doctors now", "Agents under a springing power of attorney who must show incapacity"],
      watchOut: ["Gives access to information, not authority to decide", "Check the expiration date written in the form"],
      cells: {
        signer: { level: 3, text: "Yes, you sign" },
        decider: { level: 0, text: "No, access only" },
        wishes: { level: 0, text: "No" },
        ems: { level: 0, text: "No" },
        healthy: { level: 3, text: "Yes, sign while well" },
        formality: { level: 1, text: "Signature, set content" },
        review: { level: 1, text: "With your other documents" },
      },
      map: { x: 10, y: 12 },
      learn: { href: "/learn/healthcare-directives/hipaa-authorization", label: "HIPAA authorizations explained" },
    },
    {
      id: "polst",
      name: "POLST or MOLST",
      short: "POLST",
      family: "orders",
      icon: "Stethoscope",
      what: "A portable medical order, signed by a clinician and by you or your representative, that records choices about CPR and other treatment during serious illness.",
      bestFor: ["People with advanced illness or frailty", "People who want limits on treatment honored at home, in the ambulance and in care facilities"],
      watchOut: ["Not meant for healthy adults", "Names and legal status vary by state, such as MOLST, MOST or POST"],
      cells: {
        signer: { level: 1, text: "You and a clinician" },
        decider: { level: 0, text: "No" },
        wishes: { level: 3, text: "CPR and level of treatment" },
        ems: { level: 3, text: "Yes, made to travel" },
        healthy: { level: 0, text: "No, serious illness only" },
        formality: { level: 2, text: "Clinician talk and signature" },
        review: { level: 3, text: "When your health changes" },
      },
      map: { x: 76, y: 82 },
      learn: { href: "/learn/healthcare-directives/dnr-and-polst", label: "DNR orders and POLST forms explained" },
    },
    {
      id: "dnr",
      name: "DNR order",
      short: "DNR",
      family: "orders",
      icon: "Heart",
      what: "A medical order telling staff not to attempt CPR if your heart or breathing stops. It covers CPR only, not other treatment.",
      bestFor: ["People who would not want CPR, after talking it through with a doctor", "People living at home who need an out-of-hospital form crews will honor"],
      watchOut: ["A hospital DNR may not apply at home or in the ambulance", "Does not mean do not treat"],
      cells: {
        signer: { level: 1, text: "A clinician writes it" },
        decider: { level: 0, text: "No" },
        wishes: { level: 1, text: "CPR only" },
        ems: { level: 2, text: "Out-of-hospital form only" },
        healthy: { level: 1, text: "Mostly serious illness" },
        formality: { level: 2, text: "Clinician order, state form" },
        review: { level: 3, text: "When your health changes" },
      },
      map: { x: 90, y: 56 },
      learn: { href: "/learn/healthcare-directives/dnr-and-polst", label: "DNR orders and POLST forms explained" },
    },
  ],
  map: {
    title: "The advance directive map",
    lead: "Documents on the left are ones you sign yourself while you are well. On the right are medical orders a clinician signs during serious illness. Higher up, the document says more about treatment.",
    x: { low: "You sign it, while well", high: "Clinician signs, for serious illness" },
    y: { low: "About people: who decides or knows", high: "About treatment: what to do" },
  },
  questions: [
    {
      id: "health",
      prompt: "How is your health today?",
      choices: [
        { id: "healthy", label: "Healthy, no serious illness", weights: { "healthcare-poa": 2, combined: 2, "living-will": 1, hipaa: 1, polst: -3, dnr: -2 }, reason: "You are healthy, so documents you sign yourself come first" },
        { id: "chronic", label: "Living with a chronic condition", detail: "Such as diabetes, heart disease or early memory changes.", weights: { "healthcare-poa": 2, "living-will": 2, combined: 1 }, reason: "A chronic condition makes clear written wishes and an agent more useful" },
        { id: "serious", label: "Seriously ill or frail", detail: "Your doctor would not be surprised by a decline in the next year.", weights: { polst: 4, dnr: 2, "healthcare-poa": 1 }, reason: "You are seriously ill or frail, which is who POLST and DNR orders are for" },
      ],
    },
    {
      id: "person",
      prompt: "Is there someone you trust to make medical decisions for you?",
      choices: [
        { id: "yes", label: "Yes", weights: { "healthcare-poa": 3, combined: 2, hipaa: 1 }, reason: "You have someone you trust to speak for you" },
        { id: "maybe", label: "Maybe, I need to think about it", weights: { "healthcare-poa": 1, "living-will": 2 }, reason: "Without a clear agent, written wishes carry more weight" },
        { id: "no", label: "No one I would trust", weights: { "living-will": 3, "healthcare-poa": -1 }, reason: "You have no one to name, so written wishes carry the load" },
      ],
    },
    {
      id: "views",
      prompt: "Which of these do you have strong views about?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "life-support", label: "Life support, ventilators or feeding tubes", weights: { "living-will": 3, combined: 2, polst: 1 }, reason: "You have clear views on life support" },
        { id: "cpr", label: "Whether to have CPR if my heart stops", weights: { dnr: 3, polst: 2, "living-will": 1 }, reason: "You have a view on CPR, which a doctor can turn into an order" },
        { id: "comfort", label: "Comfort and pain care near the end", weights: { "living-will": 2, combined: 1 }, reason: "You want your comfort priorities in writing" },
        { id: "none", label: "Not really, I would rather someone decide", weights: { "healthcare-poa": 3 }, reason: "You would rather trust a person than a checklist" },
      ],
    },
    {
      id: "records",
      prompt: "Do you want family to be able to talk with your doctors?",
      choices: [
        { id: "now", label: "Yes, even while I can still speak", weights: { hipaa: 4 }, reason: "You want family to get information now, which a HIPAA release allows" },
        { id: "later", label: "Only if I cannot speak for myself", weights: { hipaa: 2, "healthcare-poa": 1 }, reason: "Providers may hold back information without a signed release" },
        { id: "no", label: "No", weights: { hipaa: -1 } },
      ],
    },
    {
      id: "format",
      prompt: "How would you like the paperwork?",
      choices: [
        { id: "one", label: "One form that covers it all", weights: { combined: 4 }, reason: "You want one form, and many states offer a combined advance directive" },
        { id: "separate", label: "Separate documents, each with one job", weights: { "healthcare-poa": 1, "living-will": 1, hipaa: 1 } },
        { id: "unsure", label: "No preference", weights: {} },
      ],
    },
    {
      id: "emergency",
      prompt: "If 911 is called to your home, what matters most to you?",
      choices: [
        { id: "everything", label: "That they try everything to save me", weights: { dnr: -3 } },
        { id: "limits", label: "That they skip CPR or treatment I would not want", weights: { polst: 3, dnr: 3 }, reason: "Paramedics generally follow a POLST or out-of-hospital DNR, not a living will" },
        { id: "unsure", label: "I have not thought about it", weights: { "healthcare-poa": 1, "living-will": 1 } },
      ],
    },
  ],
  resultNote:
    "Most adults start with a healthcare power of attorney, a living will and a HIPAA authorization, often on one state form. POLST and DNR orders come later, with your doctor, if serious illness arrives.",
  shortcuts: [
    { when: "You are healthy and have someone you trust to speak for you", pick: "healthcare-poa" },
    { when: "You have firm views on life support or tube feeding", pick: "living-will" },
    { when: "You want one document your state's hospitals know well", pick: "combined" },
    { when: "Your spouse or children need to talk with your doctors", pick: "hipaa" },
    { when: "You or a parent has advanced illness or frailty", pick: "polst" },
    { when: "You would not want CPR, and your doctor agrees it fits your health", pick: "dnr" },
    { when: "You have early memory changes but still understand what you sign", pick: "healthcare-poa" },
  ],
  diagrams: ["PoaHealthcareRoles"],
  howTo: {
    name: "How to choose and set up your advance directives",
    steps: [
      { name: "Choose your healthcare agent", text: "Pick someone who knows your values and can stay calm under pressure. Name a backup in case your first choice cannot act." },
      { name: "Decide what you want written down", text: "Think about life support, feeding tubes, CPR and comfort care. Explain your values, not just yes or no answers." },
      { name: "Use the form your state recognizes", text: "Many states offer a combined form. Add a HIPAA authorization so your agent and family can get information." },
      { name: "Sign the way your state requires", text: "Rules vary by state. Many require two adult witnesses, some accept a notary, and some ask for both." },
      { name: "Ask your doctor about POLST or DNR if you are seriously ill", text: "These are medical orders, so a clinician completes them with you. Keep the original where paramedics will see it." },
      { name: "Share copies and review them", text: "Give copies to your agent, doctors and hospital. Review your documents after a diagnosis, a move or a change in your wishes." },
    ],
  },
  faqs: [
    {
      q: "What are the different types of advance directives?",
      a: "The main advance directives are a healthcare power of attorney, which names who decides for you, and a living will, which states your treatment wishes. Many states combine them in one form. A HIPAA authorization is often signed with them. POLST and DNR forms are related, but they are medical orders signed by a clinician, not directives you write yourself.",
    },
    {
      q: "What is the difference between a living will and an advance directive?",
      a: "Advance directive is the umbrella term. It covers any document stating your medical wishes or naming someone to decide for you. A living will is one type of advance directive. It records which treatments you want or refuse. Some states use a single advance directive form that includes a living will and a healthcare agent.",
    },
    {
      q: "Is a healthcare proxy the same as a medical power of attorney?",
      a: "In most cases, yes. Healthcare proxy, medical power of attorney and healthcare power of attorney all describe a document that names a person to make medical decisions when you cannot. The term depends on your state. Some people also use healthcare proxy to mean the person named, also called your agent.",
    },
    {
      q: "Is a DNR the same as a living will?",
      a: "No. A living will is your own written statement about treatment you would want in future situations. A DNR is a medical order, signed by a clinician, that says not to attempt CPR. A DNR covers CPR only. Emergency crews generally follow an out-of-hospital DNR, but they may not follow a living will.",
    },
    {
      q: "What is a POLST and who needs one?",
      a: "A POLST is a portable medical order that records choices about CPR, the level of treatment and sometimes tube feeding. A clinician signs it with you or your representative. It is meant for people with serious illness or frailty. Healthy adults usually need a living will and a healthcare agent instead. Some states call it MOLST, MOST or POST.",
    },
    {
      q: "Does a living will need to be notarized?",
      a: "It depends on your state. Many states require two adult witnesses, who often cannot be relatives, heirs or your agent. Some states accept a notary instead. Using witnesses and a notary together can help hospitals and other states accept the document. Check your state's rules before you sign.",
    },
    {
      q: "Will paramedics follow my living will?",
      a: "Usually not. In an emergency, crews have little time and are trained to start treatment unless there is a valid out-of-hospital order. In many states that means a POLST or an out-of-hospital DNR form. If you are seriously ill and want limits honored at home, ask your doctor which form your state uses.",
    },
  ],
  related: [
    { href: "/learn/healthcare-directives", label: "Advance healthcare directives, the full guide" },
    { href: "/compare/living-will-vs-healthcare-power-of-attorney", label: "Living will vs healthcare power of attorney" },
    { href: "/learn/healthcare-directives/dnr-and-polst", label: "DNR orders and POLST forms" },
    { href: "/learn/healthcare-directives/does-a-living-will-need-a-notary", label: "Does a living will need a notary?" },
    { href: "/learn/healthcare-directives/dementia-and-advance-directives", label: "Dementia and advance directives" },
    { href: "/free/healthcare-wishes-conversation-guide", label: "Healthcare wishes conversation guide" },
  ],
};
