import { FIGURES, usdFigure } from "@/config/figures";
import type { DecisionGuide } from "./types";

const GIFT_EXCLUSION = usdFigure(FIGURES.annualGiftExclusion);
const LOOKBACK_YEARS = FIGURES.medicaidLookbackMonths / 12;

export const WAYS_TO_AVOID_PROBATE: DecisionGuide = {
  slug: "ways-to-avoid-probate",
  title: "Ways to avoid probate: which one should you pick?",
  h1: "Ways to avoid probate, compared side by side",
  description:
    "Seven ways to avoid probate on one page: living trusts, beneficiary forms, POD and TOD accounts, TOD deeds, joint ownership and more. See which fits you.",
  kicker: "Probate decision guide",
  art: "HeroProbate",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "Most people avoid probate by combining tools. Beneficiary forms cover retirement accounts and life insurance. Payable-on-death and transfer-on-death forms cover bank and brokerage accounts. A transfer-on-death deed or joint ownership can pass a home. A funded revocable living trust covers almost everything, plans for incapacity and holds money for minors. Small estates may qualify for a simpler court shortcut.",
  takeaways: [
    "Probate reaches only assets in your name alone with no named beneficiary. The goal is to give each asset a direct path.",
    "Beneficiary, POD and TOD forms are low cost and often cover the largest accounts. Keep them current and name backups.",
    "A funded living trust is the only tool here that also plans for incapacity and holds money for young heirs.",
    "Joint ownership and lifetime gifts avoid probate but can cost you control, tax benefits or creditor protection.",
    "Most families mix several tools. Rules on deeds and small estates vary by state, so check yours.",
  ],
  noun: "way to avoid probate",
  families: [
    { id: "trust", name: "A trust that holds it all", text: "One plan for most assets, with someone ready to step in if you cannot manage.", tone: "accent" },
    { id: "forms", name: "Name a person on the asset", text: "You keep full ownership, and a form or deed says who gets it at death.", tone: "sage" },
    { id: "ownership", name: "Change who owns it now", text: "Someone else owns all or part of the asset before you die. Simple, but you share or lose control.", tone: "clay" },
    { id: "shortcut", name: "A shortcut after death", text: "Not avoidance, but a faster, lighter process for estates under a state limit.", tone: "gold" },
  ],
  dimensions: [
    { id: "assets", label: "Assets it covers", help: "How many kinds of property this one tool can pass." },
    { id: "cost", label: "Cost to set up", help: "Relative cost and paperwork. More dots means more work.", inverse: true },
    { id: "incapacity", label: "Covers incapacity", help: "Can someone manage the asset if you cannot?" },
    { id: "minors", label: "Handles minors and backups", help: "Can it hold money for a child or pass to a backup heir?" },
    { id: "mistakes", label: "Risk of mistakes", help: "Forgotten assets, outdated forms or side effects. More dots means more risk.", inverse: true },
    { id: "privacy", label: "Keeps things private", help: "Does the transfer stay out of public court files?" },
    { id: "states", label: "Works across states", help: "Does one setup work for property in several states?" },
  ],
  options: [
    {
      id: "trust",
      name: "Revocable living trust",
      short: "Living trust",
      family: "trust",
      icon: "ScrollText",
      what: "A trust you control during your life. Assets you retitle into it pass to your heirs through a successor trustee, with no court case.",
      bestFor: ["Homeowners who want one plan for most assets", "People with property in more than one state", "Parents of minors or heirs who should not inherit outright"],
      watchOut: ["Only covers assets you actually retitle into it", "Costs more to set up than forms or deeds"],
      cells: {
        assets: { level: 3, text: "Almost anything, once funded" },
        cost: { level: 3, text: "Highest here, plus funding" },
        incapacity: { level: 3, text: "Yes, successor trustee steps in" },
        minors: { level: 3, text: "Yes, holds money until set ages" },
        mistakes: { level: 2, text: "Unfunded assets need probate" },
        privacy: { level: 3, text: "Yes, no court file" },
        states: { level: 3, text: "Yes, one trust for all" },
      },
      map: { x: 90, y: 88 },
      learn: { href: "/learn/trusts/revocable-living-trust", label: "Revocable living trusts explained" },
    },
    {
      id: "beneficiary",
      name: "Beneficiary designations",
      short: "Beneficiary forms",
      family: "forms",
      icon: "Umbrella",
      what: "A form you file with a retirement plan, IRA, annuity or life insurance company naming who receives the money when you die.",
      bestFor: ["Anyone with a 401(k), IRA or life insurance", "People who want a free, fast transfer for their largest accounts"],
      watchOut: ["The form overrides your will, so an old one can pay the wrong person", "Naming a minor or your estate can send money back to court"],
      cells: {
        assets: { level: 1, text: "Retirement accounts and insurance" },
        cost: { level: 0, text: "Usually free" },
        incapacity: { level: 0, text: "No" },
        minors: { level: 1, text: "Backups yes, minors poorly" },
        mistakes: { level: 2, text: "Outdated or missing forms" },
        privacy: { level: 3, text: "Yes, paid directly" },
        states: { level: 3, text: "Yes, set by the account" },
      },
      map: { x: 22, y: 22 },
      learn: { href: "/learn/beneficiary-designations", label: "Beneficiary designations explained" },
    },
    {
      id: "pod-tod",
      name: "Payable-on-death and transfer-on-death accounts",
      short: "POD and TOD",
      family: "forms",
      icon: "Wallet",
      what: "A designation on a bank, CD or brokerage account that names who claims the account at your death. You keep full control while alive.",
      bestFor: ["Bank and brokerage accounts in your name alone", "People who want to keep control and skip court for cash and investments"],
      watchOut: ["If the named person dies first with no backup, the account goes to probate", "Uneven splits can happen when account values change"],
      cells: {
        assets: { level: 1, text: "Bank and brokerage accounts" },
        cost: { level: 0, text: "Usually free" },
        incapacity: { level: 0, text: "No" },
        minors: { level: 1, text: "Minors may need a custodian" },
        mistakes: { level: 2, text: "No backup named" },
        privacy: { level: 3, text: "Yes, claimed directly" },
        states: { level: 3, text: "Yes, set by the account" },
      },
      map: { x: 36, y: 14 },
      learn: { href: "/learn/beneficiary-designations/payable-on-death-and-transfer-on-death-accounts", label: "POD and TOD accounts explained" },
    },
    {
      id: "tod-deed",
      name: "Transfer-on-death deed",
      short: "TOD deed",
      family: "forms",
      icon: "House",
      what: "A recorded deed, allowed in many states, that names who receives your real estate at death. You stay the owner and can revoke it.",
      bestFor: ["Owners of one home in a state that allows these deeds", "Homeowners with adult heirs who want a low-cost route"],
      watchOut: ["Not every state allows it, and it must be recorded before death", "Does not help if you become unable to manage"],
      cells: {
        assets: { level: 1, text: "Real estate only" },
        cost: { level: 1, text: "Low, a recorded deed" },
        incapacity: { level: 0, text: "No" },
        minors: { level: 1, text: "Backups in some states" },
        mistakes: { level: 2, text: "Not recorded, or no backup" },
        privacy: { level: 2, text: "No court file, deed is public" },
        states: { level: 1, text: "Only where allowed" },
      },
      map: { x: 50, y: 24 },
      learn: { href: "/learn/beneficiary-designations/transfer-on-death-deed", label: "Transfer-on-death deeds explained" },
    },
    {
      id: "joint",
      name: "Joint ownership with right of survivorship",
      short: "Joint ownership",
      family: "ownership",
      icon: "Users",
      what: "Owning property with another person so that, when one owner dies, the survivor takes the whole thing automatically.",
      bestFor: ["Married couples sharing a home and bank accounts", "Spouses who want the survivor to take over without court"],
      watchOut: ["Adding a child exposes the asset to their creditors, divorce and decisions", "Can cause gift tax and capital gains surprises"],
      cells: {
        assets: { level: 2, text: "Homes, accounts, vehicles" },
        cost: { level: 1, text: "Low" },
        incapacity: { level: 1, text: "Partly, co-owner can act" },
        minors: { level: 0, text: "No, survivor takes all" },
        mistakes: { level: 3, text: "Creditors, control and taxes" },
        privacy: { level: 2, text: "Mostly, no court file" },
        states: { level: 2, text: "Widely used, rules vary" },
      },
      map: { x: 64, y: 46 },
      learn: { href: "/learn/property-and-assets/joint-tenancy-risks", label: "Risks of joint ownership" },
    },
    {
      id: "gifting",
      name: "Gifts during your life",
      short: "Lifetime gifts",
      family: "ownership",
      icon: "Gift",
      what: "Giving money or property away while you are alive, so it is no longer yours to pass through probate.",
      bestFor: ["People with more than they will need who want to help family now", `Yearly gifts up to ${GIFT_EXCLUSION} per person, which need no gift tax return`],
      watchOut: ["You lose control and access, and heirs may lose the step-up in basis", `Gifts within the ${LOOKBACK_YEARS}-year Medicaid look-back can delay coverage in most states`],
      cells: {
        assets: { level: 2, text: "Anything you give away" },
        cost: { level: 1, text: "Low, tax form if large" },
        incapacity: { level: 0, text: "No" },
        minors: { level: 1, text: "Needs a custodian or trust" },
        mistakes: { level: 3, text: "Control, basis and Medicaid" },
        privacy: { level: 3, text: "Yes, private" },
        states: { level: 3, text: "Yes" },
      },
      map: { x: 78, y: 30 },
      learn: { href: "/learn/estate-tax/gifting-strategies", label: "Gifting strategies explained" },
    },
    {
      id: "small-estate",
      name: "Small estate affidavit or simplified probate",
      short: "Small estate",
      family: "shortcut",
      icon: "Receipt",
      what: "A state shortcut that lets heirs collect a modest estate with a sworn affidavit or short filing instead of full probate.",
      bestFor: ["Estates with few assets left in the person's sole name", "Families where most assets already have beneficiaries"],
      watchOut: ["Limits and waiting periods vary widely by state", "Real estate is often excluded or needs a separate process"],
      cells: {
        assets: { level: 1, text: "Small probate estates only" },
        cost: { level: 0, text: "No planning cost" },
        incapacity: { level: 0, text: "No" },
        minors: { level: 0, text: "No, heirs by will or law" },
        mistakes: { level: 1, text: "Estate may exceed the limit" },
        privacy: { level: 2, text: "Often no court filing" },
        states: { level: 1, text: "Each state has its own" },
      },
      map: { x: 8, y: 10 },
      learn: { href: "/learn/probate/small-estate-affidavit", label: "Small estate procedures explained" },
    },
  ],
  map: {
    title: "The probate map",
    lead: "Tools on the left cost little and pass one kind of asset. Moving right, setup takes more work. Moving up, the tool also manages money for you or your heirs.",
    x: { low: "Little or no setup", high: "More setup and cost" },
    y: { low: "Passes the asset only", high: "Also manages money for people" },
  },
  questions: [
    {
      id: "assets",
      prompt: "What do you own?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "home", label: "A home or other real estate", weights: { trust: 3, "tod-deed": 3, joint: 1 }, reason: "Real estate in your name alone usually needs probate" },
        { id: "bank", label: "Bank accounts or CDs", weights: { "pod-tod": 3, joint: 1 }, reason: "Bank accounts can pass with a payable-on-death form" },
        { id: "brokerage", label: "Brokerage or investment accounts", weights: { "pod-tod": 3, trust: 1 }, reason: "Brokerage accounts can be registered transfer-on-death" },
        { id: "retirement", label: "Retirement accounts or life insurance", weights: { beneficiary: 4 }, reason: "Retirement accounts and life insurance pass by beneficiary form" },
        { id: "business", label: "A business or other assets with no beneficiary option", weights: { trust: 3 }, reason: "A trust can hold assets that have no beneficiary form" },
        { id: "personal", label: "Mainly a car and personal belongings", weights: { "small-estate": 3, trust: 1 }, reason: "Cars and belongings often fit a small estate process" },
      ],
    },
    {
      id: "states",
      prompt: "Do you own real estate in more than one state?",
      choices: [
        { id: "yes", label: "Yes, in two or more states", weights: { trust: 4, "tod-deed": -1 }, reason: "Property in two states can mean probate in each one" },
        { id: "no", label: "No, only in one state", weights: { "tod-deed": 1 } },
        { id: "none", label: "I do not own real estate", weights: { "small-estate": 1, "pod-tod": 1, "tod-deed": -3 } },
      ],
    },
    {
      id: "value",
      prompt: "Roughly what is everything worth, not counting accounts with beneficiaries?",
      help: "Small estate limits vary widely by state. A rough guess is fine.",
      choices: [
        { id: "small", label: "Modest, likely under my state's small estate limit", weights: { "small-estate": 4, beneficiary: 1, "pod-tod": 1 }, reason: "Your estate may qualify for your state's small estate shortcut" },
        { id: "mid", label: "More than that, but under $1 million", weights: { "pod-tod": 1, "tod-deed": 1, trust: 1 } },
        { id: "large", label: "$1 million or more", weights: { trust: 3, gifting: 1 }, reason: "Larger estates often hold many kinds of assets that are easier to manage in one trust" },
        { id: "unsure", label: "Not sure", weights: {} },
      ],
    },
    {
      id: "incapacity",
      prompt: "Do you want the same plan to cover a time when you cannot manage your money?",
      choices: [
        { id: "yes", label: "Yes", weights: { trust: 4, joint: 1 }, reason: "You want someone ready to manage your money if you cannot" },
        { id: "poa", label: "I have, or will get, a power of attorney for that", weights: { beneficiary: 1, "pod-tod": 1, "tod-deed": 1 } },
        { id: "no", label: "Not a priority right now", weights: {} },
      ],
    },
    {
      id: "heirs",
      prompt: "Who will inherit from you?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "minors", label: "Children under 18", weights: { trust: 4, joint: -2, "small-estate": -1 }, reason: "Minor children cannot manage an inheritance directly" },
        { id: "careful", label: "Someone who struggles with money or gets benefits", weights: { trust: 4, joint: -2, beneficiary: -1, "pod-tod": -1 }, reason: "Some heirs are safer receiving money through a trust" },
        { id: "spouse", label: "My spouse first", weights: { joint: 2, trust: 1 }, reason: "Spouses often own property jointly so the survivor takes over" },
        { id: "adults", label: "Adults who can handle money", weights: { beneficiary: 1, "pod-tod": 1, "tod-deed": 1 } },
      ],
    },
    {
      id: "style",
      prompt: "Which sounds most like you?",
      choices: [
        { id: "simple", label: "Keep it simple and low cost", weights: { beneficiary: 2, "pod-tod": 2, "tod-deed": 2, "small-estate": 1, trust: -2 }, reason: "You want the simplest, lowest-cost route" },
        { id: "organized", label: "One organized plan, even if it costs more", weights: { trust: 4 }, reason: "You want one plan that covers everything" },
        { id: "shared", label: "Keep things shared with my spouse", weights: { joint: 4, trust: 1 }, reason: "You want shared assets to pass to your spouse automatically" },
        { id: "give", label: "Give some assets away now", weights: { gifting: 6, joint: 1 }, reason: "You are open to giving assets away during your life" },
      ],
    },
  ],
  resultNote:
    "Most families use more than one of these tools, often a will or living trust plus beneficiary forms. A short consult confirms which ones your state allows and how they fit together.",
  shortcuts: [
    { when: "You own a home and want one plan that also covers incapacity", pick: "trust" },
    { when: "You own real estate in more than one state", pick: "trust" },
    { when: "You have a 401(k), IRA or life insurance", pick: "beneficiary" },
    { when: "You want bank and brokerage accounts to skip court", pick: "pod-tod" },
    { when: "You own one home, your heirs are adults and your state allows TOD deeds", pick: "tod-deed" },
    { when: "You are married and want the survivor to take the house", pick: "joint" },
    { when: "You would rather help your children now than later", pick: "gifting" },
    { when: "Your estate is modest and most accounts already have beneficiaries", pick: "small-estate" },
  ],
  diagrams: ["TodPodTransfers", "ProbateVsTrustComparison"],
  howTo: {
    name: "How to choose a way to avoid probate",
    steps: [
      { name: "List what you own", text: "Write down each asset and how it is titled: your name alone, joint, or with a beneficiary already named." },
      { name: "Fill the easy gaps first", text: "Name primary and backup beneficiaries on retirement accounts and life insurance. Add POD or TOD forms to bank and brokerage accounts." },
      { name: "Pick a route for real estate", text: "Choose a TOD deed if your state allows one, joint ownership with a spouse, or a living trust. Property in two states points to a trust." },
      { name: "Check your heirs and incapacity needs", text: "If an heir is a minor or should not get money outright, or you want a plan for incapacity, consider a living trust." },
      { name: "Sign, record and retitle", text: "Record deeds with the county, retitle assets into any trust, and keep a simple will to catch anything left out." },
      { name: "Review every few years", text: "Recheck forms and titles after a marriage, divorce, death, move or new account, so nothing slips back into probate." },
    ],
  },
  faqs: [
    {
      q: "What is the cheapest way to avoid probate?",
      a: "Beneficiary designations and payable-on-death or transfer-on-death forms usually cost nothing. You fill out a form with each bank, brokerage firm, retirement plan or insurer. In states that allow it, a transfer-on-death deed can pass a home for the cost of preparing and recording a deed. The catch is that each form covers only one asset, so you must keep every one current.",
    },
    {
      q: "Can you avoid probate without a trust?",
      a: "Yes. Many families avoid most or all probate with beneficiary forms, POD and TOD accounts, a transfer-on-death deed and joint ownership with a spouse. A trust adds value when you own property in several states, have minor heirs, own assets without a beneficiary option, or want a plan for incapacity.",
    },
    {
      q: "What assets do not go through probate?",
      a: "Assets with a named beneficiary, such as retirement accounts, life insurance and POD or TOD accounts, generally skip probate. So does property held jointly with right of survivorship and anything owned by a living trust. Assets in your name alone with no beneficiary, such as a car or belongings, usually go through probate unless a small estate shortcut applies.",
    },
    {
      q: "Does joint ownership avoid probate?",
      a: "Joint ownership with right of survivorship usually does, because the surviving owner takes the whole asset automatically. It works well between spouses. Adding a child is riskier: the child's creditors or divorce can reach the asset, you share control, and there can be tax costs. When the last owner dies, the asset may still need probate.",
    },
    {
      q: "What is the probate limit in my state?",
      a: "Each state sets its own small estate limit, and they vary widely. Some are tens of thousands of dollars and others are far higher. Many states count only assets without beneficiaries, and some treat real estate separately. Legislatures change these amounts, so check your state court's website or ask an attorney licensed in your state.",
    },
    {
      q: "Does a will avoid probate?",
      a: "No. A will is the document that probate court reviews and carries out. It names your executor and says who gets what, but the court still oversees the process. Only assets that pass outside the will, such as accounts with beneficiaries or property in a trust, skip probate.",
    },
    {
      q: "What happens if my beneficiary dies before me?",
      a: "If you named a backup, the asset usually goes to that person. If there is no living beneficiary and no backup, the asset often falls back into your estate and goes through probate. Some forms and state laws pass the share to the beneficiary's children. Naming a contingent beneficiary on every form avoids most of this.",
    },
  ],
  related: [
    { href: "/learn/probate/how-to-avoid-probate", label: "How to avoid probate, tool by tool" },
    { href: "/learn/probate/probate-vs-non-probate-assets", label: "Probate vs non-probate assets" },
    { href: "/compare/transfer-on-death-deed-vs-trust", label: "Transfer-on-death deed vs trust" },
    { href: "/compare/joint-ownership-vs-trust", label: "Joint ownership vs trust" },
    { href: "/decide/types-of-trusts", label: "Types of trusts, and which one fits" },
    { href: "/tools/probate-cost-estimator", label: "Probate cost estimator" },
  ],
};
