import type { DecisionGuide } from "./types";

export const GUARDIANSHIP_VS_CONSERVATORSHIP: DecisionGuide = {
  slug: "guardianship-vs-conservatorship",
  title: "Guardianship vs conservatorship vs power of attorney",
  h1: "Guardianship vs conservatorship, and the options in between",
  description:
    "Guardianship, conservatorship, power of attorney and less restrictive options compared on one page. Answer six questions to see what fits a parent or adult child.",
  kicker: "Adult guardianship decision guide",
  art: "HeroAgingParents",
  tone: "gold",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "Guardianship and conservatorship are both court processes for an adult who can no longer decide safely. In many states a guardian handles personal and medical decisions and a conservator handles money, though some states use one term for both. If the person can still sign, a durable and healthcare power of attorney usually avoids court. Supported decision-making and limited orders keep more rights.",
  takeaways: [
    "The key question is whether the person can still understand and sign a document. If yes, powers of attorney usually avoid court.",
    "Guardianship and conservatorship both need a judge. They differ in what they cover: personal care or money.",
    "The names change by state. Some states say guardian for both, Florida says guardian of the person or property, and California says conservator of the person or estate.",
    "Many states expect courts to consider less restrictive options first, such as supported decision-making or a limited order.",
    "A court appointment brings ongoing duties, such as yearly reports and accountings, and is hard to undo.",
  ],
  noun: "option",
  families: [
    { id: "signed", name: "Documents the person signs", text: "The person picks their own helpers while they can, and no judge is involved.", tone: "accent" },
    { id: "benefits", name: "Help with benefits only", text: "A government agency appoints someone to manage one benefit check, without a court.", tone: "gold" },
    { id: "tailored", name: "A tailored court order", text: "A judge gives someone authority only in the areas where the person needs it.", tone: "sage" },
    { id: "court", name: "Full court appointment", text: "A judge appoints someone to make personal or money decisions, with ongoing court oversight.", tone: "clay" },
  ],
  dimensions: [
    { id: "court", label: "Court involved", help: "Does a judge appoint and supervise the helper? More dots means more court.", inverse: true },
    { id: "choose", label: "Person picks the helper", help: "Does the person choose who helps them?" },
    { id: "rights", label: "Rights the person keeps", help: "How much legal say the person keeps over their own life." },
    { id: "money", label: "Covers money", help: "Bills, bank accounts, benefits and property." },
    { id: "care", label: "Covers health and daily care", help: "Medical choices, where to live and daily care." },
    { id: "nocap", label: "Works if they cannot sign now", help: "Can it be set up if the person no longer understands documents?" },
    { id: "effort", label: "Cost, time and reporting", help: "Relative cost, delay and ongoing paperwork. Rules vary by state. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "poa",
      name: "Durable and healthcare powers of attorney",
      short: "Power of attorney",
      family: "signed",
      icon: "FileSignature",
      what: "Documents the person signs while they still have capacity, naming agents to handle money and medical decisions if they later cannot.",
      bestFor: ["Aging parents who can still understand what they sign", "Young adults with a disability who can choose an agent", "Anyone who wants to stay out of court"],
      watchOut: ["Must be signed while the person has capacity", "An agent can misuse broad powers, so choose with care"],
      cells: {
        court: { level: 0, text: "None in most cases" },
        choose: { level: 3, text: "Yes, they name agents" },
        rights: { level: 3, text: "Keeps all rights" },
        money: { level: 3, text: "Yes, financial power" },
        care: { level: 3, text: "Yes, healthcare power" },
        nocap: { level: 0, text: "No, must sign while capable" },
        effort: { level: 1, text: "Low, signed once" },
      },
      map: { x: 24, y: 78 },
      learn: { href: "/learn/power-of-attorney", label: "Powers of attorney explained" },
    },
    {
      id: "sdm",
      name: "Supported decision-making agreement",
      short: "Supported decisions",
      family: "signed",
      icon: "Users",
      what: "An agreement in which the person picks trusted supporters to help them understand choices, while the person still makes the decisions.",
      bestFor: ["Young adults with a disability who can decide with help", "Older adults with mild memory or planning problems"],
      watchOut: ["Some states have no law for it, so doctors or banks may not honor it", "Supporters cannot act or sign for the person"],
      cells: {
        court: { level: 0, text: "Usually none" },
        choose: { level: 3, text: "Yes, they pick supporters" },
        rights: { level: 3, text: "Keeps all rights" },
        money: { level: 1, text: "Support, person decides" },
        care: { level: 1, text: "Support, person decides" },
        nocap: { level: 1, text: "Needs ability to agree" },
        effort: { level: 1, text: "Low, a written agreement" },
      },
      map: { x: 10, y: 22 },
      learn: { href: "/learn/special-needs/guardianship-alternatives-for-adult-children", label: "Guardianship alternatives at 18" },
    },
    {
      id: "payee",
      name: "Representative payee for Social Security",
      short: "Rep payee",
      family: "benefits",
      icon: "Receipt",
      what: "A person the Social Security Administration appoints to receive and manage someone's Social Security or SSI payments for their needs.",
      bestFor: ["People whose main income is a Social Security or SSI check", "Parents managing an adult child's SSI"],
      watchOut: ["Covers only Social Security payments, not other money or medical care", "The payee must use the money for the person and keep records"],
      cells: {
        court: { level: 0, text: "No, Social Security appoints" },
        choose: { level: 1, text: "Agency decides" },
        rights: { level: 3, text: "Keeps other rights" },
        money: { level: 1, text: "Social Security benefits only" },
        care: { level: 0, text: "No" },
        nocap: { level: 3, text: "Yes" },
        effort: { level: 1, text: "Low, agency paperwork" },
      },
      map: { x: 38, y: 14 },
    },
    {
      id: "limited",
      name: "Limited guardianship or conservatorship",
      short: "Limited order",
      family: "tailored",
      icon: "Scale",
      what: "A court order that gives a guardian or conservator authority only in the areas where the person needs help, such as medical consent or a bank account.",
      bestFor: ["Adults who can handle some decisions but not others", "Young adults with a disability who need help in one or two areas"],
      watchOut: ["Still a court case, with costs and reports", "Not offered the same way in every state"],
      cells: {
        court: { level: 3, text: "Yes, petition and hearing" },
        choose: { level: 1, text: "Judge appoints" },
        rights: { level: 2, text: "Keeps rights outside the order" },
        money: { level: 2, text: "If the order covers it" },
        care: { level: 2, text: "If the order covers it" },
        nocap: { level: 3, text: "Yes" },
        effort: { level: 2, text: "Court costs, yearly reports" },
      },
      map: { x: 54, y: 46 },
      learn: { href: "/learn/special-needs/guardianship-alternatives-for-adult-children", label: "Full and limited guardianship" },
    },
    {
      id: "guardian",
      name: "Guardianship of the person",
      short: "Guardian",
      family: "court",
      icon: "Stethoscope",
      what: "A court appointment of someone to make personal decisions for an adult, such as medical care, where they live and daily care.",
      bestFor: ["Adults who cannot understand or share choices about care", "Someone with no healthcare agent who needs medical decisions made"],
      watchOut: ["The person can lose many personal rights", "Hard to end, and the court supervises for years"],
      cells: {
        court: { level: 3, text: "Yes, start to finish" },
        choose: { level: 1, text: "Judge appoints" },
        rights: { level: 1, text: "Loses many personal rights" },
        money: { level: 0, text: "Not by itself" },
        care: { level: 3, text: "Medical, housing, daily care" },
        nocap: { level: 3, text: "Yes" },
        effort: { level: 3, text: "High, yearly court reports" },
      },
      map: { x: 72, y: 62 },
      learn: { href: "/learn/what-if/incapacitated-without-power-of-attorney", label: "Incapacity without a power of attorney" },
    },
    {
      id: "conservator",
      name: "Conservatorship or guardianship of the estate",
      short: "Conservator",
      family: "court",
      icon: "Landmark",
      what: "A court appointment of someone to manage an adult's money and property, with regular accountings to the court.",
      bestFor: ["Adults who can no longer manage money and signed no power of attorney", "Cases where an agent is misusing a power of attorney"],
      watchOut: ["Many sales and big spending decisions may need court approval", "Yearly accountings, and often a bond, add cost"],
      cells: {
        court: { level: 3, text: "Yes, start to finish" },
        choose: { level: 1, text: "Judge appoints" },
        rights: { level: 1, text: "Loses control of money" },
        money: { level: 3, text: "All assets and income" },
        care: { level: 0, text: "Not by itself" },
        nocap: { level: 3, text: "Yes" },
        effort: { level: 3, text: "High, accountings, often a bond" },
      },
      map: { x: 88, y: 86 },
      learn: { href: "/learn/power-of-attorney/parent-with-dementia-no-power-of-attorney", label: "A parent with dementia and no power of attorney" },
    },
  ],
  map: {
    title: "The guardianship map",
    lead: "Options on the left keep the person in charge of their own life. Moving right, a court takes over more decisions. Higher options give the helper broader authority.",
    x: { low: "Person keeps their rights", high: "Court takes over decisions" },
    y: { low: "Narrow help", high: "Broad authority" },
  },
  questions: [
    {
      id: "who",
      prompt: "Who needs help?",
      help: "This guide covers adults. For a child under 18, see guardianship for minor children.",
      choices: [
        { id: "parent", label: "An aging parent or spouse", weights: { poa: 1, conservator: 1 } },
        { id: "adult-child", label: "My adult child with a disability, or one turning 18", weights: { sdm: 2, limited: 2, poa: 1, payee: 1 }, reason: "Families of young adults with disabilities often start with less restrictive tools" },
        { id: "other", label: "Another adult relative or friend", weights: { poa: 1 } },
      ],
    },
    {
      id: "capacity",
      prompt: "Can they still understand and sign a legal document?",
      help: "Capacity to sign is a lower bar than managing everything alone. An attorney can often tell after a meeting.",
      choices: [
        { id: "yes", label: "Yes, they understand what they would sign", weights: { poa: 6, sdm: 3, limited: -2, guardian: -3, conservator: -3 }, reason: "They can still sign, so they can choose their own helpers without court" },
        { id: "partly", label: "Partly, they handle some things but not others", weights: { limited: 4, sdm: 2, poa: 1, payee: 1 }, reason: "They can still handle some decisions, so help can match the gaps" },
        { id: "no", label: "No, they cannot understand or share choices", weights: { poa: -6, sdm: -3, guardian: 3, conservator: 3, limited: 1, payee: 1 }, reason: "They can no longer sign, so a court may need to appoint someone" },
        { id: "unsure", label: "Not sure", weights: { poa: 1, limited: 1 } },
      ],
    },
    {
      id: "need",
      prompt: "What do they need help with?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "money", label: "Bills, bank accounts and property", weights: { conservator: 3, poa: 2 }, reason: "You need someone with legal authority over money" },
        { id: "benefits", label: "Only a Social Security or SSI check", weights: { payee: 7 }, reason: "Their only income to manage is Social Security or SSI" },
        { id: "medical", label: "Medical decisions and talking with doctors", weights: { guardian: 2, poa: 2, sdm: 1 }, reason: "You need someone who can make medical decisions" },
        { id: "living", label: "Where they live and daily care", weights: { guardian: 3, limited: 1 }, reason: "Decisions about housing and daily care may need a guardian" },
        { id: "understanding", label: "Understanding choices, not someone deciding for them", weights: { sdm: 5 }, reason: "They mainly need help understanding choices, not a substitute decision-maker" },
      ],
    },
    {
      id: "docs",
      prompt: "Do they already have a power of attorney or healthcare proxy?",
      choices: [
        { id: "working", label: "Yes, and it is working", weights: { poa: 5, limited: -2, guardian: -3, conservator: -3 }, reason: "Valid documents already in place usually avoid court" },
        { id: "misuse", label: "Yes, but the agent may be misusing it", weights: { conservator: 3, guardian: 1, limited: 1 }, reason: "A court can step in when an agent may be misusing power" },
        { id: "none", label: "No", weights: { guardian: 1, conservator: 1, sdm: 1 } },
        { id: "unsure", label: "Not sure", weights: {} },
      ],
    },
    {
      id: "urgency",
      prompt: "How urgent is it?",
      choices: [
        { id: "crisis", label: "A crisis now", detail: "Hospital discharge, unpaid bills or suspected abuse", weights: { guardian: 2, conservator: 2, poa: 1 }, reason: "In an emergency, many states allow a temporary court appointment" },
        { id: "soon", label: "Within the next few months", weights: {} },
        { id: "planning", label: "We are planning ahead", weights: { poa: 3, sdm: 2, guardian: -1, conservator: -1 }, reason: "Planning ahead is when signed documents work best" },
      ],
    },
    {
      id: "independence",
      prompt: "How much independence should they keep?",
      choices: [
        { id: "most", label: "As much as possible, with help where needed", weights: { sdm: 3, limited: 3, poa: 1, payee: 1, guardian: -1, conservator: -1 }, reason: "You want them to keep as many rights as possible" },
        { id: "some", label: "Someone should decide in one or two areas", weights: { limited: 5, payee: 1, guardian: -1 }, reason: "Help is needed in only some areas" },
        { id: "full", label: "They need someone to make most decisions", weights: { guardian: 3, conservator: 3 }, reason: "They need someone to make most decisions for them" },
      ],
    },
  ],
  resultNote:
    "Names and rules vary by state, and many states expect courts to try less restrictive options first. A short consult with an attorney licensed in your state confirms the right route.",
  shortcuts: [
    { when: "Your parent can still understand and sign documents", pick: "poa" },
    { when: "Your adult child can decide with help explaining the choices", pick: "sdm" },
    { when: "The only money to manage is a Social Security or SSI check", pick: "payee" },
    { when: "The person handles some decisions well but not others", pick: "limited" },
    { when: "Someone cannot make medical or housing choices and has no healthcare agent", pick: "guardian" },
    { when: "A parent can no longer manage money and signed no power of attorney", pick: "conservator" },
    { when: "An agent under a power of attorney may be misusing it", pick: "conservator" },
  ],
  diagrams: ["PoaHealthcareRoles"],
  howTo: {
    name: "How to choose between guardianship, conservatorship and the alternatives",
    steps: [
      { name: "Check whether they can still sign", text: "Ask their doctor and an attorney whether the person understands what a power of attorney does. Many people with early dementia or a disability still can." },
      { name: "Use signed documents first", text: "If they can sign, have them sign a durable financial power of attorney, a healthcare power of attorney and a HIPAA release." },
      { name: "List the areas where they need help", text: "Write down money, benefits, medical care, housing and daily safety. Note which ones they still handle well, with or without support." },
      { name: "Try less restrictive tools", text: "Consider supported decision-making, a representative payee, a joint account or an ABLE account before going to court." },
      { name: "If court is needed, ask for only what fits", text: "File a petition in the county where the person lives. Most states require notice, a medical evaluation and a hearing. Ask whether a limited order would work." },
      { name: "Keep up with court duties", text: "After an appointment, expect an inventory, yearly reports or accountings, and court approval for some decisions. Rules vary by state." },
    ],
  },
  faqs: [
    { q: "What is the difference between a guardian and a conservator?", a: "In many states, a guardian makes personal decisions, such as medical care and where someone lives, and a conservator manages money and property. Some states use guardian for both. Florida uses guardian of the person and guardian of the property. California uses conservator of the person and conservator of the estate. A court appoints both." },
    { q: "Is a power of attorney better than guardianship?", a: "For most people who can still sign, yes. A power of attorney lets the person choose their own agent, stays private and avoids court costs and yearly reports. Guardianship is usually the fallback when no valid documents exist, the person can no longer sign, or an agent is misusing their power." },
    { q: "How do I get guardianship of my elderly parent?", a: "You file a petition with the court in the county where your parent lives. In most states the court requires a medical evaluation, notice to your parent and close relatives, and a hearing. Your parent often gets their own lawyer or a court visitor. Many states also offer temporary orders for emergencies." },
    { q: "How much does a guardianship or conservatorship cost?", a: "Costs vary widely by state and by whether anyone objects. Expect court filing fees, attorney fees, a medical evaluation, and sometimes fees for a court visitor or the person's own lawyer. Conservators may also need a bond and yearly accountings. Signing powers of attorney ahead of time usually costs much less." },
    { q: "Can a power of attorney override a guardian?", a: "Usually not. In many states, a court-appointed guardian or conservator can limit or revoke an agent's authority, and the agent must answer to them. But courts often honor the person's own choices. Many states let a power of attorney nominate who should serve as guardian if one is ever needed." },
    { q: "Can you get guardianship without going to court?", a: "No. Guardianship and conservatorship always require a court order. To avoid court, the person can sign powers of attorney while they still have capacity. Other tools include supported decision-making and a Social Security representative payee." },
    { q: "Do parents need guardianship when a child with a disability turns 18?", a: "Not always. At 18 parents lose automatic legal authority, but many young adults can sign a power of attorney, a healthcare proxy and a HIPAA release. Others use supported decision-making. Guardianship, often limited, may fit when the young adult cannot understand or share choices even with support." },
    { q: "Can a guardianship or conservatorship be ended?", a: "Yes, in most states. The person, or someone on their behalf, can ask the court to change or end the order if their abilities improve or the need passes. It also ends at death. The process and evidence needed vary by state, so keep records of the person's progress." },
  ],
  related: [
    { href: "/learn/power-of-attorney/power-of-attorney-vs-guardianship", label: "Power of attorney vs guardianship" },
    { href: "/learn/power-of-attorney/parent-with-dementia-no-power-of-attorney", label: "A parent with dementia and no power of attorney" },
    { href: "/learn/special-needs/guardianship-alternatives-for-adult-children", label: "Turning 18 with a disability" },
    { href: "/learn/healthcare-directives/healthcare-power-of-attorney", label: "Healthcare power of attorney" },
    { href: "/learn/elder-care/elder-financial-abuse", label: "Elder financial abuse" },
    { href: "/learn/guardianship", label: "Guardians for minor children" },
  ],
};
