import { FIGURES, usdFigure } from "@/config/figures";
import type { DecisionGuide } from "./types";

const ABLE_LIMIT = usdFigure(FIGURES.ableAnnualContributionLimit);

export const ALTERNATIVES_TO_GUARDIANSHIP: DecisionGuide = {
  slug: "alternatives-to-guardianship",
  title: "Alternatives to adult guardianship: 9 options compared",
  h1: "Alternatives to adult guardianship, and when you still need one",
  description:
    "Supported decision-making, powers of attorney, HIPAA releases, rep payee, ABLE accounts and limited guardianship compared for an adult child or a parent with dementia.",
  kicker: "Adult guardianship alternatives guide",
  art: "HeroSpecialNeeds",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "If the adult can understand and sign a simple document, guardianship is often avoidable. A power of attorney for property, a healthcare power of attorney, a HIPAA release and supported decision-making cover most needs, and a rep payee or ABLE account can handle benefits and savings. You still need a guardian when the person cannot understand choices even with help and nothing was signed. Illinois courts favor a limited guardianship over a plenary one.",
  takeaways: [
    "At 18, parents lose legal authority over an adult child, even one who needs a lot of support. The same is true for a spouse or child of an adult with dementia.",
    "Signed documents only work if the person understands them. Many young adults with a disability and many people with early dementia still can sign.",
    "In Illinois, adult guardians are called guardian of the person (care and health) and guardian of the estate (money). Illinois does not use the word conservator.",
    "Benefits and savings have their own tools. A rep payee handles a Social Security check, and a special needs trust or ABLE account holds money without hurting SSI or Medicaid.",
    "If court is needed, ask for only what is needed. A limited guardianship leaves the person every right the order does not take.",
  ],
  noun: "option",
  families: [
    { id: "signed", name: "Choices the person makes", text: "The adult signs documents or an agreement naming who helps them. No court is involved.", tone: "accent" },
    { id: "money", name: "Tools for benefits and savings", text: "Ways to manage a benefit check or hold money without risking SSI or Medicaid.", tone: "gold" },
    { id: "limited", name: "A targeted court order", text: "A judge gives a guardian power only in the areas, or for the time, where it is needed.", tone: "sage" },
    { id: "court", name: "Full guardianship", text: "A judge appoints a guardian to make most decisions, with court oversight for years.", tone: "clay" },
  ],
  dimensions: [
    { id: "rights", label: "Rights the person keeps", help: "How much legal say the adult keeps over their own life." },
    { id: "money", label: "Covers money", help: "Bank accounts, bills, benefits and savings." },
    { id: "care", label: "Covers health and daily care", help: "Medical decisions, records, where to live and daily care." },
    { id: "nocap", label: "Works if they cannot sign", help: "Can it be put in place if the adult cannot understand a document?" },
    { id: "court", label: "Court involved", help: "Does a judge appoint and supervise? More dots means more court.", inverse: true },
    { id: "effort", label: "Cost and paperwork", help: "Relative cost, delay and ongoing reports. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "sdm",
      name: "Supported decision-making agreement",
      short: "Supported decisions",
      family: "signed",
      icon: "Handshake",
      what: "A written agreement in which the adult picks supporters to help them understand choices and share their decisions, while the adult still decides. Illinois has a Supported Decision-Making Agreement Act for adults with intellectual or developmental disabilities.",
      bestFor: ["A young adult with a disability who can decide with help explaining things", "Families who want to keep the adult in charge of their own life"],
      watchOut: ["Supporters cannot sign or decide for the person", "Some doctors and banks are not used to these agreements, so pair it with a HIPAA release and powers of attorney"],
      cells: {
        rights: { level: 3, text: "Keeps every right" },
        money: { level: 1, text: "Support only, adult decides" },
        care: { level: 1, text: "Support only, adult decides" },
        nocap: { level: 1, text: "Needs ability to agree" },
        court: { level: 0, text: "None" },
        effort: { level: 0, text: "Low, a written agreement" },
      },
      map: { x: 6, y: 40 },
      learn: { href: "/learn/special-needs/guardianship-alternatives-for-adult-children", label: "Turning 18 with a disability" },
    },
    {
      id: "poa",
      name: "Power of attorney for property",
      short: "Property POA",
      family: "signed",
      icon: "FileSignature",
      what: "A document the adult signs naming an agent to handle bank accounts, bills and property. In Illinois, the statutory short form is signed before a notary and a witness.",
      bestFor: ["A parent with early dementia who can still sign", "A young adult who trusts a parent to help with money"],
      watchOut: ["Must be signed while the person understands it", "Does not cover Social Security or VA checks"],
      cells: {
        rights: { level: 3, text: "Keeps every right" },
        money: { level: 3, text: "Accounts, bills, property" },
        care: { level: 0, text: "No" },
        nocap: { level: 0, text: "No, must sign in time" },
        court: { level: 0, text: "None" },
        effort: { level: 1, text: "Low, one signing" },
      },
      map: { x: 14, y: 80 },
      learn: { href: "/learn/power-of-attorney/durable-financial-power-of-attorney", label: "Durable financial power of attorney" },
    },
    {
      id: "hcpoa",
      name: "Healthcare power of attorney",
      short: "Healthcare POA",
      family: "signed",
      icon: "Stethoscope",
      what: "A document the adult signs naming an agent to make medical decisions when they cannot. Illinois has its own statutory short form for health care.",
      bestFor: ["Anyone who needs a trusted person to talk to doctors and consent to care", "A young adult who wants a parent to step in during a hospital stay"],
      watchOut: ["Must be signed while the person understands it", "Covers medical care, not money or where to live day to day"],
      cells: {
        rights: { level: 3, text: "Keeps every right" },
        money: { level: 0, text: "No" },
        care: { level: 3, text: "Medical decisions" },
        nocap: { level: 0, text: "No, must sign in time" },
        court: { level: 0, text: "None" },
        effort: { level: 1, text: "Low, one signing" },
      },
      map: { x: 34, y: 62 },
      learn: { href: "/learn/healthcare-directives/healthcare-power-of-attorney", label: "Healthcare power of attorney" },
    },
    {
      id: "hipaa",
      name: "HIPAA release",
      short: "HIPAA release",
      family: "signed",
      icon: "Lock",
      what: "A signed form that lets doctors and hospitals share medical information with the people the adult names. It gives information, not decision power.",
      bestFor: ["Parents of a new 18-year-old who still go to doctor visits", "Family who need to stay informed but not decide"],
      watchOut: ["Gives no power to make decisions", "Some providers want their own form, so sign theirs too"],
      cells: {
        rights: { level: 3, text: "Keeps every right" },
        money: { level: 0, text: "No" },
        care: { level: 1, text: "Information only" },
        nocap: { level: 0, text: "No, must sign" },
        court: { level: 0, text: "None" },
        effort: { level: 0, text: "Very low, one form" },
      },
      map: { x: 8, y: 8 },
      learn: { href: "/learn/healthcare-directives/hipaa-authorization", label: "HIPAA authorizations explained" },
    },
    {
      id: "payee",
      name: "Representative payee",
      short: "Rep payee",
      family: "money",
      icon: "Receipt",
      what: "A person the Social Security Administration appoints to receive and manage someone's Social Security or SSI payments for their needs.",
      bestFor: ["A young adult on SSI who cannot manage the monthly check", "A parent with dementia whose main income is Social Security"],
      watchOut: ["Covers only Social Security and SSI payments", "The payee must keep the money separate and keep records"],
      cells: {
        rights: { level: 3, text: "Keeps other rights" },
        money: { level: 1, text: "Social Security only" },
        care: { level: 0, text: "No" },
        nocap: { level: 3, text: "Yes" },
        court: { level: 0, text: "No, Social Security appoints" },
        effort: { level: 1, text: "Low, agency forms" },
      },
      map: { x: 40, y: 18 },
    },
    {
      id: "sntable",
      name: "Special needs trust or ABLE account",
      short: "SNT or ABLE",
      family: "money",
      icon: "PiggyBank",
      what: "Ways to hold savings or an inheritance for a person with a disability without losing SSI or Medicaid. A trustee runs the trust. In Illinois, ABLE accounts are offered through the Illinois ABLE program.",
      bestFor: ["An adult on SSI or Medicaid who will receive money from family", "Saving for a young adult's needs without a court managing it"],
      watchOut: [`Total ABLE deposits from everyone are capped at ${ABLE_LIMIT} a year`, "A trust needs a careful drafter and a trustee who follows benefit rules"],
      cells: {
        rights: { level: 3, text: "Keeps every right" },
        money: { level: 2, text: "Money placed in it" },
        care: { level: 0, text: "No" },
        nocap: { level: 2, text: "Family can set one up" },
        court: { level: 0, text: "Usually none" },
        effort: { level: 2, text: "Moderate, drafting or an account" },
      },
      map: { x: 28, y: 30 },
      learn: { href: "/learn/special-needs/able-accounts", label: "ABLE accounts explained" },
    },
    {
      id: "limited",
      name: "Limited guardianship",
      short: "Limited",
      family: "limited",
      icon: "Scale",
      what: "A court appoints a guardian with power only in the areas where the adult needs it, such as medical consent or a bank account. The adult keeps every other right.",
      bestFor: ["An adult who handles daily life but cannot make some major decisions", "A young adult who needs help with medical or money choices only"],
      watchOut: ["Still a court case, with fees, a hearing and yearly reports", "The order must list each power clearly, or third parties may balk"],
      cells: {
        rights: { level: 2, text: "Keeps rights outside the order" },
        money: { level: 2, text: "If the order covers it" },
        care: { level: 2, text: "If the order covers it" },
        nocap: { level: 3, text: "Yes" },
        court: { level: 3, text: "Petition, hearing, reports" },
        effort: { level: 2, text: "Court fees and reports" },
      },
      map: { x: 62, y: 54 },
      learn: { href: "/learn/power-of-attorney/power-of-attorney-vs-guardianship", label: "Power of attorney vs guardianship" },
    },
    {
      id: "temporary",
      name: "Temporary guardianship for emergencies",
      short: "Temporary",
      family: "limited",
      icon: "Hourglass",
      what: "A short court appointment when the adult faces immediate harm and no one has authority to act. In Illinois a temporary guardian can serve for up to 60 days while the full case is heard.",
      bestFor: ["A hospital discharge with no one able to consent", "Stopping a scam or abuse that is happening now"],
      watchOut: ["It ends quickly, so a full case usually follows", "Still needs a petition and a judge"],
      cells: {
        rights: { level: 1, text: "Limited for a short time" },
        money: { level: 2, text: "As the order allows" },
        care: { level: 2, text: "As the order allows" },
        nocap: { level: 3, text: "Yes" },
        court: { level: 3, text: "Yes, fast hearing" },
        effort: { level: 2, text: "Fast, but a full case often follows" },
      },
      map: { x: 76, y: 36 },
      learn: { href: "/learn/power-of-attorney/parent-with-dementia-no-power-of-attorney", label: "A parent with dementia and no power of attorney" },
    },
    {
      id: "plenary",
      name: "Plenary (full) guardianship",
      short: "Plenary",
      family: "court",
      icon: "Gavel",
      what: "A court appoints a guardian of the person, of the estate, or both, with power over most decisions. Illinois calls this a plenary guardianship.",
      bestFor: ["An adult who cannot understand or share choices even with support", "Late-stage dementia with no powers of attorney signed"],
      watchOut: ["The adult loses most rights to decide for themselves", "Yearly reports, accountings for money, and court approval for some acts"],
      cells: {
        rights: { level: 0, text: "Loses most rights" },
        money: { level: 3, text: "If guardian of the estate" },
        care: { level: 3, text: "If guardian of the person" },
        nocap: { level: 3, text: "Yes" },
        court: { level: 3, text: "Yes, for years" },
        effort: { level: 3, text: "High, fees and yearly reports" },
      },
      map: { x: 94, y: 92 },
      learn: { href: "/learn/what-if/incapacitated-without-power-of-attorney", label: "Incapacity without a power of attorney" },
    },
  ],
  map: {
    title: "The guardianship alternatives map",
    lead: "Options on the left keep the adult in charge of their own life. Moving right, a court takes over more decisions. Higher options give the helper broader authority.",
    x: { low: "Person keeps their rights", high: "Court takes over decisions" },
    y: { low: "Narrow help", high: "Broad authority" },
  },
  questions: [
    {
      id: "who",
      prompt: "Who needs help?",
      choices: [
        { id: "teen", label: "My child with a disability, turning 18 or just past it", weights: { sdm: 2, hipaa: 1, sntable: 1, limited: 1 }, reason: "Young adults with a disability often keep more rights with less restrictive tools" },
        { id: "dementia", label: "A parent or spouse with dementia or memory loss", weights: { poa: 1, hcpoa: 1 } },
        { id: "other", label: "Another adult, such as a sibling after a brain injury", weights: { hcpoa: 1, limited: 1 } },
      ],
    },
    {
      id: "capacity",
      prompt: "Can they understand and sign a simple legal document?",
      help: "This is a lower bar than handling everything alone. A doctor or attorney can help you judge it.",
      choices: [
        { id: "yes", label: "Yes, they understand what it means", weights: { poa: 3, hcpoa: 3, hipaa: 2, sdm: 1, limited: -3, plenary: -4, temporary: -2 }, reason: "They can sign, so they can choose their own helpers without court" },
        { id: "support", label: "Yes, if someone explains it in plain terms", weights: { sdm: 4, hipaa: 2, hcpoa: 1, poa: 1, plenary: -3 }, reason: "They can decide with support, which is what supported decision-making is built for" },
        { id: "partly", label: "Some things yes, big decisions no", weights: { limited: 5, sdm: 1, payee: 1 }, reason: "They handle some decisions but not others, so help can target the gaps" },
        { id: "no", label: "No, they cannot understand or share choices", weights: { plenary: 4, limited: 2, payee: 2, sntable: 1, poa: -6, hcpoa: -6, hipaa: -4, sdm: -5 }, reason: "They cannot sign or take part in an agreement, so a court may need to appoint someone" },
      ],
    },
    {
      id: "need",
      prompt: "What do they need help with?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "info", label: "Only keeping family informed about medical care", weights: { hipaa: 6 }, reason: "You mainly need doctors to share information with family" },
        { id: "medical", label: "Medical decisions and consent", weights: { hcpoa: 5, limited: 1 }, reason: "You need someone who can consent to medical care" },
        { id: "bank", label: "Bank accounts, bills and property", weights: { poa: 5, limited: 1 }, reason: "You need someone with authority over accounts and bills" },
        { id: "ssi", label: "A Social Security or SSI check", weights: { payee: 6 }, reason: "Social Security pays benefits only to a payee it appoints" },
        { id: "savings", label: "Savings or an inheritance that could affect SSI or Medicaid", weights: { sntable: 7 }, reason: "A special needs trust or ABLE account can hold money without hurting benefits" },
        { id: "choices", label: "Understanding choices, not someone deciding for them", weights: { sdm: 5 }, reason: "They need help understanding choices, not a substitute decision-maker" },
        { id: "living", label: "Where they live, safety and daily care", weights: { limited: 2, plenary: 3 }, reason: "Housing and safety decisions may need a guardian of the person" },
      ],
    },
    {
      id: "urgency",
      prompt: "How urgent is it?",
      choices: [
        { id: "now", label: "An emergency now", detail: "A hospital discharge, a medical decision or abuse happening now", weights: { temporary: 7 }, reason: "In an emergency, a court can appoint a temporary guardian quickly" },
        { id: "soon", label: "Within the next few months", weights: { limited: 1 } },
        { id: "ahead", label: "We are planning ahead", detail: "For example, a child who is 16 or 17", weights: { sdm: 2, poa: 2, hcpoa: 2, hipaa: 1, sntable: 1, temporary: -4 }, reason: "Planning ahead is when signed documents work well" },
      ],
    },
    {
      id: "independence",
      prompt: "How much should they decide for themselves?",
      choices: [
        { id: "most", label: "As much as possible, with help where needed", weights: { sdm: 3, hipaa: 1, poa: 1, hcpoa: 1, plenary: -2 }, reason: "You want them to keep as many rights as possible" },
        { id: "some", label: "Someone should decide in one or two areas", weights: { limited: 4, payee: 1 }, reason: "Help is needed in only some areas" },
        { id: "full", label: "Someone needs to make most decisions", weights: { plenary: 5, limited: -1 }, reason: "They need someone to make most decisions for them" },
      ],
    },
    {
      id: "risk",
      prompt: "Are any of these happening?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "exploit", label: "Someone is taking advantage of them", weights: { limited: 2, plenary: 2, temporary: 2 }, reason: "A court order can cut off someone who is exploiting them" },
        { id: "refuse", label: "They refuse care they clearly need", weights: { limited: 2, plenary: 2 }, reason: "A guardian may be needed when they refuse care they need" },
        { id: "conflict", label: "Family members disagree about who should help", weights: { limited: 1, plenary: 1, sdm: 1 } },
        { id: "none", label: "None of these", weights: { sdm: 1, poa: 1, hcpoa: 1, hipaa: 1 } },
      ],
    },
  ],
  resultNote:
    "Most families combine several of these, such as a healthcare power of attorney, a HIPAA release and an ABLE account. Illinois courts are expected to consider less restrictive options first. A short consult helps you judge what the person can still sign.",
  shortcuts: [
    { when: "Your 17-year-old can understand a document with help", pick: "sdm" },
    { when: "A parent with early dementia can still sign", pick: "poa" },
    { when: "You need someone to consent to medical care", pick: "hcpoa" },
    { when: "Doctors will not tell you anything since your child turned 18", pick: "hipaa" },
    { when: "The only income to manage is an SSI or Social Security check", pick: "payee" },
    { when: "An adult on SSI or Medicaid will inherit or save money", pick: "sntable" },
    { when: "The person handles daily life but not big medical or money decisions", pick: "limited" },
    { when: "A hospital needs a decision this week and no one has authority", pick: "temporary" },
    { when: "The person cannot understand choices even with help, and nothing was signed", pick: "plenary" },
  ],
  diagrams: ["PoaHealthcareRoles", "SpecialNeedsTrust"],
  howTo: {
    name: "How to choose between guardianship and its alternatives",
    steps: [
      { name: "Start early", text: "For a child with a disability, start at 16 or 17. Benefit changes and court cases both take time, and the child's 18th birthday will not wait." },
      { name: "Judge what they can sign", text: "Ask their doctor, teachers or an attorney whether the person understands what a power of attorney or HIPAA release does. Many people can with plain words." },
      { name: "Sign what they can", text: "Have them sign a healthcare power of attorney, a HIPAA release and a power of attorney for property. Add a supported decision-making agreement if it fits." },
      { name: "Set up the money tools", text: `Apply to be a rep payee if they get SSI. Open an ABLE account, up to ${ABLE_LIMIT} a year in deposits, or set up a special needs trust for larger sums.` },
      { name: "Go to court only for the gaps", text: "If a guardian is still needed, ask for a limited order that covers only those areas. In Illinois the case is filed in the circuit court of the county where the person lives, with a recent medical report." },
      { name: "Review it over time", text: "People grow and conditions change. A guardianship can be narrowed or ended, and documents can be updated as needs shift." },
    ],
  },
  faqs: [
    { q: "Is guardianship required when my child with a disability turns 18?", a: "No. Guardianship is never automatic and never required just because of a disability. Many young adults can sign a healthcare power of attorney, a power of attorney for property and a HIPAA release. Guardianship fits when the young adult cannot understand or share choices even with support." },
    { q: "How can I avoid guardianship for my parent?", a: "Have your parent sign a durable power of attorney for property and a healthcare power of attorney while they still understand them. Add a HIPAA release, and a living trust if they own a home. Once dementia takes away the ability to sign, guardianship may be the only path." },
    { q: "What is supported decision-making?", a: "It is an arrangement in which an adult with a disability picks trusted people to help them understand information and make choices. The adult keeps the legal right to decide. Illinois has a law that recognizes written supported decision-making agreements for adults with intellectual or developmental disabilities." },
    { q: "What is the difference between full and limited guardianship?", a: "A plenary, or full, guardian has power over most decisions in the areas the court names. A limited guardian has power only where the court finds the person needs help, and the person keeps every other right. Illinois law prefers limited guardianship when it will meet the person's needs." },
    { q: "What is the difference between a guardian of the person and a guardian of the estate?", a: "A guardian of the person makes personal decisions, such as medical care and where to live. A guardian of the estate manages money and property and reports to the court. Illinois uses these two terms for adults, and one person can hold both roles." },
    { q: "What is an emergency or temporary guardianship?", a: "It is a short court appointment when an adult faces immediate harm and no one has authority to act. In Illinois a temporary guardian can serve for up to 60 days. A full hearing usually follows to decide whether a longer guardianship is needed." },
    { q: "Do parents lose access to medical information when a child turns 18?", a: "Yes. Once your child is 18, doctors generally cannot share medical details with you without your child's written permission. A signed HIPAA release fixes that. A healthcare power of attorney goes further and lets you make decisions if your child cannot." },
    { q: "Can guardianship be ended or changed later?", a: "Yes. The adult, or someone on their behalf, can ask the court to narrow or end the guardianship if their abilities improve. Keep records of progress, such as school reports and doctor notes, to support the request." },
  ],
  related: [
    { href: "/decide/guardianship-vs-conservatorship", label: "Guardianship vs conservatorship" },
    { href: "/decide/how-to-manage-a-parents-finances", label: "How to manage a parent's finances" },
    { href: "/decide/types-of-special-needs-trusts", label: "Types of special needs trusts" },
    { href: "/learn/special-needs/guardianship-alternatives-for-adult-children", label: "Turning 18 with a disability" },
    { href: "/learn/power-of-attorney/power-of-attorney-vs-guardianship", label: "Power of attorney vs guardianship" },
    { href: "/decide/types-of-advance-directives", label: "Types of advance directives" },
  ],
};
