import type { DecisionGuide } from "./types";

export const WAYS_TO_HOLD_TITLE: DecisionGuide = {
  slug: "ways-to-hold-title-to-property",
  title: "Ways to hold title to a house: 8 options compared",
  h1: "Ways to hold title to a house, and which one fits you",
  description: `Sole ownership, joint tenancy, tenancy by the entirety, a living trust, a TODI, an Illinois land trust or an LLC. Compare how each title works and find yours.`,
  kicker: "Property title decision guide",
  art: "HeroFamilyHome",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "How you hold title decides who can sell the house and who gets it when you die. In Illinois, a married couple living in their home usually picks tenancy by the entirety, which adds protection from one spouse's debts. A single owner can skip probate with a transfer on death instrument or a living trust. Co-owners who want their shares to go to their own families use tenants in common.",
  takeaways: [
    "The words on your deed control what happens at death. A will cannot override joint tenancy or a recorded transfer on death instrument.",
    "Joint tenancy and tenancy by the entirety skip probate only at the first death. The last owner still needs a plan.",
    "In Illinois, tenancy by the entirety is only for a married couple's main home, and it shields the house from one spouse's own debts.",
    "An Illinois land trust keeps your name off the public record, but it skips probate only if the trust agreement names who gets it at death.",
    "Putting a home in an LLC rarely helps a family. It is a tool for rentals, and it can cost you your homestead tax break.",
  ],
  noun: "way to hold title",
  families: [
    { id: "deed", name: "Titles written on the deed", text: "One or more people own the house directly. The deed's wording sets the rules for selling and for death.", tone: "accent" },
    { id: "death", name: "Tools that pass it at death", text: "You keep full ownership now, and the house goes to the people you named without probate.", tone: "sage" },
    { id: "entity", name: "A trust or company holds title", text: "A trustee or an LLC is the owner on paper. You keep control through the agreement.", tone: "gold" },
  ],
  dimensions: [
    { id: "probate", label: "Avoids probate", help: "Does the house pass at death without an Illinois probate case?" },
    { id: "survivor", label: "Co-owner takes it automatically", help: "Does a surviving co-owner get the house with no court and no will?" },
    { id: "creditors", label: "Protection from debts and lawsuits", help: "Can an owner's creditors or a lawsuit reach the house?" },
    { id: "control", label: "You can sell alone", help: "Can you sell, refinance or change the plan without anyone else signing?" },
    { id: "privacy", label: "Privacy", help: "Does your name stay off the public land records?" },
    { id: "basis", label: "Step-up in basis at death", help: "Do heirs get the home's value at death as their tax basis?" },
    { id: "effort", label: "Setup cost and upkeep", help: "Relative cost and paperwork. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "sole",
      name: "Sole ownership",
      short: "Sole owner",
      family: "deed",
      icon: "UserCheck",
      what: "You are the only owner on the deed. You can sell or mortgage the house on your own, and at your death it passes by your will or by state law.",
      bestFor: ["A single person who has not yet made an estate plan", "A spouse who owned the house before marriage and wants it kept separate"],
      watchOut: ["In Illinois, a house in your sole name usually means a probate case, because the small estate affidavit does not cover real estate", "If you become unable to manage, someone needs a power of attorney or a court order to sell"],
      cells: {
        probate: { level: 0, text: "No, goes through probate" },
        survivor: { level: 0, text: "No co-owner" },
        creditors: { level: 0, text: "Your creditors can reach it" },
        control: { level: 3, text: "Full, no one else signs" },
        privacy: { level: 0, text: "Your name on the deed" },
        basis: { level: 3, text: "Full step-up" },
        effort: { level: 0, text: "Lowest, nothing extra" },
      },
      map: { x: 6, y: 10 },
      learn: { href: "/learn/probate/what-is-probate", label: "What probate is and how it works" },
    },
    {
      id: "tic",
      name: "Tenants in common",
      short: "Tenants in common",
      family: "deed",
      icon: "Split",
      what: "Two or more people each own a share of the house, equal or not. When one owner dies, that share goes to their own heirs, not to the other owners.",
      bestFor: ["Siblings or friends who buy together and want their shares to go to their own families", "Unequal investors, such as one paying 70% and the other 30%", "Spouses in a second marriage who each have children"],
      watchOut: ["Each owner's share goes through probate unless it is held in a trust", "Any owner can ask a court to force a sale, and you may end up co-owning with someone's heirs"],
      cells: {
        probate: { level: 0, text: "No, each share goes through probate" },
        survivor: { level: 0, text: "No, share goes to the owner's heirs" },
        creditors: { level: 0, text: "Each owner's creditors can reach their share" },
        control: { level: 1, text: "Your share only" },
        privacy: { level: 0, text: "Names on the deed" },
        basis: { level: 3, text: "Full step-up on the share that passes" },
        effort: { level: 0, text: "Low, plus a co-owner agreement" },
      },
      map: { x: 20, y: 32 },
      learn: { href: "/learn/property-and-assets/heirs-property", label: "Heirs property and shared ownership" },
    },
    {
      id: "joint",
      name: "Joint tenancy with right of survivorship",
      short: "Joint tenancy",
      family: "deed",
      icon: "Users",
      what: "Two or more people own the whole house together. When one dies, the others own it automatically, without probate and no matter what the will says.",
      bestFor: ["Unmarried partners who want the survivor to keep the home", "A married couple buying a rental or a second home", "Co-owners who truly want the last one standing to own it all"],
      watchOut: ["Probate is only put off until the last owner dies", "Adding a child as a joint tenant exposes the house to the child's debts and can cost the child a tax break"],
      cells: {
        probate: { level: 2, text: "Until the last owner dies" },
        survivor: { level: 3, text: "Yes, automatically" },
        creditors: { level: 0, text: "Each owner's creditors can reach it" },
        control: { level: 1, text: "All owners sign to sell" },
        privacy: { level: 0, text: "Names on the deed" },
        basis: { level: 2, text: "Partial, on the owner who died" },
        effort: { level: 0, text: "Low, deed wording only" },
      },
      map: { x: 34, y: 12 },
      learn: { href: "/learn/property-and-assets/joint-tenancy-risks", label: "The hidden risks of joint ownership" },
    },
    {
      id: "tbe",
      name: "Tenancy by the entirety",
      short: "By the entirety",
      family: "deed",
      icon: "HeartHandshake",
      what: "A form of joint ownership only for a married couple. In Illinois it is allowed only for the couple's homestead, the home they live in, and it keeps one spouse's own creditors from forcing a sale.",
      bestFor: ["A married couple who live in the home they own", "A couple where one spouse runs a business, practices a profession or carries personal debt"],
      watchOut: ["Only for the principal home in Illinois, not a rental or vacation house", "No protection from debts both spouses owe together, and protection ends if you divorce or move out"],
      cells: {
        probate: { level: 2, text: "Until the second spouse dies" },
        survivor: { level: 3, text: "Yes, to the surviving spouse" },
        creditors: { level: 2, text: "Shielded from one spouse's own debts" },
        control: { level: 0, text: "Both spouses must sign" },
        privacy: { level: 0, text: "Names on the deed" },
        basis: { level: 2, text: "Half step-up at the first death" },
        effort: { level: 0, text: "Low, deed wording only" },
      },
      map: { x: 30, y: 72 },
      learn: { href: "/glossary/tenancy-by-the-entirety", label: "Tenancy by the entirety defined" },
    },
    {
      id: "todi",
      name: "Transfer on death instrument (TODI)",
      short: "TODI",
      family: "death",
      icon: "FileSignature",
      what: "Illinois's version of a transfer-on-death deed. You stay the full owner and record a document that names who gets the house when you die.",
      bestFor: ["A single owner who wants the house to skip probate at low cost", "The surviving spouse, after a joint tenancy owner dies", "Adult heirs who get along and can share or sell"],
      watchOut: ["It must be signed with the required formalities and recorded with the county before you die", "No help if you become incapacitated, and no way to hold a young heir's share in trust"],
      cells: {
        probate: { level: 3, text: "Yes, if recorded before death" },
        survivor: { level: 1, text: "Names heirs, not a co-owner" },
        creditors: { level: 0, text: "Your creditors can reach it" },
        control: { level: 3, text: "Full, can revoke" },
        privacy: { level: 0, text: "Recorded in public records" },
        basis: { level: 3, text: "Full step-up" },
        effort: { level: 1, text: "Low, one recorded form" },
      },
      map: { x: 50, y: 8 },
      learn: { href: "/learn/beneficiary-designations/transfer-on-death-deed", label: "Transfer-on-death deeds explained" },
    },
    {
      id: "trust",
      name: "Revocable living trust",
      short: "Living trust",
      family: "death",
      icon: "House",
      what: "You deed the house to a trust you control. If you cannot manage, or when you die, your successor trustee takes over and follows your written terms.",
      bestFor: ["Parents of minor children or a child who needs protection", "Owners of homes in more than one state", "Anyone who wants one plan for incapacity and death"],
      watchOut: ["It only works if you sign and record a new deed into the trust", "No protection from your own creditors or lawsuits"],
      cells: {
        probate: { level: 3, text: "Yes, once deeded to it" },
        survivor: { level: 2, text: "Yes, through a joint trust" },
        creditors: { level: 0, text: "No, still yours" },
        control: { level: 3, text: "Full, as trustee" },
        privacy: { level: 2, text: "Trust name on deed, terms private" },
        basis: { level: 3, text: "Full step-up" },
        effort: { level: 2, text: "Moderate, plus a new deed" },
      },
      map: { x: 66, y: 18 },
      learn: { href: "/learn/trusts/transfer-house-to-living-trust", label: "Moving your house into a living trust" },
    },
    {
      id: "landtrust",
      name: "Illinois land trust",
      short: "Land trust",
      family: "entity",
      icon: "KeyRound",
      what: "A bank or trust company holds title as trustee, and you hold the beneficial interest and direct every decision. The public record shows a trust number, not your name.",
      bestFor: ["Owners who want their name off the land records, such as landlords or people in public roles", "Investors who want to transfer an interest without recording a new deed"],
      watchOut: ["It does not avoid probate by itself. The beneficial interest must name who takes it at your death", "It hides the owner but does not stop a lawsuit, and the trustee charges fees each year"],
      cells: {
        probate: { level: 2, text: "Only if a death beneficiary is named" },
        survivor: { level: 2, text: "If the agreement says so" },
        creditors: { level: 1, text: "Hidden, not shielded" },
        control: { level: 3, text: "You direct the trustee" },
        privacy: { level: 3, text: "Name off the public record" },
        basis: { level: 3, text: "Full step-up" },
        effort: { level: 2, text: "Trustee fees each year" },
      },
      map: { x: 82, y: 34 },
    },
    {
      id: "llc",
      name: "LLC",
      short: "LLC",
      family: "entity",
      icon: "Building2",
      what: "A limited liability company owns the property and you own the company. It is mainly a way to keep a rental's lawsuits away from your other savings.",
      bestFor: ["Rental or investment property", "Co-investors who want written rules on money, management and buyouts"],
      watchOut: ["For a home you live in, you may lose the homeowner property tax exemption and need lender consent", "Your LLC interest still goes through probate unless a trust owns it or the operating agreement passes it"],
      cells: {
        probate: { level: 1, text: "Only with a trust or plan for the interest" },
        survivor: { level: 1, text: "Only if the agreement says so" },
        creditors: { level: 3, text: "Separates property claims from you" },
        control: { level: 3, text: "You manage the company" },
        privacy: { level: 1, text: "LLC name on deed, state filing lists people" },
        basis: { level: 2, text: "Usually, some tax filings" },
        effort: { level: 3, text: "Filing fees and yearly reports" },
      },
      map: { x: 92, y: 86 },
      learn: { href: "/learn/business-owners/llc-ownership-at-death", label: "What happens to your LLC when you die" },
    },
  ],
  map: {
    title: "The property title map",
    lead: "Options on the left put people's names straight on the deed. Moving right, a trust or company holds title for you. Options higher up do more to keep creditors and lawsuits away from the property.",
    x: { low: "Your name on the deed", high: "A trust or company holds title" },
    y: { low: "Little protection from creditors", high: "More protection from creditors" },
  },
  questions: [
    {
      id: "owners",
      prompt: "Who owns the property, or will own it, with you?",
      choices: [
        { id: "alone", label: "Just me", weights: { sole: 2, todi: 3, trust: 2, landtrust: 1, tic: -2, joint: -2, tbe: -3 }, reason: "You own it alone, so a death plan matters more than co-owner rules" },
        { id: "spouse", label: "My spouse", weights: { tbe: 3, joint: 2, trust: 2, tic: -1 }, reason: "You own it with your spouse" },
        { id: "partner", label: "An unmarried partner", weights: { joint: 3, tic: 1, trust: 1, tbe: -3 }, reason: "You want your partner to keep the home if you die first" },
        { id: "others", label: "Siblings, friends or co-investors", weights: { tic: 3, llc: 2, landtrust: 1, tbe: -3 }, reason: "Each co-owner will want their share to go to their own family" },
      ],
    },
    {
      id: "use",
      prompt: "How is the property used?",
      choices: [
        { id: "home", label: "It is the home I live in", weights: { tbe: 2, trust: 1, todi: 1, llc: -3 }, reason: "It is your main home" },
        { id: "rental", label: "It is a rental or investment", weights: { llc: 4, landtrust: 2, tbe: -3 }, reason: "You rent it out, and tenants can sue" },
        { id: "second", label: "A vacation home or land", weights: { trust: 2, joint: 1, tic: 1, tbe: -3 }, reason: "A second property is a common reason for a trust" },
      ],
    },
    {
      id: "death",
      prompt: "What should happen to your part when you die?",
      choices: [
        { id: "partner", label: "My co-owner should get it automatically", weights: { joint: 3, tbe: 3, tic: -3 }, reason: "You want your co-owner to own it all when you die" },
        { id: "family", label: "It should go to my own children or family", weights: { tic: 3, trust: 2, todi: 2, joint: -2, tbe: -1 }, reason: "You want your share to go to your own family, not a co-owner" },
        { id: "rules", label: "It should be held with rules, such as for a young child", weights: { trust: 5, landtrust: 1, todi: -2 }, reason: "You need someone to hold the property on your terms after you die" },
        { id: "unsure", label: "I am fine with probate deciding it", weights: { sole: 4, tic: 1, todi: -1, trust: -1 }, reason: "You are comfortable letting your will and probate handle it" },
      ],
    },
    {
      id: "risk",
      prompt: "Which of these worry you?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "spouse-debt", label: "One spouse has business debts or a risky job", weights: { tbe: 4, llc: 1 }, reason: "Tenancy by the entirety keeps one spouse's own creditors from forcing a sale of your home" },
        { id: "tenant", label: "A tenant or visitor could sue", weights: { llc: 4, landtrust: 1 }, reason: "An LLC can keep a property lawsuit away from your other savings" },
        { id: "privacy", label: "I want my name off the public records", weights: { landtrust: 5, trust: 1, llc: 1 }, reason: "You want privacy, and an Illinois land trust keeps your name off the deed" },
        { id: "incapacity", label: "Who manages it if I cannot", weights: { trust: 3, landtrust: 1 }, reason: "You want someone ready to manage the property if you cannot" },
        { id: "none", label: "None of these", weights: { sole: 1, todi: 1, joint: 1, tic: 1 } },
      ],
    },
    {
      id: "control",
      prompt: "Do you want to sell or change your mind without anyone else signing?",
      choices: [
        { id: "alone", label: "Yes, I want full control", weights: { sole: 2, todi: 2, trust: 2, landtrust: 1, tbe: -1, joint: -1 }, reason: "You want to be able to sell or change the plan on your own" },
        { id: "shared", label: "No, we decide together", weights: { tbe: 2, joint: 2, tic: 1 }, reason: "You are fine with all owners signing to sell" },
      ],
    },
    {
      id: "effort",
      prompt: "How much setup and upkeep are you willing to take on?",
      choices: [
        { id: "low", label: "As little as possible", weights: { sole: 2, todi: 2, joint: 1, tbe: 1, tic: 1, llc: -2, landtrust: -1 }, reason: "You want a simple setup with no yearly upkeep" },
        { id: "some", label: "Some legal fees now are fine", weights: { trust: 2, todi: 1 }, reason: "You are willing to pay once for a fuller plan" },
        { id: "ongoing", label: "Yearly fees and filings are fine", weights: { llc: 2, landtrust: 2 }, reason: "You accept yearly fees for protection or privacy" },
      ],
    },
  ],
  resultNote: "You can combine these. A couple can hold their home by the entirety inside their living trusts, and an LLC can be owned by your trust. An Illinois attorney can check the deed wording before you record anything.",
  shortcuts: [
    { when: "You are married, you live in the house, and one of you has business or personal debt risk", pick: "tbe" },
    { when: "You own your home alone and just want it to skip probate", pick: "todi" },
    { when: "You have minor children, a child who needs protection or property in another state", pick: "trust" },
    { when: "You and a sibling or friend buy together and each want your share to go to your own family", pick: "tic" },
    { when: "You are unmarried partners and want the survivor to keep the home", pick: "joint" },
    { when: "You own a rental and worry about a tenant's lawsuit", pick: "llc" },
    { when: "You want your name off the Illinois land records", pick: "landtrust" },
  ],
  diagrams: ["TodPodTransfers", "TrustFundingAssets"],
  howTo: {
    name: "How to choose a way to hold title to your house",
    steps: [
      { name: "Read your current deed", text: "Get a copy from the county recorder. Look for words like \"joint tenants\", \"tenants in common\" or \"tenants by the entirety\". In Illinois, co-owners who are not described as joint tenants or tenants by the entirety are usually tenants in common." },
      { name: "Decide what should happen at each death", text: "Write down who should get the house if you die first, and who should get it after the last owner dies. Title only answers the first question for joint tenants." },
      { name: "Check your mortgage, insurance and tax exemptions", text: "Ask your lender before deeding the house to an LLC or land trust. Tell your insurer about any new owner, and confirm you keep the homeowner exemption on your property tax bill." },
      { name: "Weigh creditor and lawsuit risks", text: "Married homeowners with debt risk can look at tenancy by the entirety. Landlords should price an umbrella policy and compare it with an LLC." },
      { name: "Sign and record the new deed", text: "Have the deed prepared with the exact wording you want, signed and notarized, then recorded with the county recorder where the house sits." },
      { name: "Line up your will and trust", text: "Make sure your will, trust and any TODI agree with the deed. A deed beats a will, so a mismatch can send the house to the wrong person." },
    ],
  },
  faqs: [
    { q: "What is the difference between joint tenancy and tenants in common?", a: "Joint tenants own the whole house together, and when one dies the others take it automatically without probate. Tenants in common each own a separate share, and a share passes to that owner's heirs through their will or probate. In Illinois, the deed must clearly say joint tenancy, or co-owners are usually treated as tenants in common." },
    { q: "How should a married couple hold title to a home in Illinois?", a: "Many Illinois couples use tenancy by the entirety for the home they live in. The survivor gets the house without probate, and one spouse's own creditors cannot force a sale. If you also want to plan for after the second death or for incapacity, a living trust can hold the home, and Illinois law can let you keep the entirety protection inside your trusts if the deed is drafted for it." },
    { q: "Is Illinois a community property state?", a: "No. Illinois is a common law property state, so community property is not one of the ways to hold title here. States like California, Texas and Arizona use community property, which can give a surviving spouse a full step-up in basis on the whole house. If you moved from one of those states, ask whether any property you brought keeps that status." },
    { q: "Does joint tenancy avoid probate?", a: "Yes, but only at the first death. The surviving owner takes the house without probate. When the last owner dies, the house is in their sole name and will need probate in Illinois unless they add a TODI or move it into a trust." },
    { q: "Does an Illinois land trust avoid probate?", a: "Not on its own. The land trust holds title, but your beneficial interest still belongs to you and can go through probate at your death. It skips probate if the trust agreement names a contingent beneficiary or if your living trust holds the beneficial interest." },
    { q: "Should I put my house in an LLC?", a: "Usually not for a home you live in. An LLC is built for rentals, where it can keep tenant lawsuits away from your other savings. For a home, it can cost you the homeowner property tax exemption, complicate your mortgage and title insurance, and add yearly filings, without skipping probate." },
    { q: "Do jointly owned houses get a step-up in basis?", a: "Partly. When spouses own a home as joint tenants or by the entirety, half the house usually gets a new tax basis at the first death. For co-owners who are not married, the IRS looks at how much each paid toward the house. A house left in a trust or by a TODI gets a full step-up at the owner's death." },
    { q: "What happens if I own a house with a sibling and one of us dies?", a: "It depends on the deed. If you are joint tenants, the surviving sibling owns the whole house. If you are tenants in common, the share of the sibling who died goes to their heirs, and you become co-owners with them." },
  ],
  related: [
    { href: "/learn/property-and-assets/joint-tenancy-risks", label: "The hidden risks of joint ownership" },
    { href: "/estate-planning/illinois", label: "Estate planning in Illinois" },
    { href: "/decide/how-to-leave-your-house-to-your-children", label: "How to leave your house to your children" },
    { href: "/decide/ways-to-avoid-probate", label: "Ways to avoid probate compared" },
    { href: "/decide/llc-vs-trust-for-rental-property", label: "LLC vs trust for rental property" },
    { href: "/decide/estate-planning-for-second-marriages", label: "Estate planning for second marriages" },
  ],
};
