import { FIGURES, usdFigure, usdMillions } from "@/config/figures";
import type { DecisionGuide } from "./types";

const EXEMPTION = usdMillions(FIGURES.federalExemption);
const GIFT_EXCLUSION = usdFigure(FIGURES.annualGiftExclusion);
const LOOKBACK_YEARS = FIGURES.medicaidLookbackMonths / 12;

export const HOUSE_TO_CHILDREN: DecisionGuide = {
  slug: "how-to-leave-your-house-to-your-children",
  title: "How to leave your house to your children: 6 ways compared",
  h1: "How to leave your house to your children",
  description: `Six ways to pass your home to your children compared: living trust, TOD deed, lady bird deed, life estate, gift or will. Answer six questions to see which fits.`,
  kicker: "Family home decision guide",
  art: "HeroFamilyHome",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "For most parents, a revocable living trust or a transfer-on-death deed is the best way to leave a house to children. Both skip probate, let you keep control, and give your children a step-up in basis. A will works but needs probate. Putting a child on the deed now is usually the costliest choice, because the child takes your old tax basis.",
  takeaways: [
    "Inheriting is usually better than a gift for taxes. Heirs get a step-up in basis, while a gift passes on your old basis.",
    "A living trust and a transfer-on-death deed both skip probate and let you keep full control while you live.",
    "Adding a child to your deed now exposes the house to their debts and divorce, and you need their signature to sell.",
    "Deeds that help with Medicaid, such as life estate and lady bird deeds, depend heavily on your state's rules.",
    "Plan for siblings early. Write down who may live there, how a buyout works and when the house is sold.",
  ],
  noun: "way to leave your house",
  families: [
    { id: "keep", name: "Keep control, skip probate", text: "The house stays yours until you die, then passes without a court case.", tone: "accent" },
    { id: "give", name: "Give it away now", text: "Your children own all or part of the house today. This can help with Medicaid but costs control and tax basis.", tone: "clay" },
    { id: "court", name: "Pass it through probate", text: "Your will names who gets the house, and the probate court oversees the transfer.", tone: "gold" },
  ],
  dimensions: [
    { id: "probate", label: "Avoids probate", help: "Does the house pass without a court process?" },
    { id: "control", label: "You keep control", help: "Can you sell, refinance or change your mind without asking anyone?" },
    { id: "basis", label: "Step-up in basis", help: "Do your children get the home's value at your death as their tax basis?" },
    { id: "medicaid", label: "Helps with Medicaid", help: "Can it keep the house from counting for nursing home Medicaid? Rules vary by state." },
    { id: "childrisk", label: "Safe from a child's problems", help: "Protection from a child's debts, divorce or poor money habits." },
    { id: "incapacity", label: "Covers incapacity", help: "Is someone ready to manage the house if you cannot?" },
    { id: "effort", label: "Setup cost and effort", help: "Relative cost and paperwork, now and at death. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "trust",
      name: "Revocable living trust",
      short: "Living trust",
      family: "keep",
      icon: "House",
      what: "You deed the house to a trust you control. At your death, your successor trustee passes it to your children on the terms you wrote.",
      bestFor: ["Parents of minor children or a child who needs protection", "Owners of property in more than one state", "Anyone who wants rules for a sale, buyout or who lives there"],
      watchOut: ["Only works if you actually deed the house into the trust", "No Medicaid protection, since the house still counts as yours"],
      cells: {
        probate: { level: 3, text: "Yes, once deeded to it" },
        control: { level: 3, text: "Full, change any time" },
        basis: { level: 3, text: "Yes, full step-up" },
        medicaid: { level: 0, text: "No, counted as yours" },
        childrisk: { level: 3, text: "Yes, can hold shares in trust" },
        incapacity: { level: 3, text: "Yes, successor trustee" },
        effort: { level: 2, text: "Moderate, plus a new deed" },
      },
      map: { x: 24, y: 16 },
      learn: { href: "/learn/trusts/transfer-house-to-living-trust", label: "Moving your house into a living trust" },
    },
    {
      id: "tod",
      name: "Transfer-on-death deed",
      short: "TOD deed",
      family: "keep",
      icon: "FileSignature",
      what: "A recorded deed that names who gets the house when you die. You stay the full owner until then and can revoke it.",
      bestFor: ["A home going to adult children who get along", "Owners whose other accounts already name beneficiaries", "People who want a low-cost way to skip probate"],
      watchOut: ["Not every state allows it, and signing rules differ", "No help if you become incapacitated, and no way to hold a share in trust"],
      cells: {
        probate: { level: 3, text: "Yes, where allowed" },
        control: { level: 3, text: "Full, can revoke" },
        basis: { level: 3, text: "Yes, full step-up" },
        medicaid: { level: 0, text: "No, may face recovery" },
        childrisk: { level: 1, text: "Only until your death" },
        incapacity: { level: 0, text: "No" },
        effort: { level: 1, text: "Low, one recorded deed" },
      },
      map: { x: 40, y: 12 },
      learn: { href: "/learn/beneficiary-designations/transfer-on-death-deed", label: "Transfer-on-death deeds explained" },
    },
    {
      id: "ladybird",
      name: "Lady bird deed",
      short: "Lady bird",
      family: "keep",
      icon: "Heart",
      what: "An enhanced life estate deed, used in only a few states. You keep the right to live in, sell or mortgage the house, and it passes to your children at death.",
      bestFor: ["Homeowners in a state that recognizes this deed", "Older owners who want to keep control and plan for possible Medicaid"],
      watchOut: ["Only a few states recognize it, so check your state first", "Medicaid and estate recovery treatment varies by state"],
      cells: {
        probate: { level: 3, text: "Yes, where allowed" },
        control: { level: 3, text: "Full, can sell or revoke" },
        basis: { level: 3, text: "Yes, full step-up" },
        medicaid: { level: 2, text: "Often helps, varies by state" },
        childrisk: { level: 1, text: "Only until your death" },
        incapacity: { level: 0, text: "No" },
        effort: { level: 1, text: "Low, a few states only" },
      },
      map: { x: 22, y: 56 },
    },
    {
      id: "lifeestate",
      name: "Traditional life estate deed",
      short: "Life estate",
      family: "give",
      icon: "Hourglass",
      what: "You deed the house to your children now but keep the right to live there for life. At your death, it is fully theirs without probate.",
      bestFor: ["Healthy owners who want to protect the house from nursing home costs years ahead", "Parents ready to give up the right to sell on their own"],
      watchOut: [`It is a gift for the ${LOOKBACK_YEARS}-year Medicaid look-back`, "Hard to undo, and your children must sign to sell or refinance"],
      cells: {
        probate: { level: 3, text: "Yes" },
        control: { level: 1, text: "Children must sign to sell" },
        basis: { level: 2, text: "At death, not if sold early" },
        medicaid: { level: 2, text: "Yes, after the look-back" },
        childrisk: { level: 0, text: "No, they own a share now" },
        incapacity: { level: 0, text: "No" },
        effort: { level: 1, text: "Low, but hard to undo" },
      },
      map: { x: 66, y: 78 },
      learn: { href: "/learn/elder-care/protecting-your-home-from-nursing-home-costs", label: "Protecting your home from nursing home costs" },
    },
    {
      id: "gift",
      name: "Add a child to the deed or gift it now",
      short: "Gift now",
      family: "give",
      icon: "Gift",
      what: "You make a child a joint owner today, or deed the whole house to them. The gifted part belongs to the child right away.",
      bestFor: ["Owners who truly want the child to own the house now", "Families who have weighed the tax cost with an adviser"],
      watchOut: ["The child takes your old tax basis on the gifted part, which can mean a large capital gains bill", "The child's creditors, divorce or lawsuit can reach the house"],
      cells: {
        probate: { level: 2, text: "Yes, if the child outlives you" },
        control: { level: 0, text: "No, child must sign" },
        basis: { level: 0, text: "No, child takes your basis" },
        medicaid: { level: 1, text: `Penalty for ${LOOKBACK_YEARS} years` },
        childrisk: { level: 0, text: "No, exposed now" },
        incapacity: { level: 0, text: "No" },
        effort: { level: 1, text: "Low, hidden costs later" },
      },
      map: { x: 86, y: 40 },
      learn: { href: "/learn/probate/adding-a-child-to-your-deed", label: "Adding a child to your deed: the risks" },
    },
    {
      id: "will",
      name: "Leave it in your will",
      short: "Will",
      family: "court",
      icon: "ScrollText",
      what: "Your will names who gets the house. Your executor takes it through probate, and the court approves the transfer to your children.",
      bestFor: ["Owners in states where probate is quick and affordable", "People who want a simple, low-cost plan today"],
      watchOut: ["Probate can take months, costs money and is public", "Does nothing if you become incapacitated"],
      cells: {
        probate: { level: 0, text: "No, goes through probate" },
        control: { level: 3, text: "Full, change any time" },
        basis: { level: 3, text: "Yes, full step-up" },
        medicaid: { level: 0, text: "No, open to recovery" },
        childrisk: { level: 1, text: "Only with a trust in it" },
        incapacity: { level: 0, text: "No" },
        effort: { level: 2, text: "Low now, probate later" },
      },
      map: { x: 8, y: 12 },
      learn: { href: "/learn/probate/what-is-probate", label: "What probate is and how it works" },
    },
  ],
  map: {
    title: "The family home map",
    lead: "Options on the left keep the house in your name until you die. Moving right, you hand over ownership now. Options higher up do more to protect the house from nursing home costs.",
    x: { low: "You keep ownership", high: "Children own it now" },
    y: { low: "Little Medicaid protection", high: "More Medicaid protection" },
  },
  questions: [
    {
      id: "care",
      prompt: "Could you need nursing home care paid by Medicaid?",
      help: `Medicaid looks back ${LOOKBACK_YEARS} years at gifts in most states. California differs.`,
      choices: [
        { id: "soon", label: `Yes, possibly within ${LOOKBACK_YEARS} years`, weights: { ladybird: 3, lifeestate: 1, gift: -2 }, reason: "Care may be needed soon, so a gift now could delay Medicaid coverage" },
        { id: "later", label: `Possibly, but probably more than ${LOOKBACK_YEARS} years away`, weights: { lifeestate: 4, ladybird: 2, gift: 1 }, reason: "You may need care later, and there is time for the look-back to pass" },
        { id: "no", label: "Unlikely", weights: { trust: 1, tod: 1, lifeestate: -2, gift: -1 } },
      ],
    },
    {
      id: "control",
      prompt: "Do you want to keep the right to sell, refinance or change your mind?",
      choices: [
        { id: "keep", label: "Yes, I want full control", weights: { trust: 3, tod: 3, ladybird: 3, will: 2, lifeestate: -2, gift: -3 }, reason: "You want to keep full control of the house" },
        { id: "handover", label: "No, I am ready to hand it over now", weights: { lifeestate: 3, gift: 2 }, reason: "You are ready to give your children ownership now" },
      ],
    },
    {
      id: "children",
      prompt: "Which of these describe your children?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "adults", label: "Adults who get along", weights: { tod: 3, ladybird: 2 }, reason: "Your children are adults who can share the house simply" },
        { id: "minor", label: "A child is under 18", weights: { trust: 4, will: 2, tod: -2, ladybird: -1, gift: -3 }, reason: "A minor cannot manage a house, so a trustee should hold it" },
        { id: "risk", label: "A child has debts, divorce risk or money troubles", weights: { trust: 4, gift: -3, lifeestate: -2 }, reason: "A trust can keep a child's share away from creditors or a divorce" },
        { id: "disability", label: "A child has a disability or gets SSI or Medicaid", weights: { trust: 5, will: 1 }, reason: "Owning a house directly could affect a child's benefits" },
        { id: "disagree", label: "Several children who may not agree on the house", weights: { trust: 3, will: 1 }, reason: "A trust can set rules for a sale or a buyout" },
        { id: "lives", label: "A child lives there or will want to", weights: { trust: 2, lifeestate: 1 }, reason: "A trust can let one child live there on clear terms" },
      ],
    },
    {
      id: "rest",
      prompt: "What else should your plan cover?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "other", label: "Other property or accounts with no beneficiary", detail: "Including real estate in another state.", weights: { trust: 4, tod: -1 }, reason: "A trust can keep all your assets out of probate in one plan" },
        { id: "incapacity", label: "Someone to manage the house if I cannot", weights: { trust: 3 }, reason: "You want someone ready to manage the house if you cannot" },
        { id: "covered", label: "Nothing. My accounts already name beneficiaries", weights: { tod: 2, ladybird: 2 }, reason: "Your other assets already skip probate, so the house is the main gap" },
      ],
    },
    {
      id: "probate",
      prompt: "How much does skipping probate matter to you?",
      choices: [
        { id: "yes", label: "A lot. I want the house to skip probate", weights: { trust: 2, tod: 2, ladybird: 2, lifeestate: 1, gift: 1, will: -3 }, reason: "You want the house to pass without probate" },
        { id: "no", label: "Not much. Probate is fine with me", weights: { will: 5, trust: -1, tod: -1, ladybird: -1 }, reason: "You are comfortable with probate, so a will can do the job" },
      ],
    },
    {
      id: "cost",
      prompt: "What matters most about cost?",
      choices: [
        { id: "now", label: "Lowest cost today", weights: { tod: 2, ladybird: 2, will: 2, lifeestate: 1, gift: 1 }, reason: "You want the lowest cost today" },
        { id: "total", label: "Lowest total cost, counting probate later", weights: { trust: 2, tod: 2, ladybird: 2, will: -2 }, reason: "You want to avoid probate costs later" },
        { id: "flex", label: "Flexibility is worth paying for", weights: { trust: 3 }, reason: "You value detailed instructions and flexibility" },
      ],
    },
  ],
  resultNote: "Deed options and Medicaid rules differ a lot from state to state. A short consult confirms which options your state allows and how each affects taxes and long-term care.",
  shortcuts: [
    { when: "Your home is your main asset, your children are adults and your state allows TOD deeds", pick: "tod" },
    { when: "A child is under 18, has a disability or struggles with money", pick: "trust" },
    { when: "You own real estate in more than one state", pick: "trust" },
    { when: "Your state recognizes lady bird deeds and long-term care is a concern", pick: "ladybird" },
    { when: `You are healthy, care may be needed more than ${LOOKBACK_YEARS} years out, and you can give up control`, pick: "lifeestate" },
    { when: "You are thinking of putting a child on your deed to skip probate", pick: "tod" },
    { when: "Probate is quick in your state and you want the lowest cost today", pick: "will" },
  ],
  diagrams: ["TodPodTransfers", "MedicaidLookback"],
  howTo: {
    name: "How to choose a way to leave your house to your children",
    steps: [
      { name: "Check how the house is titled", text: "Find your current deed. Note who owns it, whether a spouse is on title, and whether there is a mortgage." },
      { name: "Find out what your state allows", text: "Ask whether your state offers transfer-on-death or lady bird deeds, and how it handles Medicaid estate recovery." },
      { name: "Think about each child", text: "Note any child who is a minor, has a disability, has debts or divorce risk, or may want to live there." },
      { name: "Weigh taxes and long-term care", text: `Compare the step-up in basis with any Medicaid goal. Gifts start a ${LOOKBACK_YEARS}-year look-back in most states.` },
      { name: "Sign and record the right document", text: "Sign the trust or deed the way your state requires, then record any new deed with the county before you die." },
      { name: "Write down the family rules", text: "Say who may live there, how the house is valued, how a buyout works and when it must be sold." },
    ],
  },
  faqs: [
    { q: "Is it better to gift a house or let your children inherit it?", a: "For taxes, inheriting is usually better. A child who inherits gets a step-up in basis to the home's value at your death, so a quick sale may bring little capital gains tax. A child who receives a gift keeps your original basis and may owe tax on decades of growth. A gift can also start a Medicaid look-back period." },
    { q: "Can I put my house in my child's name to avoid probate?", a: "You can, but it is often a costly way to skip probate. Your child owns part of the house now, so their creditors or divorce can reach it. You need their signature to sell or refinance. They also lose the step-up in basis on the gifted part. A transfer-on-death deed or a living trust usually avoids probate with fewer risks." },
    { q: "Is a transfer-on-death deed better than a trust?", a: "It depends on your family. A transfer-on-death deed is cheaper and works well for a home going to adult children who get along, in states that allow it. A living trust costs more but covers incapacity, other assets, property in other states, and children who are minors or need protection." },
    { q: "Can Medicaid take my house if it is in a trust?", a: "If it is in a revocable living trust, the house still counts as yours, and many states can seek repayment from it after your death. An irrevocable Medicaid trust can protect the house, but usually only after the look-back period passes. Estate recovery rules vary by state, so ask an attorney in your state." },
    { q: "Do my children pay capital gains tax when they sell an inherited house?", a: "Only on gain above the home's value at your death, in most cases. That stepped-up basis often means little or no tax on a quick sale. If they keep the house and it grows in value, they owe tax on that later growth when they sell. A few states also have their own estate or inheritance taxes." },
    { q: "What is a lady bird deed?", a: "A lady bird deed, also called an enhanced life estate deed, lets you keep full control of your home for life. You can still sell or mortgage it. At your death the house passes to the people you named without probate. Only a few states recognize it, and its Medicaid effects vary by state." },
    { q: "Do I have to pay gift tax if I give my house to my child?", a: `Usually not, but you may need to file a gift tax return. A gift above the annual exclusion, ${GIFT_EXCLUSION} per recipient for the most recent year, is reported to the IRS. Tax is rarely due because it counts against your lifetime exemption, ${EXEMPTION} per person as of ${FIGURES.year}.` },
  ],
  related: [
    { href: "/learn/property-and-assets/leaving-your-home-to-children", label: "Leaving your house to your children" },
    { href: "/compare/transfer-on-death-deed-vs-trust", label: "Transfer-on-death deed vs trust" },
    { href: "/learn/estate-tax/step-up-in-basis", label: "Step-up in basis explained" },
    { href: "/learn/elder-care/protecting-your-home-from-nursing-home-costs", label: "Protecting your home from nursing home costs" },
    { href: "/quizzes/add-child-to-deed-check", label: "Should you add a child to your deed?" },
    { href: "/decide/types-of-trusts", label: "Types of trusts: which one fits you" },
  ],
};
