import type { DecisionGuide } from "./types";

export const LLC_VS_TRUST_RENTAL: DecisionGuide = {
  slug: "llc-vs-trust-for-rental-property",
  title: "LLC vs trust for rental property: which one, or both?",
  h1: "LLC vs trust for rental property: which one, or both?",
  description: `An LLC limits lawsuit risk from a rental. A living trust skips probate. Compare six ways to own a rental in Illinois, including both together, and find yours.`,
  kicker: "Rental property decision guide",
  art: "HeroBusinessSuccession",
  tone: "gold",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "An LLC and a trust solve different problems. An LLC can keep a tenant's lawsuit away from your other savings, but on its own it still goes through probate. A revocable living trust skips probate and covers incapacity, but it offers no lawsuit protection. Many Illinois landlords use both: the rental goes in an LLC, and their living trust owns the LLC.",
  takeaways: [
    "An LLC answers \"what if a tenant sues?\" A trust answers \"what happens when I die or cannot manage?\"",
    "A revocable trust gives no protection from lawsuits. You still own everything in it.",
    "An LLC alone does not skip probate. Your membership interest is property that passes through your estate.",
    "Good insurance comes first. An LLC with no umbrella policy and sloppy books may not protect you.",
    "Moving a mortgaged rental into an LLC can give the lender the right to call the loan. Ask before you deed it.",
  ],
  noun: "way to own a rental",
  families: [
    { id: "personal", name: "Keep it in your name", text: "You own the rental directly and rely on insurance for lawsuits.", tone: "clay" },
    { id: "liability", name: "Wall off lawsuits", text: "A company owns the rental, so a claim about the property stays with the company.", tone: "accent" },
    { id: "estate", name: "Plan for death and incapacity", text: "A trust holds title so your family can take over without a court case.", tone: "sage" },
    { id: "both", name: "Both together", text: "An LLC for lawsuits, owned by your trust for probate and incapacity.", tone: "gold" },
  ],
  dimensions: [
    { id: "liability", label: "Lawsuit protection", help: "Does a claim about the rental stay away from your home and savings?" },
    { id: "probate", label: "Avoids probate", help: "Does the rental pass at death without an Illinois probate case?" },
    { id: "incapacity", label: "Covers incapacity", help: "Is someone ready to collect rent and make repairs if you cannot?" },
    { id: "privacy", label: "Privacy", help: "Does your name stay off the deed and public records?" },
    { id: "loan", label: "Easy with your mortgage", help: "Can you set it up without the lender calling the loan or requiring a new one?" },
    { id: "effort", label: "Setup cost and upkeep", help: "Filing fees, yearly reports, separate accounts and legal help. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "personal",
      name: "Your own name, with landlord insurance and an umbrella policy",
      short: "Own name + insurance",
      family: "personal",
      icon: "Umbrella",
      what: "You own the rental yourself and carry a landlord policy plus a personal umbrella policy, often $1 million or more, to pay claims.",
      bestFor: ["A landlord with one rental, a mortgage and modest savings", "Someone renting out a unit in the two-flat they live in", "Owners who want the simplest setup and the easiest refinancing"],
      watchOut: ["A claim above your policy limits can reach your home, savings and wages", "The rental goes through probate unless you add a TODI or a trust"],
      cells: {
        liability: { level: 1, text: "Insurance only, up to its limits" },
        probate: { level: 0, text: "No, goes through probate" },
        incapacity: { level: 0, text: "Only with a power of attorney" },
        privacy: { level: 0, text: "Your name on the deed" },
        loan: { level: 3, text: "No change to the loan" },
        effort: { level: 0, text: "Premiums only" },
      },
      map: { x: 8, y: 14 },
      learn: { href: "/learn/probate/what-is-probate", label: "What probate is and how it works" },
    },
    {
      id: "llc",
      name: "Single-member LLC",
      short: "LLC",
      family: "liability",
      icon: "Building2",
      what: "You form an LLC and deed the rental to it. A claim about the property is generally limited to what the LLC owns, as long as you treat it as a separate business.",
      bestFor: ["A landlord with real equity in a rental and other savings to protect", "Owners who will keep a separate bank account, lease in the LLC's name and file every year"],
      watchOut: ["Your LLC interest still goes through probate, and nobody may have authority to act if the agreement names no successor", "Illinois charges a yearly annual report fee, and a lender may call a residential loan if you deed the rental to an LLC"],
      cells: {
        liability: { level: 2, text: "Yes, if run as a real business" },
        probate: { level: 0, text: "No, the interest goes through probate" },
        incapacity: { level: 1, text: "Only if a successor manager is named" },
        privacy: { level: 1, text: "LLC on the deed, filing lists people" },
        loan: { level: 1, text: "May trigger due-on-sale" },
        effort: { level: 2, text: "Filing fees and annual report" },
      },
      map: { x: 14, y: 76 },
      learn: { href: "/learn/business-owners/llc-ownership-at-death", label: "What happens to your LLC when you die" },
    },
    {
      id: "both",
      name: "LLC owned by your revocable trust",
      short: "LLC + trust",
      family: "both",
      icon: "Layers",
      what: "The rental sits in an LLC for lawsuit protection, and you assign your LLC membership interest to your living trust so your successor trustee can step in at death or incapacity.",
      bestFor: ["Landlords with equity to protect who also want their family to skip probate", "Owners with several rentals or a spouse and children who will take over"],
      watchOut: ["Two sets of paperwork to keep current, and the operating agreement must allow the trust as a member", "Same mortgage questions as any LLC"],
      cells: {
        liability: { level: 2, text: "Yes, through the LLC" },
        probate: { level: 3, text: "Yes, through the trust" },
        incapacity: { level: 3, text: "Yes, successor trustee steps in" },
        privacy: { level: 2, text: "LLC on the deed, trust terms private" },
        loan: { level: 1, text: "May trigger due-on-sale" },
        effort: { level: 3, text: "Highest, two documents to maintain" },
      },
      map: { x: 86, y: 80 },
      learn: { href: "/learn/trusts/how-to-fund-a-trust", label: "How to fund a trust" },
    },
    {
      id: "trust",
      name: "Revocable living trust only",
      short: "Living trust",
      family: "estate",
      icon: "House",
      what: "You deed the rental to your own living trust. You manage it as trustee, and your successor trustee takes over if you cannot or after you die.",
      bestFor: ["A landlord whose main worry is probate and incapacity, with insurance for lawsuits", "Owners of an owner-occupied two-flat or rentals in more than one state"],
      watchOut: ["No lawsuit protection at all, because you still own everything in the trust", "Federal protection from due-on-sale clauses covers a home you live in, not a pure rental, so check with the lender"],
      cells: {
        liability: { level: 0, text: "None, still yours" },
        probate: { level: 3, text: "Yes, once deeded to it" },
        incapacity: { level: 3, text: "Yes, successor trustee" },
        privacy: { level: 2, text: "Trust name on deed" },
        loan: { level: 2, text: "Usually allowed, ask first" },
        effort: { level: 2, text: "Moderate, plus a new deed" },
      },
      map: { x: 84, y: 10 },
      learn: { href: "/learn/trusts/revocable-living-trust", label: "Revocable living trusts explained" },
    },
    {
      id: "landtrust",
      name: "Illinois land trust",
      short: "Land trust",
      family: "estate",
      icon: "KeyRound",
      what: "A bank or trust company holds title as trustee, and you hold the beneficial interest and direct every decision. The deed shows a trust number instead of your name.",
      bestFor: ["Landlords who want their name off the land records", "Owners who want to sell or transfer the rental by assigning the beneficial interest"],
      watchOut: ["It hides who owns the rental but does not stop a tenant from suing you", "It skips probate only if the agreement names who takes the beneficial interest at your death, and the trustee charges yearly fees"],
      cells: {
        liability: { level: 0, text: "Hidden, not shielded" },
        probate: { level: 2, text: "Only with a death beneficiary" },
        incapacity: { level: 1, text: "Only if someone else can direct" },
        privacy: { level: 3, text: "Name off the public record" },
        loan: { level: 2, text: "Many Illinois lenders accept it" },
        effort: { level: 2, text: "Trustee fees each year" },
      },
      map: { x: 62, y: 24 },
    },
    {
      id: "series",
      name: "Series LLC",
      short: "Series LLC",
      family: "liability",
      icon: "Network",
      what: "One LLC with separate series inside it, each holding its own rental. Illinois allows them, and the goal is that a claim against one series cannot reach the others.",
      bestFor: ["Investors with several rentals who want each one walled off", "Owners who own rentals free and clear or with commercial loans"],
      watchOut: ["Many lenders, title companies and courts outside Illinois are unsure how to treat a series", "Each series has its own state filing and fee, and the rules are newer and less tested than a regular LLC"],
      cells: {
        liability: { level: 3, text: "Each rental walled off, if upheld" },
        probate: { level: 0, text: "No, interest goes through probate" },
        incapacity: { level: 1, text: "Only if a successor is named" },
        privacy: { level: 1, text: "Series name on the deed" },
        loan: { level: 0, text: "Many lenders will not lend" },
        effort: { level: 3, text: "Filings for each series" },
      },
      map: { x: 26, y: 90 },
    },
  ],
  map: {
    title: "The rental property map",
    lead: "Options on the right skip probate. Options higher up do more to keep a tenant's lawsuit away from your home and savings. The top right corner, an LLC owned by your trust, does both.",
    x: { low: "Goes through probate", high: "Skips probate" },
    y: { low: "Little lawsuit protection", high: "More lawsuit protection" },
  },
  questions: [
    {
      id: "count",
      prompt: "How many rental properties do you own?",
      choices: [
        { id: "one", label: "One", weights: { personal: 2, trust: 1, llc: 1, series: -2 }, reason: "With one rental, insurance and a simple setup may be enough" },
        { id: "few", label: "Two to four", weights: { llc: 2, both: 2, series: 1 }, reason: "Several rentals add more lawsuit risk and more to pass on" },
        { id: "many", label: "Five or more", weights: { series: 3, both: 2, llc: 1, personal: -2 }, reason: "With many rentals, walling each one off can be worth the paperwork" },
      ],
    },
    {
      id: "worry",
      prompt: "What worries you most?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "lawsuit", label: "A tenant or guest suing me", weights: { llc: 3, both: 3, series: 3, trust: -1 }, reason: "You want a claim about the rental kept away from your home and savings" },
        { id: "probate", label: "My family going through probate", weights: { trust: 3, both: 3, landtrust: 1, llc: -1, series: -1 }, reason: "You want the rental to pass without probate" },
        { id: "incapacity", label: "Who collects rent if I cannot", weights: { trust: 2, both: 2 }, reason: "You want someone ready to run the rental if you cannot" },
        { id: "privacy", label: "Tenants or others finding out what I own", weights: { landtrust: 5, both: 1 }, reason: "You want your name off the public records, which an Illinois land trust does well" },
        { id: "neither", label: "None. Insurance feels like enough", weights: { personal: 4 }, reason: "You are comfortable relying on landlord and umbrella insurance" },
      ],
    },
    {
      id: "loan",
      prompt: "What kind of loan is on the rental?",
      choices: [
        { id: "residential", label: "A regular residential mortgage", weights: { personal: 2, trust: 1, landtrust: 1, llc: -1, both: -1, series: -2 }, reason: "A residential lender may call the loan if you deed the rental to an LLC" },
        { id: "commercial", label: "A commercial or LLC loan", weights: { llc: 2, both: 2, series: 1 }, reason: "Your lender already expects a company to own the rental" },
        { id: "none", label: "No loan, it is paid off", weights: { llc: 1, both: 1, series: 2 }, reason: "With no loan, you are free to deed the rental to a company" },
      ],
    },
    {
      id: "live",
      prompt: "Do you live in the building, such as one unit of a two-flat?",
      choices: [
        { id: "yes", label: "Yes, I live in one of the units", weights: { trust: 3, personal: 2, llc: -2, series: -2 }, reason: "You live in the building, so a trust keeps your homeowner protections intact" },
        { id: "no", label: "No, it is purely a rental", weights: { llc: 1, both: 1, series: 1 } },
      ],
    },
    {
      id: "plan",
      prompt: "Do you already have a revocable living trust?",
      choices: [
        { id: "yes", label: "Yes", weights: { both: 3, trust: 2 }, reason: "You already have a trust that can own the rental or your LLC interest" },
        { id: "no", label: "No, and I do not want one yet", weights: { personal: 1, llc: 2, landtrust: 1, series: 1, both: -2, trust: -2 }, reason: "You want to protect the rental without a full estate plan right now" },
        { id: "planning", label: "No, but I am making a plan", weights: { both: 2, trust: 2 }, reason: "You are building an estate plan, so the rental can be part of it" },
      ],
    },
    {
      id: "upkeep",
      prompt: "How much yearly upkeep will you actually keep up with?",
      help: "An LLC only protects you if it is run like a separate business.",
      choices: [
        { id: "low", label: "Very little", weights: { personal: 3, trust: 2, llc: -2, both: -2, series: -3 }, reason: "You want a setup that needs almost no yearly upkeep" },
        { id: "some", label: "A yearly fee and filing is fine", weights: { llc: 2, landtrust: 2, both: 1 }, reason: "You will keep up a yearly filing and fee" },
        { id: "full", label: "Separate books, accounts and filings for each property", weights: { series: 3, both: 2, llc: 1 }, reason: "You will run each rental like its own business" },
      ],
    },
  ],
  resultNote: "Insurance is the first layer for any landlord. An Illinois attorney can check your loan, deed and operating agreement before you move a rental.",
  shortcuts: [
    { when: "You own one rental with a residential mortgage and modest savings", pick: "personal" },
    { when: "You have real equity to protect and do not need a probate plan yet", pick: "llc" },
    { when: "You want both lawsuit protection and no probate for your family", pick: "both" },
    { when: "You live in one unit of a two-flat or three-flat", pick: "trust" },
    { when: "Your main goal is keeping your name off the Illinois land records", pick: "landtrust" },
    { when: "You own several paid-off rentals and want each one walled off", pick: "series" },
  ],
  diagrams: ["BusinessSuccession", "TrustFundingAssets"],
  howTo: {
    name: "How to choose between an LLC and a trust for a rental",
    steps: [
      { name: "Price your insurance first", text: "Get quotes for a landlord policy and a personal umbrella policy. Many landlords carry $1 million or more of umbrella coverage, and it protects you whether or not you form an LLC." },
      { name: "Call your lender before you deed anything", text: "Ask whether moving the rental to an LLC, a trust or a land trust triggers the due-on-sale clause. Get the answer in writing." },
      { name: "Form the LLC and run it like a business", text: "File with the Illinois Secretary of State, sign an operating agreement, open a separate bank account, and put leases and insurance in the LLC's name. File the annual report every year." },
      { name: "Make the LLC part of your estate plan", text: "Assign your membership interest to your living trust, or name a successor manager in the operating agreement, so someone can act if you die or cannot manage." },
      { name: "Record the new deed and update your policies", text: "Record the deed with the county recorder, then make sure your title insurance and landlord policy name the new owner." },
    ],
  },
  faqs: [
    { q: "Should I put my rental property in an LLC or a trust?", a: "It depends on what you are protecting against. An LLC helps if a tenant sues, and a living trust helps your family skip probate and covers incapacity. If you want both, put the rental in an LLC and have your living trust own the LLC." },
    { q: "Does a revocable trust protect my rental from lawsuits?", a: "No. You still own and control everything in a revocable trust, so a person who wins a judgment against you can reach the rental. A revocable trust is about probate and incapacity, not lawsuits." },
    { q: "Does an LLC avoid probate?", a: "Not by itself. The LLC owns the rental, but you own the LLC, and your membership interest is part of your estate. To skip probate, assign the interest to your living trust or use another transfer at death that your operating agreement and Illinois law allow." },
    { q: "Will my mortgage lender call the loan if I put my rental in an LLC?", a: "It can. Most residential mortgages have a due-on-sale clause, and the federal law that protects transfers to a living trust covers a home you live in, not a transfer of a rental to an LLC. Many lenders never act on it, but ask first and get the answer in writing." },
    { q: "How much does an LLC cost in Illinois?", a: "You pay a state filing fee to form the LLC and an annual report fee every year after that, plus any legal help and registered agent fees. Check the Illinois Secretary of State's current fee schedule, because the amounts change. Missing the annual report can lead to the LLC being dissolved." },
    { q: "What is an Illinois land trust, and does it protect a rental?", a: "It is an Illinois arrangement where a trustee holds title and you keep full control as the beneficiary. It keeps your name off the deed, which makes you harder to find, but it does not stop a lawsuit. It also skips probate only if the agreement names who takes your interest at death." },
    { q: "Is a series LLC worth it for several rentals in Illinois?", a: "It can be for an investor with several paid-off or commercially financed rentals. Illinois allows series LLCs, but each series needs its own filing and fee, and some lenders and courts outside Illinois are unsure how to treat them. Separate LLCs for each property are the more familiar choice." },
    { q: "What happens to a rental property when the landlord dies?", a: "If the rental was in the landlord's name alone, an Illinois probate case is usually needed before it can be sold or retitled, and leases stay in force. If it was in a trust, or in an LLC owned by a trust, the successor trustee can step in, collect rent and handle repairs right away." },
  ],
  related: [
    { href: "/learn/business-owners/llc-ownership-at-death", label: "What happens to your LLC when you die" },
    { href: "/learn/trusts/how-to-fund-a-trust", label: "How to fund a trust" },
    { href: "/learn/property-and-assets/out-of-state-property", label: "Owning property in another state" },
    { href: "/decide/ways-to-hold-title-to-property", label: "Ways to hold title to a house" },
    { href: "/decide/ways-to-avoid-probate", label: "Ways to avoid probate compared" },
    { href: "/decide/types-of-trusts", label: "Types of trusts: which one fits you" },
  ],
};
