import { FIGURES, usdFigure } from "@/config/figures";
import type { DecisionGuide } from "./types";

const GIFT_EXCLUSION = usdFigure(FIGURES.annualGiftExclusion);

export const MONEY_FOR_MINORS: DecisionGuide = {
  slug: "leaving-money-to-minor-children",
  title: "Leaving money to minor children: trust, UTMA or 529?",
  h1: "Leaving money to minor children, and which way fits you",
  description:
    "Trusts, UTMA accounts, 529 plans, court accounts and informal promises compared. Answer six questions to see how to leave money to a child safely.",
  kicker: "Money for minors decision guide",
  art: "HeroGuardianship",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "A child under 18 cannot legally manage an inheritance. Without a plan, a court often appoints someone to hold the money, and the child may get it all at 18. Most parents use a trust, which lets them pick the manager and the payout ages. A UTMA custodial account suits smaller gifts, and a 529 plan suits college savings.",
  takeaways: [
    "A minor cannot own and manage an inheritance. Someone has to hold it, and you can choose who or leave it to a court.",
    "A trust gives you the most control: who manages the money, what it pays for and the ages your child receives it.",
    "A UTMA account is simple and low cost, but the child gets everything at an age set by state law, often 18 or 21.",
    "Life insurance and retirement forms that name a minor directly often lead to court, whatever your will says.",
    "Leaving money to a relative to hold informally creates no legal duty, and their creditors or divorce can reach it.",
  ],
  noun: "option",
  families: [
    { id: "rules", name: "Your rules", text: "You write the rules and pick the manager, and they can last as long as you want.", tone: "accent" },
    { id: "accounts", name: "Simple accounts", text: "Low-cost accounts with rules set by law or the plan, best for gifts and savings.", tone: "sage" },
    { id: "default", name: "What happens without a plan", text: "A court steps in, or the money depends on one person's goodwill.", tone: "clay" },
  ],
  dimensions: [
    { id: "age", label: "You choose the age", help: "Can you decide when the child gets full control?" },
    { id: "court", label: "Keeps the court out", help: "Does the money reach the child without a judge?" },
    { id: "spending", label: "Flexible spending", help: "Can the money pay for what the child really needs?" },
    { id: "protect", label: "Protects the money", help: "From misuse, a manager's debts, or the child's creditors and divorce." },
    { id: "forms", label: "Works on beneficiary forms", help: "Can you name it on life insurance or a retirement account?" },
    { id: "effort", label: "Cost and upkeep", help: "Relative cost and paperwork. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "trust",
      name: "Trust for your children",
      short: "Children's trust",
      family: "rules",
      icon: "ShieldCheck",
      what: "A trust in your living trust or will that holds money for your children. A trustee you choose spends it under your rules, then pays it out at the ages you set.",
      bestFor: [
        "Parents of young children, especially with life insurance",
        "Anyone who wants payouts later than 18 or 21",
        "Families who want one shared pot until the youngest grows up",
      ],
      watchOut: ["Costs more to set up than a simple account", "A trust in a will only starts after probate"],
      cells: {
        age: { level: 3, text: "Yes, any ages you choose" },
        court: { level: 3, text: "Yes, if in a living trust" },
        spending: { level: 3, text: "Your rules, any purpose" },
        protect: { level: 3, text: "Strong, with spendthrift terms" },
        forms: { level: 3, text: "Yes, name the trust" },
        effort: { level: 2, text: "Moderate, plus a trustee" },
      },
      map: { x: 86, y: 84 },
      learn: { href: "/learn/trusts/trusts-for-children", label: "Trusts for children explained" },
    },
    {
      id: "utma",
      name: "UTMA or UGMA custodial account",
      short: "UTMA account",
      family: "accounts",
      icon: "Wallet",
      what: "An account under your state's transfers to minors law. A custodian manages it for the child, who takes full control at an age set by state law.",
      bestFor: ["Modest gifts from parents, grandparents or relatives", "Small sums where a trust would cost too much"],
      watchOut: [
        "The child gets everything at 18 to 21, or up to 25 in some states",
        "Counts as the child's asset for financial aid",
      ],
      cells: {
        age: { level: 1, text: "State law sets it" },
        court: { level: 3, text: "Usually, no court" },
        spending: { level: 2, text: "Any use for the child" },
        protect: { level: 1, text: "Some, ends at transfer" },
        forms: { level: 2, text: "Yes, in many states" },
        effort: { level: 1, text: "Low" },
      },
      map: { x: 40, y: 40 },
      learn: { href: "/guides/leaving-money-to-minors", label: "Custodial accounts and trusts for minors" },
    },
    {
      id: "plan-529",
      name: "529 education savings plan",
      short: "529 plan",
      family: "accounts",
      icon: "Landmark",
      what: "A state-sponsored savings account for education. Growth is tax-free when spent on qualified school costs, and the account owner, not the child, keeps control.",
      bestFor: ["Parents and grandparents saving for school now", "People who want to keep control of the money"],
      watchOut: ["Other uses mean tax and a penalty on earnings", "Name a successor owner, or the account may be stuck"],
      cells: {
        age: { level: 2, text: "Owner keeps control" },
        court: { level: 3, text: "Yes, with a successor owner" },
        spending: { level: 1, text: "Mainly education" },
        protect: { level: 2, text: "Owner controls, varies by state" },
        forms: { level: 0, text: "Not usually" },
        effort: { level: 1, text: "Low, plan fees" },
      },
      map: { x: 58, y: 62 },
    },
    {
      id: "court",
      name: "Court guardianship of the estate",
      short: "Court account",
      family: "default",
      icon: "Scale",
      what: "What often happens with no plan. A judge appoints a guardian or conservator of the estate to manage the child's money under court rules.",
      bestFor: ["No one by choice. It is the fallback when a minor inherits directly", "Showing what a plan saves your family from"],
      watchOut: [
        "Bonds, court reports and approvals take time and money",
        "In many states the child gets it all at 18",
      ],
      cells: {
        age: { level: 0, text: "No, usually 18" },
        court: { level: 0, text: "No, court runs it" },
        spending: { level: 1, text: "Court approves big costs" },
        protect: { level: 2, text: "Oversight until 18" },
        forms: { level: 0, text: "No, it is the fallback" },
        effort: { level: 3, text: "High, ongoing court costs" },
      },
      map: { x: 10, y: 64 },
      learn: { href: "/learn/guardianship/leaving-money-to-minors", label: "What happens when a minor inherits" },
    },
    {
      id: "informal",
      name: "Leaving it to an adult to hold for them",
      short: "Informal promise",
      family: "default",
      icon: "HandHeart",
      what: "You leave the money to a relative or friend and ask them to use it for your child. Legally it becomes their money, with no rules attached.",
      bestFor: ["Very small sums left to someone you trust completely", "Showing why a trust is safer for the same person"],
      watchOut: [
        "No legal duty to spend it on your child",
        "Their creditors, divorce or death can take it",
      ],
      cells: {
        age: { level: 0, text: "No, up to them" },
        court: { level: 2, text: "Yes, but no oversight" },
        spending: { level: 2, text: "Whatever the adult decides" },
        protect: { level: 0, text: "None, it is theirs" },
        forms: { level: 2, text: "Yes, but no legal duty" },
        effort: { level: 0, text: "None up front" },
      },
      map: { x: 24, y: 12 },
      learn: { href: "/learn/trusts/choosing-a-trustee", label: "Choosing who manages the money" },
    },
  ],
  map: {
    title: "The money for minors map",
    lead: "Options on the right let you set the rules. Options higher up add safeguards, so the money is more likely to reach your child as you intended.",
    x: { low: "Law or others set the rules", high: "You set the rules" },
    y: { low: "Few safeguards", high: "Strong safeguards" },
  },
  questions: [
    {
      id: "who",
      prompt: "Who do you want to leave money to?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "own", label: "My own children under 18", weights: { trust: 2 }, reason: "Your children may need money managed for years if you die while they are young" },
        { id: "others", label: "Grandchildren, nieces or nephews", weights: { utma: 2, "plan-529": 2 }, reason: "Gifts to other people's children often go into a custodial or 529 account" },
        { id: "disability", label: "A child with a disability", weights: { trust: 3, utma: -2 }, reason: "A child with a disability usually needs a special needs trust, not an account in their name" },
      ],
    },
    {
      id: "amount",
      prompt: "Roughly how much could each child receive, including life insurance?",
      help: "A rough guess is fine.",
      choices: [
        { id: "small", label: "Under $50,000", weights: { utma: 3, "plan-529": 1, trust: -1 }, reason: "You expect a modest amount, where a simple account often works" },
        { id: "mid", label: "$50,000 to $250,000", weights: { trust: 2, utma: 1 }, reason: "A sum this size is often worth a trust's controls" },
        { id: "large", label: "More than $250,000", weights: { trust: 4, utma: -2 }, reason: "Larger sums are where staged payouts matter most" },
      ],
    },
    {
      id: "age",
      prompt: "When should your child have full control of the money?",
      choices: [
        { id: "early", label: "18 to 21 is fine", weights: { utma: 3 }, reason: "You are comfortable with full control at 18 to 21" },
        { id: "later", label: "Later, such as 25 or 30", weights: { trust: 4, utma: -2 }, reason: "You want control to wait past what custodial laws allow" },
        { id: "school", label: "It is mainly for school", weights: { "plan-529": 4 }, reason: "You mainly want to pay for education" },
        { id: "unsure", label: "Not sure", weights: { trust: 1 } },
      ],
    },
    {
      id: "source",
      prompt: "Where will most of the money come from?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "insurance", label: "Life insurance", weights: { trust: 3, utma: 1 }, reason: "A life insurance payout needs a trust or custodian named, not a child" },
        { id: "retirement", label: "Retirement accounts", weights: { trust: 2 }, reason: "Retirement accounts pass by beneficiary form, so the form needs a trust or custodian" },
        { id: "estate", label: "Savings, a home or investments under my will", weights: { trust: 2, utma: 1 }, reason: "Assets passing at death need a named manager for each child" },
        { id: "gifts", label: "Gifts I make now, while I am living", weights: { utma: 2, "plan-529": 3 }, reason: "You want to give now, which custodial and 529 accounts are built for" },
      ],
    },
    {
      id: "rules",
      prompt: "Do you want rules for how the money is spent?",
      choices: [
        { id: "detailed", label: "Yes, different rules by child or purpose", weights: { trust: 4 }, reason: "You want rules a custodial account cannot hold" },
        { id: "school", label: "Mostly school costs", weights: { "plan-529": 3 }, reason: "You mainly want to pay for education" },
        { id: "trusted", label: "No, a trusted adult can decide", weights: { utma: 2, informal: 2 }, reason: "You are happy to let a trusted adult decide" },
      ],
    },
    {
      id: "now",
      prompt: "What do you have in place today?",
      choices: [
        { id: "nothing", label: "Nothing, or a will leaving money to my children outright", weights: { court: 2, trust: 2 }, reason: "Without a plan, a court may manage the money" },
        { id: "forms", label: "Beneficiary forms that name my children directly", weights: { court: 3, trust: 3 }, reason: "Forms that name a minor directly often lead to court" },
        { id: "relative", label: "A plan to leave it to a relative to hold", weights: { informal: 3, trust: 2 }, reason: "You plan to rely on an informal promise, which a trust can make binding" },
        { id: "done", label: "A trust or custodial account already", weights: { trust: 1, utma: 1 } },
      ],
    },
  ],
  resultNote:
    "Most parents of young children use a trust for the main money and name it on life insurance and retirement forms. Custodial and court rules vary by state, so a short consult confirms what applies to you.",
  shortcuts: [
    { when: "Your life insurance names your young children directly", pick: "trust" },
    { when: "You want your children to wait until 25 or later", pick: "trust" },
    { when: "A grandparent wants to give a modest sum now", pick: "utma" },
    { when: "You are saving for college and want to keep control", pick: "plan-529" },
    { when: "You have young children and no will or trust", pick: "court" },
    { when: "You planned to leave it to a sibling to hold for the kids", pick: "informal" },
  ],
  diagrams: ["MoneyForMinors", "GuardianshipDecision"],
  howTo: {
    name: "How to leave money to a minor child",
    steps: [
      { name: "List what your child could receive", text: "Add up life insurance, retirement accounts, savings and your home. Life insurance is often the largest amount young parents leave." },
      { name: "Pick the vehicle for each source", text: "Larger sums usually go to a trust. Small gifts may suit a UTMA account, and school savings may suit a 529 plan." },
      { name: "Choose a trustee and a guardian", text: "The guardian raises your child and the trustee manages the money. They can be the same person or two people. Name backups for both." },
      { name: "Set the payout ages and rules", text: "Decide whether to use one pot for all children or a share for each, and the ages each child receives money." },
      { name: "Update every beneficiary form", text: "Name the trust or a UTMA custodian on life insurance and retirement accounts. Never name a minor child directly." },
    ],
  },
  faqs: [
    {
      q: "Can a minor inherit money?",
      a: "A minor can be left money, but cannot legally manage it. If the money goes to the child directly, a court often appoints a guardian or conservator of the estate to hold it. To avoid this, parents commonly leave the money to a trust or name a custodian under their state's transfers to minors act.",
    },
    {
      q: "At what age does a child receive an inheritance?",
      a: "It depends on how the money is held. A court account usually ends at 18 in many states. A UTMA account ends at an age set by state law, often 18 or 21 and up to 25 in some states. A trust pays out at whatever ages you choose, such as 25, 30 and 35.",
    },
    {
      q: "Is a trust or a UTMA account better for a child?",
      a: "For larger sums or for control past age 21, a trust is usually the better fit. It can stage payouts, limit what the money pays for and protect it from a child's creditors. A UTMA account is cheaper and simpler, so it often suits modest gifts from relatives.",
    },
    {
      q: "Can I name my minor child as a life insurance beneficiary?",
      a: "You can, but insurers generally will not pay a minor directly. The money may then sit in a court-supervised account until the child turns 18. Naming a trust for your children, or a custodian under your state's UTMA law, avoids this. Retirement account forms work the same way.",
    },
    {
      q: "What happens to money left to a minor with no trust?",
      a: "In many states a judge appoints a guardian or conservator of the estate. That person may need to post a bond, file regular reports and ask the court before large expenses. The costs come out of the child's money, and the child often receives what remains at 18.",
    },
    {
      q: "Can the guardian and the trustee be different people?",
      a: "Yes. The guardian raises your child, and the trustee manages the money. Some parents name one person for both jobs. Others split the roles, so a caring relative raises the children while a careful money manager runs the trust. Splitting the roles also adds a check on spending.",
    },
    {
      q: "Can I leave money to a relative to hold for my child?",
      a: "You can, but it is risky. Legally the money becomes theirs, with no duty to spend it on your child. Their creditors or a divorcing spouse may reach it, and if they die it passes to their heirs. A trust lets the same person manage the money with legal duties to your child.",
    },
    {
      q: "How much can I give a child each year without a gift tax return?",
      a: `Gifts up to the annual gift tax exclusion, ${GIFT_EXCLUSION} per child (the 2025 figure), generally need no gift tax return. That applies to gifts into a UTMA account or a 529 plan. Larger gifts usually need a return but rarely cause tax, because they count against your lifetime exemption.`,
    },
  ],
  related: [
    { href: "/learn/guardianship/leaving-money-to-minors", label: "Leaving money to minor children" },
    { href: "/learn/trusts/trusts-for-children", label: "Trusts for children" },
    { href: "/learn/guardianship/guardian-vs-trustee", label: "Guardian vs trustee" },
    { href: "/learn/beneficiary-designations/life-insurance-beneficiaries", label: "Life insurance beneficiaries" },
    { href: "/tools/guardian-fund-calculator", label: "Guardian fund calculator" },
    { href: "/decide/types-of-trusts", label: "Types of trusts, and which one fits you" },
  ],
};
