import { FIGURES } from "@/config/figures";
import type { DecisionGuide } from "./types";

const LOOKBACK_YEARS = FIGURES.medicaidLookbackMonths / 12;

export const MANAGING_PARENT_FINANCES: DecisionGuide = {
  slug: "how-to-manage-a-parents-finances",
  title: "How to manage a parent's finances: 8 options compared",
  h1: "How to manage a parent's finances: every option, and which one fits",
  description:
    "Power of attorney, joint accounts, signers, rep payee, VA fiduciary, trustee and guardianship compared for a parent's money. Answer six questions to see what fits.",
  kicker: "Aging parent money guide",
  art: "HeroAgingParents",
  tone: "gold",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "If your parent can still understand and sign a document, the usual way to manage their finances is a durable power of attorney for property. In Illinois that is often the statutory short form. Bank signer access and a trusted contact cover smaller needs. If your parent can no longer sign and has no power of attorney or trust, a court guardianship of the estate is usually the only route.",
  takeaways: [
    "The first question is whether your parent can still understand and sign a document. If yes, you have many choices. If no, you have few.",
    "A durable power of attorney for property covers almost every account, bill and asset, and it keeps working if your parent loses capacity.",
    "Adding a child as a joint owner is easy but risky. The money can pass outside the will, and the child's creditors can reach it.",
    "Social Security and the VA appoint their own helpers for their own checks. A power of attorney does not cover those payments.",
    "Guardianship of the estate is the court route when nothing was signed in time. It works, but it is slower, public and costly.",
  ],
  noun: "option",
  families: [
    { id: "signed", name: "Documents your parent signs", text: "Your parent picks who helps, while they still can. No court is involved.", tone: "accent" },
    { id: "bank", name: "Bank and account tools", text: "Quick fixes set up at one bank or brokerage. Each covers only the accounts it is added to.", tone: "sage" },
    { id: "agency", name: "Benefit helpers", text: "Social Security or the VA appoints someone to manage one benefit check.", tone: "gold" },
    { id: "court", name: "Court appointment", text: "A judge appoints someone to manage money for a parent who can no longer sign.", tone: "clay" },
  ],
  dimensions: [
    { id: "scope", label: "Money it covers", help: "One account or check, or all of your parent's money and property." },
    { id: "nocap", label: "Can start after capacity is lost", help: "Can it be set up once your parent can no longer understand a document?" },
    { id: "say", label: "Parent keeps a say", help: "Does your parent choose the helper and stay involved?" },
    { id: "estate", label: "Keeps the estate plan intact", help: "Does the money still pass under your parent's will or trust at death?" },
    { id: "safe", label: "Safeguards against misuse", help: "Duties, reports or limits that protect your parent's money." },
    { id: "court", label: "Court involved", help: "Does a judge appoint and supervise the helper? More dots means more court.", inverse: true },
    { id: "effort", label: "Cost and setup work", help: "Relative cost, delay and paperwork. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "poa",
      name: "Durable power of attorney for property",
      short: "Property POA",
      family: "signed",
      icon: "FileSignature",
      what: "A document your parent signs naming an agent to handle their money and property. In Illinois, most people use the Statutory Short Form Power of Attorney for Property.",
      bestFor: ["A parent who can still understand what they are signing", "Families who want one person to handle bank accounts, bills, taxes and the house", "Planning ahead before memory loss gets worse"],
      watchOut: ["Must be signed while your parent has capacity", "Some banks push back on older or unfamiliar forms, so give each bank a copy early", "Does not cover Social Security or VA checks"],
      cells: {
        scope: { level: 3, text: "Nearly all money and property" },
        nocap: { level: 0, text: "No, must be signed in time" },
        say: { level: 3, text: "Parent picks the agent" },
        estate: { level: 3, text: "Yes, ownership stays the same" },
        safe: { level: 2, text: "Agent owes legal duties" },
        court: { level: 0, text: "None" },
        effort: { level: 1, text: "Low, one signing" },
      },
      map: { x: 10, y: 88 },
      learn: { href: "/learn/power-of-attorney/durable-financial-power-of-attorney", label: "Durable financial power of attorney" },
    },
    {
      id: "trustee",
      name: "Successor trustee of a revocable trust",
      short: "Successor trustee",
      family: "signed",
      icon: "Landmark",
      what: "If your parent has a living trust, the successor trustee they named takes over the trust's assets when your parent can no longer manage them.",
      bestFor: ["A parent who already has a funded revocable trust", "Families with a house or investments held in the trust"],
      watchOut: ["Covers only what was actually put into the trust", "The trust sets how incapacity is proven, often letters from one or two doctors"],
      cells: {
        scope: { level: 2, text: "Trust assets only" },
        nocap: { level: 2, text: "Yes, if the trust was signed earlier" },
        say: { level: 3, text: "Parent named the trustee" },
        estate: { level: 3, text: "Yes, the trust controls" },
        safe: { level: 2, text: "Trustee owes legal duties" },
        court: { level: 0, text: "None" },
        effort: { level: 1, text: "Low if the trust exists" },
      },
      map: { x: 22, y: 72 },
      learn: { href: "/learn/trusts/choosing-a-trustee", label: "Choosing a trustee" },
    },
    {
      id: "joint",
      name: "Adding a child as a joint account owner",
      short: "Joint owner",
      family: "bank",
      icon: "Users",
      what: "Your parent adds you to an account as a co-owner. You can sign checks, and at your parent's death the account usually becomes yours.",
      bestFor: ["A parent with one child and a simple estate", "A small checking account used only for bills"],
      watchOut: ["The money passes to you at death, outside the will, which can leave siblings with less", "Your own creditors, divorce or a lawsuit can reach the account", "Medicaid usually treats the whole account as your parent's"],
      cells: {
        scope: { level: 1, text: "Only that account" },
        nocap: { level: 0, text: "No, parent must add you" },
        say: { level: 2, text: "Parent chooses, then shares" },
        estate: { level: 0, text: "No, passes to the joint owner" },
        safe: { level: 0, text: "Few, you own it too" },
        court: { level: 0, text: "None" },
        effort: { level: 0, text: "Very low, a bank form" },
      },
      map: { x: 34, y: 52 },
      learn: { href: "/learn/property-and-assets/joint-tenancy-risks", label: "Risks of joint ownership" },
    },
    {
      id: "signer",
      name: "Authorized or convenience signer",
      short: "Signer",
      family: "bank",
      icon: "KeyRound",
      what: "Your parent adds you to a bank account as a signer only. You can write checks and pay bills, but you are not an owner and do not inherit the account.",
      bestFor: ["Paying a parent's bills from one or two accounts", "Families who want the account to follow the will", "Siblings who want an equal split"],
      watchOut: ["Not every bank offers it, and names differ from bank to bank", "Ends at your parent's death, and it may stop working if your parent loses capacity, depending on the bank"],
      cells: {
        scope: { level: 1, text: "Only that account" },
        nocap: { level: 0, text: "No, parent must add you" },
        say: { level: 3, text: "Parent stays sole owner" },
        estate: { level: 3, text: "Yes, no survivor rights" },
        safe: { level: 1, text: "Some, you are not an owner" },
        court: { level: 0, text: "None" },
        effort: { level: 0, text: "Very low, a bank form" },
      },
      map: { x: 16, y: 32 },
      learn: { href: "/learn/power-of-attorney/bank-refuses-power-of-attorney", label: "When a bank refuses a power of attorney" },
    },
    {
      id: "informal",
      name: "Informal help: bill pay, view-only access and trusted contacts",
      short: "Informal help",
      family: "bank",
      icon: "ShieldCheck",
      what: "Lighter tools your parent sets up: view-only online access, automatic bill pay, account alerts, and a trusted contact the bank or brokerage can call if something looks wrong.",
      bestFor: ["A parent who still manages money but wants a second set of eyes", "Spotting scams and missed bills early"],
      watchOut: ["Gives you no power to act or sign", "A trusted contact can be told about concerns but cannot move money"],
      cells: {
        scope: { level: 0, text: "Watch only, no authority" },
        nocap: { level: 0, text: "No, parent sets it up" },
        say: { level: 3, text: "Parent stays fully in charge" },
        estate: { level: 3, text: "Yes, nothing changes" },
        safe: { level: 2, text: "Helps catch fraud early" },
        court: { level: 0, text: "None" },
        effort: { level: 0, text: "Very low" },
      },
      map: { x: 6, y: 8 },
      learn: { href: "/learn/elder-care/elder-financial-abuse", label: "Elder financial abuse" },
    },
    {
      id: "payee",
      name: "Social Security representative payee",
      short: "Rep payee",
      family: "agency",
      icon: "Receipt",
      what: "A person the Social Security Administration appoints to receive your parent's Social Security or SSI payments and spend them on your parent's needs.",
      bestFor: ["A parent whose main income is a Social Security check", "A parent who can no longer sign but has no power of attorney"],
      watchOut: ["Covers only Social Security and SSI payments", "Social Security decides who serves, and you must keep records of how the money was spent"],
      cells: {
        scope: { level: 1, text: "Social Security and SSI only" },
        nocap: { level: 3, text: "Yes" },
        say: { level: 1, text: "Agency decides" },
        estate: { level: 3, text: "Yes, ownership stays the same" },
        safe: { level: 2, text: "Agency can ask for reports" },
        court: { level: 0, text: "No, Social Security appoints" },
        effort: { level: 1, text: "Low, an interview and forms" },
      },
      map: { x: 68, y: 22 },
      learn: { href: "/learn/elder-care/helping-aging-parents-plan", label: "Helping aging parents plan" },
    },
    {
      id: "va",
      name: "VA fiduciary",
      short: "VA fiduciary",
      family: "agency",
      icon: "BadgeCheck",
      what: "A person the Department of Veterans Affairs appoints to manage a veteran's or surviving spouse's VA benefits after the VA finds they cannot manage them.",
      bestFor: ["A parent who gets a VA pension or disability payments", "Veterans and surviving spouses rated unable to manage their own benefits"],
      watchOut: ["Covers only VA benefits", "The VA screens the fiduciary and can require accountings and a bond"],
      cells: {
        scope: { level: 1, text: "VA benefits only" },
        nocap: { level: 3, text: "Yes" },
        say: { level: 1, text: "VA decides, family can be named" },
        estate: { level: 3, text: "Yes, ownership stays the same" },
        safe: { level: 3, text: "VA oversight and reports" },
        court: { level: 0, text: "No, the VA appoints" },
        effort: { level: 2, text: "Moderate, VA review" },
      },
      map: { x: 76, y: 36 },
      learn: { href: "/learn/elder-care/va-aid-and-attendance", label: "VA Aid and Attendance" },
    },
    {
      id: "guardian",
      name: "Guardianship of the estate",
      short: "Guardianship",
      family: "court",
      icon: "Gavel",
      what: "A court appoints someone to manage the money and property of an adult who can no longer do it and who has no working power of attorney. Illinois calls this a guardian of the estate.",
      bestFor: ["A parent who can no longer sign and has no power of attorney or trust", "Stopping an agent or relative who is misusing a parent's money"],
      watchOut: ["Takes weeks or months, and costs court and lawyer fees", "The guardian files inventories and accountings with the court, and often posts a bond", "Your parent loses the right to manage their own money"],
      cells: {
        scope: { level: 3, text: "All money and property" },
        nocap: { level: 3, text: "Yes, made for this case" },
        say: { level: 0, text: "Judge decides" },
        estate: { level: 3, text: "Yes, ownership stays the same" },
        safe: { level: 3, text: "Court reports and approvals" },
        court: { level: 3, text: "Yes, start to finish" },
        effort: { level: 3, text: "High, fees and yearly reports" },
      },
      map: { x: 86, y: 90 },
      learn: { href: "/learn/power-of-attorney/parent-with-dementia-no-power-of-attorney", label: "A parent with dementia and no power of attorney" },
    },
  ],
  map: {
    title: "The parent finances map",
    lead: "Options on the left are ones your parent sets up while they can. Moving right, an agency or a court appoints the helper. Higher options cover more of your parent's money.",
    x: { low: "Parent sets it up", high: "Agency or court appoints" },
    y: { low: "Narrow help", high: "Covers most of their money" },
  },
  questions: [
    {
      id: "capacity",
      prompt: "Can your parent still understand and sign a legal document?",
      help: "This bar is lower than managing money alone. Many people with early dementia can still sign. A doctor or attorney can help you tell.",
      choices: [
        { id: "yes", label: "Yes, they understand what they would sign", weights: { poa: 5, signer: 2, informal: 2, joint: 1, guardian: -4 }, reason: "Your parent can still sign, so they can choose their own helper without court" },
        { id: "slipping", label: "Yes for now, but memory is slipping", weights: { poa: 6, trustee: 1, guardian: -3 }, reason: "Your parent can still sign, but the window to do it may be closing" },
        { id: "no", label: "No, they can no longer understand or sign", weights: { guardian: 4, payee: 2, va: 2, trustee: 2, poa: -6, signer: -4, joint: -4, informal: -4 }, reason: "Your parent can no longer sign, so the options are ones others put in place" },
        { id: "unsure", label: "Not sure", weights: { poa: 1 } },
      ],
    },
    {
      id: "money",
      prompt: "What money needs looking after?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "bills", label: "Monthly bills from a checking account", weights: { signer: 3, poa: 2, joint: 1, informal: 1 }, reason: "You mainly need to pay bills from one account" },
        { id: "ss", label: "A Social Security or SSI check", weights: { payee: 6 }, reason: "Social Security pays only a payee it appoints, not an agent under a power of attorney" },
        { id: "vab", label: "VA pension or disability payments", weights: { va: 7 }, reason: "The VA uses its own fiduciary to manage VA benefits" },
        { id: "trust", label: "A house or investments held in a living trust", weights: { trustee: 6 }, reason: "Assets in a living trust are run by the successor trustee" },
        { id: "big", label: "A house, investments, taxes or a sale outside any trust", weights: { poa: 3, guardian: 2, signer: -1, joint: -1 }, reason: "You need authority over property and taxes, not only a bank account" },
      ],
    },
    {
      id: "docs",
      prompt: "What has your parent already signed?",
      help: "Pick all that apply. Look for papers from an earlier visit to a lawyer.",
      multi: true,
      choices: [
        { id: "poa", label: "A power of attorney for property", weights: { poa: 6, guardian: -3 }, reason: "A signed power of attorney is already in place, so the agent can usually act now" },
        { id: "trust", label: "A revocable living trust", weights: { trustee: 4, guardian: -2 }, reason: "Your parent's trust already names who takes over" },
        { id: "none", label: "Neither, or we cannot find them", weights: { guardian: 2, signer: 1, payee: 1 } },
      ],
    },
    {
      id: "help",
      prompt: "How much help does your parent need right now?",
      choices: [
        { id: "watch", label: "Just a second set of eyes on scams and late bills", weights: { informal: 6, signer: 1 }, reason: "Your parent still handles money and mainly needs someone watching for problems" },
        { id: "alongside", label: "Someone to pay bills alongside them", weights: { signer: 4, joint: 2, informal: 1 }, reason: "You need to pay bills while your parent stays in charge" },
        { id: "takeover", label: "Someone to take over most money matters", weights: { poa: 3, trustee: 2, guardian: 2, informal: -3 }, reason: "Someone needs authority to run most of your parent's money" },
      ],
    },
    {
      id: "family",
      prompt: "Which of these are true for your family?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "siblings", label: "Siblings should end up with equal shares", weights: { signer: 3, poa: 2, joint: -4 }, reason: "You want the money to follow your parent's will, so siblings share as planned" },
        { id: "risk", label: "The helper has debts, a lawsuit or a shaky marriage", weights: { signer: 2, poa: 2, joint: -5 }, reason: "Joint ownership would expose your parent's money to the helper's own problems" },
        { id: "onlychild", label: "I am the only child and my parent wants the account to come to me", weights: { joint: 6 }, reason: "Your parent wants the account to pass to you anyway, which is what joint ownership does" },
        { id: "misuse", label: "Someone may be misusing my parent's money now", weights: { guardian: 4, informal: 1 }, reason: "A court can step in and remove a person who is misusing your parent's money" },
        { id: "medicaid", label: `Nursing home care may be needed within ${LOOKBACK_YEARS} years`, weights: { poa: 2, joint: -2 }, reason: "An agent with the right powers can help with Medicaid planning" },
      ],
    },
    {
      id: "court",
      prompt: "How do you feel about going to court?",
      choices: [
        { id: "avoid", label: "I want to stay out of court if at all possible", weights: { poa: 2, trustee: 2, signer: 1, payee: 1, va: 1, guardian: -2 }, reason: "You want to avoid a court case" },
        { id: "ok", label: "Court is fine if it is the only way", weights: { guardian: 3 }, reason: "You are ready to ask a court if nothing else works" },
      ],
    },
  ],
  resultNote:
    "Most families use more than one of these. A typical mix is a power of attorney for property, a trusted contact at each bank, and a rep payee for Social Security if needed. A short consult confirms what your parent can still sign.",
  shortcuts: [
    { when: "Your parent can still understand and sign a document", pick: "poa" },
    { when: "Your parent has a living trust that holds the house or investments", pick: "trustee" },
    { when: "You only need to pay bills and want siblings to share equally", pick: "signer" },
    { when: "Your parent is fine with money but you worry about scams", pick: "informal" },
    { when: "The main income is a Social Security or SSI check and your parent cannot manage it", pick: "payee" },
    { when: "Your parent gets VA benefits and the VA has rated them unable to manage them", pick: "va" },
    { when: "Your parent can no longer sign and nothing was signed in time", pick: "guardian" },
    { when: "You are thinking of putting your name on every account", pick: "poa" },
  ],
  diagrams: ["PoaHealthcareRoles", "LivingTrustFlow"],
  howTo: {
    name: "How to start managing a parent's finances",
    steps: [
      { name: "Talk with your parent early", text: "Ask what help they want and who they trust. Bring it up before a crisis, while they can still take part and sign." },
      { name: "Find what is already signed", text: "Look for a power of attorney, a living trust and any bank signer forms. Call the lawyer who drafted them if you know who it was." },
      { name: "Sign the missing documents", text: "If your parent can still sign, have them sign a durable power of attorney for property. In Illinois, the statutory short form is signed before a notary and one witness who is not the agent." },
      { name: "Set up each account", text: "Give every bank and brokerage a copy of the power of attorney. Add a trusted contact, view-only access and bill pay where they help." },
      { name: "Handle benefit checks separately", text: "Apply to Social Security to be a representative payee, or to the VA for a fiduciary, if your parent cannot manage those payments." },
      { name: "Keep records and separate money", text: "Never mix your parent's money with yours. Keep receipts and a simple ledger so you can show every dollar was spent for your parent." },
    ],
  },
  faqs: [
    { q: "How do I manage my parent's finances without a power of attorney?", a: "If your parent can still sign, the simplest fix is to have them sign one now. If they cannot, you can become a Social Security representative payee or a VA fiduciary for those checks, and a bank may let you help with an account your parent already added you to. For everything else, you will likely need a court guardianship of the estate." },
    { q: "Can I just add my name to my parent's bank account?", a: "Your parent can add you, but you cannot add yourself. Joint ownership is easy, but the account usually passes to you at death outside the will, which can shortchange siblings. Your creditors could also reach the money. A signer-only arrangement or a power of attorney avoids those problems." },
    { q: "What is the difference between a power of attorney and a joint account?", a: "A power of attorney lets you act for your parent, but the money stays theirs and passes under their will or trust. A joint account makes you a co-owner, so the money is partly yours now and usually all yours at death. A power of attorney also covers many accounts and assets, while a joint account covers only one." },
    { q: "What is a convenience account?", a: "It is an account where a second person is added only to help pay bills, not to inherit. Banks use names like authorized signer or convenience signer. If a child is listed as a full joint owner \"for convenience,\" the bank may still pay the child at death, so check exactly how the account is titled." },
    { q: "What is a representative payee?", a: "It is a person the Social Security Administration appoints to receive someone's Social Security or SSI payments and use them for that person's needs. The payee must keep the money separate and keep records. A power of attorney does not let you manage Social Security payments, so families often need both." },
    { q: "Who can see a parent's bank accounts?", a: "Only your parent and anyone they gave access to, such as a joint owner, a signer or an agent under a power of attorney. View-only online access lets you see balances without the power to move money. Banks and brokerages can also list you as a trusted contact to call if they suspect fraud." },
    { q: "Does Medicaid count money in a joint account with a child?", a: `Usually yes. Medicaid generally treats the whole account as your parent's unless you can prove you put in the money. Taking your name off, or pulling money out for yourself, can count as a gift during the ${LOOKBACK_YEARS}-year look-back. Talk with an elder law attorney before moving money.` },
    { q: "Do I need guardianship if my parent has dementia?", a: "Not if your parent signed a durable power of attorney for property, or a living trust, before they lost capacity. Those documents keep working after a dementia diagnosis. Guardianship is usually needed only when nothing was signed in time, or when an agent is misusing their power." },
  ],
  related: [
    { href: "/decide/types-of-power-of-attorney", label: "Types of power of attorney" },
    { href: "/decide/alternatives-to-guardianship", label: "Alternatives to adult guardianship" },
    { href: "/learn/power-of-attorney/parent-with-dementia-no-power-of-attorney", label: "A parent with dementia and no power of attorney" },
    { href: "/learn/elder-care/helping-aging-parents-plan", label: "Helping aging parents plan" },
    { href: "/learn/elder-care/elder-financial-abuse", label: "Elder financial abuse" },
    { href: "/decide/guardianship-vs-conservatorship", label: "Guardianship vs conservatorship" },
  ],
};
