import type { DecisionGuide } from "./types";

/*
 * One example family runs through this whole guide (the interactive family tree uses the same one):
 * you have three children, Ann, Ben and Cara. Ben dies before you and leaves two children. Cara has one child.
 * The estate is $300,000. Keep these numbers in step with the widget.
 */

export const PER_STIRPES_VS_PER_CAPITA: DecisionGuide = {
  slug: "per-stirpes-vs-per-capita",
  title: "Per stirpes vs per capita: who inherits if a child dies first",
  h1: "Per stirpes vs per capita: who gets what if a child dies before you",
  description: `Per stirpes, per capita and three other ways to handle a share when a child dies before you, shown with one family and a $300,000 estate. Six questions to pick.`,
  kicker: "Beneficiary decision guide",
  art: "HeroWills",
  tone: "gold",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "Per stirpes keeps a child's share in that child's family. If your son dies before you, his children split his share. Per capita usually splits the money equally among the people still alive at that level, so his share goes to your other children and his kids get nothing. Most parents who want grandchildren to step into a parent's place choose per stirpes. Always check how your document defines the words.",
  takeaways: [
    "The choice only matters if someone dies before you. Until then, every option pays the same people.",
    "Per stirpes means \"by branch.\" A child who dies first passes their share down to their own children.",
    "\"Per capita\" has no single meaning. Some documents cut out a dead child's family, others count every grandchild as a head.",
    "Retirement account and life insurance forms follow their own rules, not your will. Some offer a per stirpes box and some do not.",
    "In Illinois, if you die without a will, your descendants inherit per stirpes.",
  ],
  noun: "way to split a share",
  families: [
    { id: "branch", name: "Shares follow the family tree", text: "A child who dies first is replaced by their own children, so each branch keeps its part.", tone: "accent" },
    { id: "heads", name: "Equal shares per person", text: "The money is split by counting the people alive at a certain level of the family.", tone: "sage" },
    { id: "pool", name: "No substitute", text: "The share of someone who died first goes back into the pot for everyone else.", tone: "clay" },
    { id: "names", name: "You name the backups", text: "You write down exactly who gets a share if your first choice has died.", tone: "gold" },
  ],
  dimensions: [
    { id: "branch", label: "Keeps a branch's share", help: "Do Ben's children get the share Ben would have had?" },
    { id: "equal", label: "Equal per person", help: "Do people at the same level of the family get the same amount?" },
    { id: "clear", label: "Clear meaning", help: "Will your family, the court and the account company read it the same way?" },
    { id: "forms", label: "Easy on 401(k) and IRA forms", help: "Can you set it up on a typical retirement or insurance beneficiary form?" },
    { id: "later", label: "Covers grandchildren born later", help: "Does a grandchild born after you sign get included without an update?" },
    { id: "upkeep", label: "Needs updating", help: "How often you must revise it as the family changes. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "stirpes",
      name: "Per stirpes (by branch)",
      short: "Per stirpes",
      family: "branch",
      icon: "GitBranch",
      what: "Each child's share stays in that child's branch. With a $300,000 estate, Ann gets $100,000, Cara gets $100,000 and Ben's two children get $50,000 each.",
      bestFor: ["Parents who want grandchildren to take a parent's place", "Families with children who have different numbers of kids", "Anyone who wants the plan to adjust on its own as grandchildren are born"],
      watchOut: ["A grandchild under 18 cannot take money directly, so name a custodian or a trust", "Stepchildren and a child's spouse are not part of the branch unless you name them"],
      cells: {
        branch: { level: 3, text: "Yes, Ben's kids get $50k each" },
        equal: { level: 1, text: "Equal per branch, not per head" },
        clear: { level: 3, text: "Widely understood" },
        forms: { level: 2, text: "Many forms have a box for it" },
        later: { level: 3, text: "Yes, new grandkids join a branch" },
        upkeep: { level: 0, text: "Rarely needs changes" },
      },
      map: { x: 10, y: 16 },
      learn: { href: "/glossary/per-stirpes", label: "Per stirpes defined" },
    },
    {
      id: "capita",
      name: "Per capita (equal among those still living)",
      short: "Per capita",
      family: "heads",
      icon: "UsersRound",
      what: "The money is split equally among the people alive at that level. Under the common meaning, Ann and Cara get $150,000 each and Ben's children get nothing.",
      bestFor: ["Parents who want only their living children to inherit", "Gifts to a group, such as siblings, where you want the survivors to share"],
      watchOut: ["Other documents use per capita to mean every living descendant counts as one head, which would give five people $60,000 each", "Easy to cut out grandchildren by accident"],
      cells: {
        branch: { level: 0, text: "No, Ben's kids get $0" },
        equal: { level: 3, text: "Ann and Cara get $150k each" },
        clear: { level: 1, text: "Meaning varies by document" },
        forms: { level: 1, text: "Some forms offer it" },
        later: { level: 1, text: "Depends on the wording" },
        upkeep: { level: 1, text: "Low, if the wording is clear" },
      },
      map: { x: 82, y: 14 },
      learn: { href: "/glossary/per-capita", label: "Per capita defined" },
    },
    {
      id: "generation",
      name: "Per capita at each generation",
      short: "Each generation",
      family: "heads",
      icon: "Users",
      what: "Each living child takes an equal share. The shares of children who died first go into one pot that is split equally among all of their children.",
      bestFor: ["Families where two or more children could die before you", "Grandparents who want every orphaned grandchild treated the same"],
      watchOut: ["Few beneficiary forms offer it, so it usually needs a will or trust", "Gives the same result as per stirpes when only one child has died"],
      cells: {
        branch: { level: 2, text: "Yes, pooled with other branches" },
        equal: { level: 3, text: "Equal among cousins" },
        clear: { level: 2, text: "Clear if the document defines it" },
        forms: { level: 0, text: "Rarely on forms" },
        later: { level: 3, text: "Yes" },
        upkeep: { level: 0, text: "Rarely needs changes" },
      },
      map: { x: 44, y: 24 },
    },
    {
      id: "lapse",
      name: "Let the share lapse",
      short: "Lapse",
      family: "pool",
      icon: "Coins",
      what: "If a beneficiary dies first, their gift fails and goes back into the pool for the others. In our family, Ann and Cara would split Ben's share.",
      bestFor: ["Gifts to friends, siblings or a charity, where you do not want the gift passing to that person's heirs", "Account forms where the other named people should simply share"],
      watchOut: ["Illinois and many other states have an anti-lapse rule that passes a will gift for a child who died first to that child's descendants unless your will says otherwise", "Many 401(k) and IRA forms lapse by default, which can cut out grandchildren without anyone choosing it"],
      cells: {
        branch: { level: 0, text: "No, Ben's kids get $0" },
        equal: { level: 2, text: "Survivors share equally" },
        clear: { level: 2, text: "Clear, but state law may override" },
        forms: { level: 3, text: "Often the form's default" },
        later: { level: 0, text: "No" },
        upkeep: { level: 1, text: "Low" },
      },
      map: { x: 92, y: 42 },
      learn: { href: "/learn/beneficiary-designations/contingent-beneficiaries", label: "Contingent beneficiaries explained" },
    },
    {
      id: "named",
      name: "Name each backup by name",
      short: "Named backups",
      family: "names",
      icon: "UserCheck",
      what: "You list a specific contingent beneficiary for each share, such as \"if Ben dies first, to his children Dan and Eve in equal shares.\"",
      bestFor: ["Beneficiary forms with no per stirpes box", "Leaving a share to someone outside the bloodline, such as a stepchild or a child's partner", "Families that are complete and unlikely to change"],
      watchOut: ["A grandchild born after you sign is left out until you update the form", "More forms to keep current after every birth, death or divorce"],
      cells: {
        branch: { level: 3, text: "Yes, if you name the kids" },
        equal: { level: 2, text: "Whatever split you write" },
        clear: { level: 3, text: "Very clear" },
        forms: { level: 3, text: "Works on almost every form" },
        later: { level: 0, text: "No, update needed" },
        upkeep: { level: 3, text: "Update after each change" },
      },
      map: { x: 26, y: 88 },
      learn: { href: "/learn/beneficiary-designations/retirement-account-beneficiaries", label: "Retirement account beneficiaries" },
    },
  ],
  map: {
    title: "The family branch map",
    lead: "Options on the left keep each child's share in that child's family. Moving right, the money is split equally among whoever is alive. Options higher up need more updating as your family grows.",
    x: { low: "Keeps each branch's share", high: "Simple and equal per head" },
    y: { low: "Adjusts on its own", high: "Needs updating by hand" },
  },
  questions: [
    {
      id: "share",
      prompt: "If one of your children dies before you, who should get that child's share?",
      help: "Think of Ben, who dies first and leaves two children.",
      choices: [
        { id: "kids", label: "That child's own children", weights: { stirpes: 3, generation: 2, named: 2, capita: -2, lapse: -3 }, reason: "You want a child's share to pass to that child's own children" },
        { id: "siblings", label: "My other living children", weights: { capita: 3, lapse: 3, stirpes: -2, generation: -2 }, reason: "You want your living children to split a share left by a child who died first" },
        { id: "all", label: "All my grandchildren whose parent has died, equally", weights: { generation: 4, stirpes: 1 }, reason: "You want grandchildren who lost a parent treated the same as each other" },
      ],
    },
    {
      id: "uneven",
      prompt: "Your children have different numbers of kids. If two children died first, how should their kids be treated?",
      help: "Say Ben (two kids) and Cara (one kid) both die before you.",
      choices: [
        { id: "family", label: "Each family keeps its parent's share", detail: "Cara's only child gets $100,000. Ben's two get $50,000 each.", weights: { stirpes: 3, named: 1 }, reason: "You want each family to keep its parent's share, however many children it has" },
        { id: "cousins", label: "All three cousins get the same", detail: "About $66,667 each, after Ann takes $100,000.", weights: { generation: 4, stirpes: -1 }, reason: "You want cousins who lost a parent to get equal amounts" },
        { id: "unsure", label: "I have not thought about it", weights: { stirpes: 1 } },
      ],
    },
    {
      id: "doc",
      prompt: "Where are you making this choice?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "will", label: "A will or a trust", weights: { stirpes: 1, generation: 2, capita: 1 }, reason: "A will or trust can spell out any method in plain words" },
        { id: "retire", label: "A 401(k), 403(b) or IRA beneficiary form", detail: "These forms control the account, not your will.", weights: { named: 2, stirpes: 1, lapse: 1, generation: -1 }, reason: "Retirement forms often have no per stirpes box, so naming backups works on almost any form" },
        { id: "insurance", label: "A life insurance beneficiary form", weights: { named: 2, stirpes: 1 }, reason: "Insurance forms are easiest to complete when each backup is named" },
      ],
    },
    {
      id: "future",
      prompt: "Do you expect more grandchildren?",
      choices: [
        { id: "yes", label: "Yes, or possibly", weights: { stirpes: 2, generation: 2, named: -2 }, reason: "Your family is still growing, so the plan should include new grandchildren on its own" },
        { id: "no", label: "No, the family is complete", weights: { named: 3 }, reason: "Your family is complete, so naming each backup is practical" },
      ],
    },
    {
      id: "who",
      prompt: "Who else is in this plan?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "outside", label: "Someone outside the bloodline, such as a stepchild or a child's partner", weights: { named: 4 }, reason: "You want to include people a per stirpes clause would leave out" },
        { id: "friends", label: "Friends, siblings or a charity", weights: { lapse: 3, named: 1 }, reason: "You leave gifts to friends, siblings or a charity, where a gift often should fall back to the others" },
        { id: "descendants", label: "Only my children and grandchildren", weights: { stirpes: 1, generation: 1 } },
      ],
    },
    {
      id: "style",
      prompt: "How hands-on do you want to be?",
      choices: [
        { id: "auto", label: "Set it once and let it adjust", weights: { stirpes: 2, generation: 1, lapse: 1, named: -2 }, reason: "You want a rule that adjusts on its own as your family changes" },
        { id: "simple", label: "Keep it simple: equal shares for whoever is alive", weights: { capita: 3, lapse: 1 }, reason: "You want a simple equal split among whoever is alive" },
        { id: "review", label: "I review my forms every year or two", weights: { named: 2 }, reason: "You review your forms often, so named backups will stay current" },
      ],
    },
  ],
  resultNote: "Whatever you pick, write it the same way in your will, your trust and every beneficiary form. A mismatch is the most common way grandchildren get left out.",
  shortcuts: [
    { when: "You want a grandchild to step into the place of a parent who died", pick: "stirpes" },
    { when: "Two or more of your children could die before you and you want their children treated alike", pick: "generation" },
    { when: "Your 401(k) or IRA form has no per stirpes box", pick: "named" },
    { when: "You want to include a stepchild or a child's partner as a backup", pick: "named" },
    { when: "The gift is to a friend or sibling and should not pass to their heirs", pick: "lapse" },
    { when: "You truly want only your living children to share, and the document defines per capita that way", pick: "capita" },
  ],
  widgets: ["inheritance-tree"],
  diagrams: ["IntestacyLadder", "BeneficiaryBeatsWill"],
  howTo: {
    name: "How to choose between per stirpes and per capita",
    steps: [
      { name: "Draw your family tree", text: "List each child and each grandchild. Mark anyone under 18 and anyone who gets disability benefits." },
      { name: "Run the numbers for one death", text: "Pretend one child dies before you. Write down what each person gets under per stirpes and under per capita." },
      { name: "Collect every document and form", text: "Gather your will, any trust, and the beneficiary forms for each 401(k), IRA, life insurance policy and payable-on-death account." },
      { name: "Use the same rule everywhere", text: "Check the per stirpes box where a form has one. Where it does not, name each backup by name or ask the plan for its own form." },
      { name: "Plan for minor grandchildren", text: "A child under 18 cannot take money directly. Name a custodian or have the share held in a trust." },
      { name: "Review after births and deaths", text: "Look again whenever a grandchild is born or a family member dies, divorces or marries." },
    ],
  },
  faqs: [
    { q: "What is per stirpes?", a: "Per stirpes is Latin for \"by branch.\" Each of your children's shares stays with that child's family. If a child dies before you, that child's own children split the share their parent would have received." },
    { q: "What is the difference between per stirpes and per capita?", a: "Per stirpes divides by family branch, so a child who died first is replaced by their children. Per capita divides by head among the people alive at a given level. With three children, $300,000 and a son who died first, per stirpes gives his two kids $50,000 each. The common per capita reading gives them nothing and splits $150,000 each between your two living children." },
    { q: "Per stirpes vs. per capita: which should I choose?", a: "Choose per stirpes if you want grandchildren to take their parent's place. Choose per capita only if you truly want your living children to share and you are sure how your document defines it. If two or more children could die first and you want their kids treated equally, ask about per capita at each generation." },
    { q: "Do grandchildren inherit if a parent dies before me?", a: "It depends on the document. In Illinois, if you die without a will, your descendants inherit per stirpes, so grandchildren take their parent's place. Illinois also has an anti-lapse rule that generally sends a will gift for a child who died first to that child's descendants. A beneficiary form follows its own terms, and many simply pay the other named people." },
    { q: "What happens if one of several beneficiaries dies before me?", a: "On many 401(k), IRA and insurance forms, the share of a primary beneficiary who died first is split among the other primary beneficiaries. That is a lapse, and it cuts out the dead person's children. To prevent it, check a per stirpes box if the form has one, or name contingent beneficiaries." },
    { q: "Can I name a grandchild as a contingent beneficiary?", a: "Yes. You can name grandchildren as backups on almost any beneficiary form. If a grandchild is under 18, name a custodian or a trust to receive the money, or the account company may require a court-appointed guardian before it pays." },
    { q: "What is per capita in a will?", a: "It means equal shares per head, but documents disagree on whose heads count. Some count only your living children. Others count every living descendant, which would give Ann, Cara and three grandchildren $60,000 each. Your will should spell out the method instead of relying on the label." },
    { q: "Does per stirpes include stepchildren?", a: "Usually not. Per stirpes passes a share to a person's descendants by birth or adoption. A stepchild who was never adopted is not included unless you name them. If a stepchild should share, name them on the form or in your will." },
  ],
  related: [
    { href: "/learn/beneficiary-designations/contingent-beneficiaries", label: "Contingent beneficiaries explained" },
    { href: "/learn/beneficiary-designations/retirement-account-beneficiaries", label: "Naming beneficiaries on retirement accounts" },
    { href: "/learn/wills/dying-without-a-will", label: "Who inherits if you die without a will" },
    { href: "/decide/leaving-money-to-minor-children", label: "Leaving money to minor children" },
    { href: "/decide/estate-planning-for-second-marriages", label: "Estate planning in a second marriage" },
  ],
};
