import type { DecisionGuide } from "./types";

export const TYPES_OF_POA: DecisionGuide = {
  slug: "types-of-power-of-attorney",
  title: "Types of power of attorney: which one should you pick?",
  h1: "Types of power of attorney, and which one fits you",
  description:
    "Durable, general, limited, springing and healthcare powers of attorney compared on one page. Answer six questions to see which one fits you or a parent.",
  kicker: "Power of attorney decision guide",
  art: "HeroPowersOfAttorney",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "There are six common documents. A durable financial power of attorney lets an agent handle your money and keeps working if you lose capacity, so most adults start there. A healthcare power of attorney covers medical decisions, and a HIPAA authorization lets your agent see records. General, limited and springing versions suit short-term, single-task or delayed needs. Every power of attorney ends at death.",
  takeaways: [
    "Money and medical choices are usually separate documents. Most adults sign a durable financial power of attorney and a healthcare power of attorney.",
    "Durable means it keeps working if you lose capacity. That is the moment most families need it.",
    "Every power of attorney ends at death. After that, your will or trust and your executor or trustee take over.",
    "A limited power of attorney fits one task, such as a home closing you cannot attend.",
    "You must have capacity when you sign. If a parent may already lack it, a court process may be the only route.",
  ],
  noun: "power of attorney",
  families: [
    { id: "ongoing", name: "Money, for the long run", text: "An agent can manage your finances, and the document keeps working if you lose capacity.", tone: "accent" },
    { id: "short", name: "Money, for a task or a while", text: "Help with one deal or a set period, while you can still keep an eye on things.", tone: "gold" },
    { id: "health", name: "Health care", text: "Someone to make medical decisions and talk with your doctors when you cannot.", tone: "sage" },
  ],
  dimensions: [
    { id: "scope", label: "What the agent can do", help: "How much the document lets your agent handle." },
    { id: "incapacity", label: "Works if you lose capacity", help: "Does it keep working if you can no longer decide for yourself?" },
    { id: "start", label: "Ready the day you sign", help: "Can your agent act right away, without proof of incapacity?" },
    { id: "death", label: "Works after death", help: "None of them do. Your will, trust and executor take over at death." },
    { id: "accept", label: "Easy for others to accept", help: "How readily banks, title companies or hospitals tend to rely on it." },
    { id: "effort", label: "Setup and formalities", help: "Relative cost and signing rules, which vary by state. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "durable",
      name: "Durable financial power of attorney",
      short: "Durable",
      family: "ongoing",
      icon: "Landmark",
      what: "A document that names an agent to handle your money and property, and keeps working if you lose the ability to manage your own affairs.",
      bestFor: ["Almost every adult, as the base of an incapacity plan", "Older adults and anyone planning for a parent", "Couples, since a spouse does not get automatic authority"],
      watchOut: ["Your agent can misuse broad powers, so choose with care", "Some banks push back on older or unfamiliar forms"],
      cells: {
        scope: { level: 3, text: "Broad money and property powers" },
        incapacity: { level: 3, text: "Yes, built for it" },
        start: { level: 3, text: "Usually, unless springing" },
        death: { level: 0, text: "No, ends at death" },
        accept: { level: 2, text: "Usually, some banks resist" },
        effort: { level: 2, text: "Notary, sometimes witnesses" },
      },
      map: { x: 12, y: 82 },
      learn: { href: "/learn/power-of-attorney/durable-financial-power-of-attorney", label: "Durable financial power of attorney" },
    },
    {
      id: "springing",
      name: "Springing power of attorney",
      short: "Springing",
      family: "ongoing",
      icon: "CalendarClock",
      what: "A durable financial power of attorney that only takes effect after a set trigger, usually a doctor's written finding that you cannot manage.",
      bestFor: ["People uneasy giving anyone power before it is needed", "People with no close family they fully trust yet"],
      watchOut: ["Proving the trigger can delay your agent when speed matters", "Some states restrict springing powers or treat them with caution"],
      cells: {
        scope: { level: 3, text: "Broad money and property powers" },
        incapacity: { level: 3, text: "Yes, it starts then" },
        start: { level: 0, text: "No, needs proof first" },
        death: { level: 0, text: "No, ends at death" },
        accept: { level: 1, text: "Often questioned" },
        effort: { level: 2, text: "Moderate, plus proof later" },
      },
      map: { x: 30, y: 62 },
      learn: { href: "/learn/power-of-attorney/springing-vs-immediate-power-of-attorney", label: "Springing vs immediate power of attorney" },
    },
    {
      id: "general",
      name: "General (non-durable) power of attorney",
      short: "General",
      family: "short",
      icon: "Briefcase",
      what: "A document that gives an agent broad power over your finances, but ends if you lose capacity.",
      bestFor: ["Someone away for a while, such as travel or deployment", "People who want help now and can still oversee the agent"],
      watchOut: ["It stops working when you lose capacity, when help is often needed most", "In many states a new power of attorney is durable unless it says otherwise"],
      cells: {
        scope: { level: 3, text: "Broad money and property powers" },
        incapacity: { level: 0, text: "No, ends at incapacity" },
        start: { level: 3, text: "Yes, at signing" },
        death: { level: 0, text: "No, ends at death" },
        accept: { level: 2, text: "Yes, while you can act" },
        effort: { level: 1, text: "Low, often notarized" },
      },
      map: { x: 32, y: 30 },
      learn: { href: "/learn/power-of-attorney/when-does-power-of-attorney-end", label: "When a power of attorney ends" },
    },
    {
      id: "limited",
      name: "Limited or special power of attorney",
      short: "Limited",
      family: "short",
      icon: "FileSignature",
      what: "A document that lets an agent do one thing or a short list of things, such as sign at a home closing or sell a car.",
      bestFor: ["A home closing or sale you cannot attend", "One account, one vehicle or one tax matter"],
      watchOut: ["Your agent cannot act outside the listed task", "Real estate forms may need to be recorded with the county"],
      cells: {
        scope: { level: 1, text: "One task or account" },
        incapacity: { level: 1, text: "Only if it says durable" },
        start: { level: 3, text: "Yes, for the set task" },
        death: { level: 0, text: "No, ends at death" },
        accept: { level: 3, text: "Easy, the task is clear" },
        effort: { level: 1, text: "Low" },
      },
      map: { x: 12, y: 12 },
      learn: { href: "/learn/power-of-attorney", label: "Powers of attorney explained" },
    },
    {
      id: "healthcare",
      name: "Healthcare (medical) power of attorney",
      short: "Healthcare",
      family: "health",
      icon: "Stethoscope",
      what: "A document that names an agent to make medical decisions for you when you cannot make or share them yourself.",
      bestFor: ["Every adult, including children who just turned 18", "Anyone facing surgery, a diagnosis or older age"],
      watchOut: ["It does not cover money, so pair it with a financial one", "Talk through your wishes, or your agent may be guessing"],
      cells: {
        scope: { level: 2, text: "Medical decisions only" },
        incapacity: { level: 3, text: "Yes, built for it" },
        start: { level: 1, text: "Often when you cannot decide" },
        death: { level: 0, text: "Mostly no, rules vary" },
        accept: { level: 2, text: "Hospitals expect one" },
        effort: { level: 1, text: "Low, often a state form" },
      },
      map: { x: 84, y: 84 },
      learn: { href: "/learn/healthcare-directives/healthcare-power-of-attorney", label: "Healthcare power of attorney explained" },
    },
    {
      id: "hipaa",
      name: "HIPAA authorization (companion form)",
      short: "HIPAA",
      family: "health",
      icon: "Lock",
      what: "A signed form that lets doctors, hospitals and insurers share your health information with the people you name. It does not let them decide anything.",
      bestFor: ["Family who need to talk with doctors or insurers", "Agents under a springing power who must prove incapacity", "Parents of a child who just turned 18"],
      watchOut: ["Grants access to information only, not decision power", "Check the expiration date when you review your plan"],
      cells: {
        scope: { level: 1, text: "Health records access only" },
        incapacity: { level: 3, text: "Yes, until it expires" },
        start: { level: 3, text: "Yes, at signing" },
        death: { level: 0, text: "No, executor steps in" },
        accept: { level: 2, text: "Providers know the form" },
        effort: { level: 0, text: "Very low, short form" },
      },
      map: { x: 66, y: 44 },
      learn: { href: "/learn/healthcare-directives/hipaa-authorization", label: "HIPAA authorizations explained" },
    },
  ],
  map: {
    title: "The power of attorney map",
    lead: "Money documents sit on the left and health documents on the right. Higher up, the document is built to keep working if you lose capacity. All of them end at death.",
    x: { low: "Money and property", high: "Health care" },
    y: { low: "One task or a short time", high: "Keeps working through incapacity" },
  },
  questions: [
    {
      id: "area",
      prompt: "What do you need help with?",
      choices: [
        { id: "money", label: "Money, bills and property", weights: { durable: 3, general: 1, limited: 1, springing: 1, healthcare: -2, hipaa: -1 }, reason: "You need someone who can handle money and property" },
        { id: "medical", label: "Medical decisions", weights: { healthcare: 4, hipaa: 3, durable: -2 }, reason: "You want someone to make or support medical decisions" },
        { id: "both", label: "Both", weights: { durable: 3, healthcare: 3, hipaa: 2 }, reason: "You want cover for both money and medical decisions" },
      ],
    },
    {
      id: "scope",
      prompt: "How long or how wide should it reach?",
      choices: [
        { id: "task", label: "One task, like a closing or a car sale", weights: { limited: 5, general: 1, durable: -1 }, reason: "You need help with one task" },
        { id: "period", label: "Broad help for a set period", detail: "For example, while you travel or are deployed.", weights: { general: 4, limited: 2 }, reason: "You need broad help for a set period" },
        { id: "ongoing", label: "Ongoing, for the rest of my life", weights: { durable: 3, springing: 1, healthcare: 1 }, reason: "You want ongoing help, not a single task" },
        { id: "medical", label: "This is only about medical care", weights: { healthcare: 2, hipaa: 1 }, reason: "Your focus is medical care" },
      ],
    },
    {
      id: "incapacity",
      prompt: "Should it keep working if you can no longer make decisions?",
      choices: [
        { id: "yes", label: "Yes", weights: { durable: 3, springing: 2, healthcare: 2, general: -3 }, reason: "You want it to keep working if you lose capacity" },
        { id: "no", label: "No, only while I can oversee things", weights: { general: 3, limited: 2, durable: -1 }, reason: "You only need it while you can still oversee your agent" },
        { id: "unsure", label: "Not sure", weights: { durable: 1, healthcare: 1 } },
      ],
    },
    {
      id: "start",
      prompt: "When should your agent be able to act?",
      choices: [
        { id: "now", label: "Right away", weights: { durable: 2, general: 1, limited: 1, springing: -2 }, reason: "You want your agent able to act right away" },
        { id: "later", label: "Only after a doctor says I cannot decide", weights: { springing: 5 }, reason: "You want it to start only after a doctor's finding" },
        { id: "unsure", label: "Not sure", weights: { durable: 1 } },
      ],
    },
    {
      id: "memory",
      prompt: "Is the person signing having memory or thinking problems?",
      help: "The signer must understand the document at the moment they sign. Rules vary by state.",
      choices: [
        { id: "clear", label: "No, they are thinking clearly", weights: { durable: 1, healthcare: 1 } },
        { id: "early", label: "Some early changes, but they still understand", weights: { durable: 3, healthcare: 3, hipaa: 2, springing: -2 }, reason: "A diagnosis does not always end the ability to sign, so acting soon matters" },
        { id: "lost", label: "They may no longer understand what they sign", detail: "See the note with your result about guardianship.", weights: {} },
      ],
    },
    {
      id: "extras",
      prompt: "What else is going on?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "sale", label: "A one-time deal, like selling a house or car", weights: { limited: 4 }, reason: "You have a single deal someone must sign for" },
        { id: "away", label: "I will be away or deployed for a while", weights: { general: 3, limited: 1, durable: 1 }, reason: "You will be away and need someone to handle things" },
        { id: "hospital", label: "Surgery or a hospital stay is coming up", weights: { healthcare: 3, hipaa: 3, durable: 1 }, reason: "You have surgery or a hospital stay coming up" },
        { id: "records", label: "Family needs to talk with doctors or insurers", weights: { hipaa: 4 }, reason: "You want family to be able to talk with your doctors" },
        { id: "wary", label: "I am uneasy giving power before I need help", weights: { springing: 3, durable: -1 }, reason: "You are uneasy giving power before it is needed" },
        { id: "aging", label: "I am planning ahead for older age", weights: { durable: 3, healthcare: 2, hipaa: 1 }, reason: "You are planning ahead for older age" },
        { id: "eighteen", label: "My child just turned 18", weights: { healthcare: 2, hipaa: 3, durable: 2 }, reason: "Parents lose automatic access once a child turns 18" },
      ],
    },
  ],
  resultNote:
    "Most adults sign a durable financial power of attorney, a healthcare power of attorney and a HIPAA authorization together. If the person may already lack capacity, a power of attorney may not be possible. Our power of attorney vs guardianship guide, linked below, explains that route.",
  shortcuts: [
    { when: "You want a plan if you can no longer manage money", pick: "durable" },
    { when: "You want someone to make medical decisions if you cannot", pick: "healthcare" },
    { when: "You cannot attend a home closing or sale", pick: "limited" },
    { when: "You will be away for months and can still check in", pick: "general" },
    { when: "You only want it to start after a doctor's finding", pick: "springing" },
    { when: "Your family needs to talk with your doctors or insurers", pick: "hipaa" },
    { when: "A parent has early memory loss but still understands", pick: "durable" },
    { when: "Your child just turned 18", pick: "healthcare" },
  ],
  diagrams: ["PoaHealthcareRoles", "ExecutorTrusteeAgent"],
  howTo: {
    name: "How to choose the right type of power of attorney",
    steps: [
      { name: "Separate money from medical", text: "Decide who should handle your finances and who should make medical decisions. It can be the same person or two people." },
      { name: "Decide how long it should last", text: "For one task, a limited power fits. For lasting help, choose a durable power so it keeps working if you lose capacity." },
      { name: "Choose when it starts", text: "An immediate power works at signing. A springing power waits for a doctor's finding, which can slow your agent down." },
      { name: "Pick your agents and backups", text: "Name someone honest and organized, plus at least one successor. Talk with them before you sign." },
      { name: "Sign the way your state requires", text: "Many states require a notary, witnesses or both, and rules vary by state. Real estate use may need recording." },
      { name: "Share copies and add a HIPAA form", text: "Give copies to your agent, bank and doctors. Add a HIPAA authorization so your agent can see medical records." },
    ],
  },
  faqs: [
    { q: "What are the main types of power of attorney?", a: "The main types are durable, general, limited and springing powers of attorney for money, plus a healthcare power of attorney for medical decisions. A durable power keeps working if you lose capacity. A general one ends at incapacity. A limited one covers a single task. A springing one starts only after a set trigger." },
    { q: "Which power of attorney is best for an elderly parent?", a: "For most older adults, the usual pair is a durable financial power of attorney and a healthcare power of attorney, plus a HIPAA authorization. Your parent must still understand what they are signing. If they may not, ask an attorney to assess capacity, or look at guardianship as the fallback." },
    { q: "Does a power of attorney end at death?", a: "Yes. Every power of attorney ends when the person who signed it dies. The agent can no longer pay bills or access accounts. After death, the executor named in the will, or the trustee of a living trust, takes over, along with any beneficiary forms." },
    { q: "What is the difference between a durable and a general power of attorney?", a: "Both can give broad power over your finances. A durable power of attorney keeps working if you lose capacity. A general, non-durable one ends at that point. In many states a new power of attorney is durable unless it says otherwise, but rules vary by state." },
    { q: "Can a power of attorney be used for medical decisions?", a: "Only a healthcare power of attorney covers medical decisions. A financial power of attorney does not. Some states call it a healthcare proxy or combine it with a living will in one advance directive. A HIPAA authorization is a separate form that lets your agent see your medical records." },
    { q: "Is a springing power of attorney a good idea?", a: "It can suit someone who does not want an agent to act early. The tradeoff is delay. Your agent must prove the trigger, often with a doctor's letter, before banks will act. Many people instead sign an immediate durable power and hold the original until it is needed." },
    { q: "What happens if there is no power of attorney and a person loses capacity?", a: "Family members usually cannot sign for them, even a spouse in many cases. Someone may need to ask a court to appoint a guardian or conservator. That process is public, slower and more costly than a power of attorney, and the court may require ongoing reports." },
    { q: "Do I need a lawyer to make a power of attorney?", a: "Not always. Many states offer statutory forms. Still, a lawyer can tailor powers such as gifting or trust funding, check your state's signing rules and help avoid forms that banks question. Help matters most when there are family tensions, a business or doubts about capacity." },
  ],
  related: [
    { href: "/learn/power-of-attorney", label: "Powers of attorney explained" },
    { href: "/learn/power-of-attorney/power-of-attorney-vs-guardianship", label: "Power of attorney vs guardianship" },
    { href: "/compare/living-will-vs-healthcare-power-of-attorney", label: "Living will vs healthcare power of attorney" },
    { href: "/learn/power-of-attorney/choosing-a-power-of-attorney-agent", label: "How to choose your agent" },
    { href: "/learn/power-of-attorney/bank-refuses-power-of-attorney", label: "When a bank refuses a power of attorney" },
    { href: "/decide/types-of-trusts", label: "Types of trusts: which one fits you" },
  ],
};
