import type { DecisionGuide } from "./types";

/** Illinois small estate affidavit limit for personal property. Confirm the current figure before launch. */
const IL_SMALL_ESTATE = "$150,000";

export const TYPES_OF_PROBATE: DecisionGuide = {
  slug: "types-of-probate",
  title: "Types of probate in Illinois: 7 paths an estate can take",
  h1: "Types of probate, and which one your family's estate needs",
  description: `No probate, a small estate affidavit, independent or supervised administration, ancillary probate or trust administration. Answer six questions to see which fits.`,
  kicker: "Probate decision guide",
  art: "HeroProbate",
  tone: "gold",
  updated: "2026-10-06",
  reviewed: false,
  answer: `Most Illinois estates take one of four paths. If everything passed by beneficiary form, joint ownership or a living trust, no probate is needed. If the person left ${IL_SMALL_ESTATE} or less in personal property and no real estate, a small estate affidavit usually works. Otherwise the family opens a court case, usually independent administration, with supervised administration for disputes or vulnerable heirs. Property in another state adds ancillary probate there.`,
  takeaways: [
    "Probate only covers what the person owned in their name alone with no beneficiary. Start by sorting assets into those two piles.",
    `In Illinois, a small estate affidavit can collect up to ${IL_SMALL_ESTATE} of personal property with no court case, but it cannot transfer real estate.`,
    "A house in the person's name alone usually means opening a case in the circuit court of the county where they lived.",
    "Independent administration is the usual Illinois route. The executor acts without asking the judge before each step.",
    "In Illinois, the original will must be filed with the circuit clerk within 30 days of learning of the death, even if no case is opened.",
  ],
  noun: "probate path",
  families: [
    { id: "nocourt", name: "No court", text: "Assets pass by form, title or trust, and nobody files a probate case.", tone: "sage" },
    { id: "light", name: "Light court", text: "A short filing or an open case where the executor mostly works alone.", tone: "gold" },
    { id: "full", name: "Full court", text: "A judge reviews the major steps, or a second case is needed in another state.", tone: "clay" },
  ],
  dimensions: [
    { id: "court", label: "Court involvement", help: "How often a judge or clerk is part of the process. More dots means more court.", inverse: true },
    { id: "time", label: "Typical time", help: "How long it usually takes to finish. More dots means longer.", inverse: true },
    { id: "cost", label: "Typical cost", help: "Filing fees, publication, bond and lawyer time. More dots means more cost.", inverse: true },
    { id: "realestate", label: "Can transfer real estate", help: "Can this path pass a house or land to the heirs?" },
    { id: "size", label: "Works for larger estates", help: "Is there a dollar cap on the estate that can use it?" },
    { id: "workload", label: "Executor workload", help: "Paperwork, notices and reports for the person in charge. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "none",
      name: "No probate needed",
      short: "No probate",
      family: "nocourt",
      icon: "Check",
      what: "Every asset passes outside the will, through a beneficiary form, a payable-on-death or transfer-on-death account, joint ownership with survivorship or a recorded transfer on death instrument.",
      bestFor: ["Estates where every account names a living beneficiary", "A house held in joint tenancy with a surviving spouse", "A house with an Illinois transfer on death instrument recorded before death"],
      watchOut: ["One forgotten account in the person's name alone can still need an affidavit or a case", "The original will must still be filed with the circuit clerk in Illinois"],
      cells: {
        court: { level: 0, text: "None, just death certificates" },
        time: { level: 0, text: "Weeks, one form at a time" },
        cost: { level: 0, text: "Little or nothing" },
        realestate: { level: 3, text: "Yes, by joint title or TODI" },
        size: { level: 3, text: "No cap" },
        workload: { level: 0, text: "Light, mostly phone calls" },
      },
      map: { x: 6, y: 64 },
      learn: { href: "/learn/probate/probate-vs-non-probate-assets", label: "Probate vs non-probate assets" },
    },
    {
      id: "trust",
      name: "Trust administration",
      short: "Trust admin",
      family: "nocourt",
      icon: "Landmark",
      what: "The successor trustee of a funded living trust collects, manages and hands out the trust's assets under the trust's terms, with no probate case.",
      bestFor: ["Estates where the house and main accounts were deeded or retitled to a living trust", "Families who want privacy and no court calendar", "Property in more than one state held in the same trust"],
      watchOut: ["Only covers what was actually put into the trust", "The trustee still owes duties: notice to beneficiaries, records, taxes and fair dealing"],
      cells: {
        court: { level: 0, text: "None unless someone sues" },
        time: { level: 1, text: "Often a few months" },
        cost: { level: 1, text: "Trustee time and some legal help" },
        realestate: { level: 3, text: "Yes, trustee signs the deed" },
        size: { level: 3, text: "No cap" },
        workload: { level: 2, text: "Real work, but on your schedule" },
      },
      map: { x: 14, y: 90 },
      learn: { href: "/learn/trusts/revocable-living-trust", label: "Revocable living trusts explained" },
    },
    {
      id: "affidavit",
      name: "Illinois small estate affidavit",
      short: "Small estate",
      family: "light",
      icon: "FileSignature",
      what: `A sworn form an heir signs and hands to banks and other holders to collect personal property, when the Illinois probate estate is ${IL_SMALL_ESTATE} or less and includes no real estate.`,
      bestFor: [`Estates with ${IL_SMALL_ESTATE} or less in sole-name accounts and belongings`, "Families where the house already passed by joint title or a trust", "Heirs who agree on who gets what"],
      watchOut: ["Cannot transfer real estate in Illinois", "The person who signs is personally on the hook if the facts are wrong or a debt goes unpaid", "Check the current limit before relying on it, since the legislature changes it"],
      cells: {
        court: { level: 0, text: "No case; will still filed" },
        time: { level: 0, text: "Weeks" },
        cost: { level: 0, text: "Low" },
        realestate: { level: 0, text: "No" },
        size: { level: 1, text: `Up to ${IL_SMALL_ESTATE}, no real estate` },
        workload: { level: 1, text: "One detailed form, then follow-up" },
      },
      map: { x: 24, y: 8 },
      learn: { href: "/learn/probate/small-estate-affidavit", label: "Small estate procedures explained" },
    },
    {
      id: "summary",
      name: "Summary administration",
      short: "Summary",
      family: "light",
      icon: "ClipboardList",
      what: "A shortened Illinois court case for small estates, used when every heir and beneficiary agrees in writing and the debts and taxes are paid or covered.",
      bestFor: ["Small estates that do not fit the affidavit, such as one that includes a modest piece of real estate", "Families where every heir agrees and signs"],
      watchOut: ["Less common, and the dollar limit is lower than many expect, so check the current limit", "Heirs who take property can stay liable for claims that surface later"],
      cells: {
        court: { level: 1, text: "One short case" },
        time: { level: 1, text: "Shorter than a full case" },
        cost: { level: 1, text: "Filing fee and some legal help" },
        realestate: { level: 2, text: "Can, within the limit" },
        size: { level: 1, text: "Small estates only" },
        workload: { level: 1, text: "Light once heirs sign" },
      },
      map: { x: 44, y: 26 },
      learn: { href: "/learn/probate/how-to-file-probate", label: "How to file probate, step by step" },
    },
    {
      id: "independent",
      name: "Independent administration",
      short: "Independent",
      family: "light",
      icon: "Gavel",
      what: "The usual Illinois probate case. The court appoints the executor, then the executor sells property, pays debts and distributes assets without asking the judge before each step.",
      bestFor: ["A house in the person's name alone, with heirs who get along", "Estates over the affidavit limit", "Executors who want a clear process without monthly court dates"],
      watchOut: ["The creditor claim period runs at least six months from the first published notice, so plan on most of a year", "Any heir can ask the court to switch to supervised administration"],
      cells: {
        court: { level: 2, text: "Opened, then hands-off" },
        time: { level: 2, text: "Often 6 to 12 months" },
        cost: { level: 2, text: "Fees, publication, lawyer time" },
        realestate: { level: 3, text: "Yes" },
        size: { level: 3, text: "No cap" },
        workload: { level: 2, text: "Inventory, notices, final report" },
      },
      map: { x: 64, y: 78 },
      learn: { href: "/learn/probate/what-is-probate", label: "What probate is and how it works" },
    },
    {
      id: "supervised",
      name: "Supervised administration",
      short: "Supervised",
      family: "full",
      icon: "Scale",
      what: "A probate case where the judge approves major steps, such as selling property, paying fees and making distributions, and reviews accountings along the way.",
      bestFor: ["Families in open disagreement or a will contest", "Estates with a minor or a disabled heir who needs protecting", "Executors who want a court order behind each big decision"],
      watchOut: ["The slowest and costliest path", "Every major step waits on a court date"],
      cells: {
        court: { level: 3, text: "Judge approves major steps" },
        time: { level: 3, text: "Often a year or more" },
        cost: { level: 3, text: "Highest, more hearings" },
        realestate: { level: 3, text: "Yes, with court approval" },
        size: { level: 3, text: "No cap" },
        workload: { level: 3, text: "Heavy, with court accountings" },
      },
      map: { x: 92, y: 84 },
      learn: { href: "/learn/probate/how-long-does-probate-take", label: "How long probate takes" },
    },
    {
      id: "ancillary",
      name: "Ancillary probate",
      short: "Ancillary",
      family: "full",
      icon: "Building2",
      what: "A second probate case in another state, needed when the person owned real estate there in their name alone. It runs alongside the main case at home.",
      bestFor: ["An Illinois resident who owned a condo in Florida or a cabin in Wisconsin in their own name", "A non-resident who owned Illinois real estate"],
      watchOut: ["Often needs a lawyer licensed in the other state", "Adds months and a second set of fees"],
      cells: {
        court: { level: 2, text: "A second case in that state" },
        time: { level: 2, text: "Adds months" },
        cost: { level: 2, text: "Second set of fees" },
        realestate: { level: 3, text: "That is its purpose" },
        size: { level: 3, text: "No cap" },
        workload: { level: 2, text: "Two courts, two sets of rules" },
      },
      map: { x: 78, y: 50 },
      learn: { href: "/learn/probate/ancillary-probate", label: "Ancillary probate explained" },
    },
  ],
  map: {
    title: "The probate path map",
    lead: "Paths on the left keep the family out of court. Moving right, a judge plays a bigger part. Paths higher up can handle larger estates and real estate.",
    x: { low: "No court", high: "Judge reviews each step" },
    y: { low: "Small estates only", high: "Any size, with real estate" },
  },
  questions: [
    {
      id: "title",
      prompt: "How did the person hold their main assets?",
      help: "Pick all that apply. Look at statements, deeds and beneficiary forms.",
      multi: true,
      choices: [
        { id: "forms", label: "Accounts with named beneficiaries, or joint with a survivor", weights: { none: 4, affidavit: 1 }, reason: "You have assets that pass by beneficiary form or joint title, outside probate" },
        { id: "trust", label: "A living trust held the house or main accounts", weights: { trust: 6, none: 1 }, reason: "You have a funded living trust, so the trustee can act without a court case" },
        { id: "sole", label: "Bank or brokerage accounts in their name alone, no beneficiary", weights: { affidavit: 2, summary: 1, independent: 1, none: -3 }, reason: "You have sole-name accounts that need some legal route to collect" },
        { id: "house", label: "An Illinois house in their name alone", weights: { independent: 4, summary: 1, supervised: 1, affidavit: -5, none: -4, trust: -2 }, reason: "You have Illinois real estate in the person's sole name, which usually needs a court case" },
        { id: "other", label: "Real estate in another state in their name alone", weights: { ancillary: 7, trust: -1 }, reason: "You have property in another state, which usually needs a second probate case there" },
      ],
    },
    {
      id: "size",
      prompt: "What is the rough value of everything in the person's name alone, with no beneficiary?",
      help: "Leave out accounts with a beneficiary, joint property and anything in a trust.",
      choices: [
        { id: "zero", label: "Nothing, or almost nothing", weights: { none: 5, trust: 2, affidavit: -2, independent: -2, supervised: -2 }, reason: "You have little or nothing left in the person's name alone" },
        { id: "small", label: `Under ${IL_SMALL_ESTATE}`, weights: { affidavit: 4, summary: 2, independent: -1 }, reason: `You have a probate estate under ${IL_SMALL_ESTATE}, which may qualify for a shortcut` },
        { id: "large", label: `More than ${IL_SMALL_ESTATE}`, weights: { independent: 3, supervised: 1, affidavit: -5, summary: -3 }, reason: "You have an estate too large for the Illinois small estate shortcuts" },
        { id: "unsure", label: "Not sure yet", weights: { independent: 1, affidavit: 1 } },
      ],
    },
    {
      id: "family",
      prompt: "How are the heirs getting along?",
      choices: [
        { id: "agree", label: "Everyone agrees on the plan", weights: { affidavit: 2, summary: 3, independent: 2, trust: 1 }, reason: "You have heirs who agree, which allows the lighter paths" },
        { id: "tension", label: "Some tension, but no lawsuits", weights: { independent: 2, supervised: 1, summary: -2 } },
        { id: "fight", label: "Open disagreement, or someone may contest the will", weights: { supervised: 6, summary: -3, affidavit: -3 }, reason: "You expect disputes, and a judge's approval at each step protects the executor" },
      ],
    },
    {
      id: "heirs",
      prompt: "Is any heir a minor, or an adult who cannot manage money because of a disability?",
      choices: [
        { id: "yes", label: "Yes", weights: { supervised: 4, trust: 1, affidavit: -1 }, reason: "You have a minor or disabled heir, and courts often want closer watch over their share" },
        { id: "no", label: "No, all heirs are capable adults", weights: { independent: 1, affidavit: 1, summary: 1 } },
      ],
    },
    {
      id: "debts",
      prompt: "What do the person's debts look like?",
      choices: [
        { id: "few", label: "Few and already known, such as a final medical bill", weights: { affidavit: 2, summary: 2, none: 1 }, reason: "You have few, known debts, so a short path is less risky" },
        { id: "unclear", label: "Unclear, or there may be creditors we do not know about", weights: { independent: 3, supervised: 1, affidavit: -2, summary: -2 }, reason: "You have uncertain debts, and a published notice cuts off late creditor claims" },
        { id: "more", label: "Debts may be more than the assets", weights: { supervised: 3, independent: 2, affidavit: -3, summary: -3 }, reason: "You may have an insolvent estate, where the court sets the order of payment" },
      ],
    },
    {
      id: "executor",
      prompt: "What does the person in charge want most?",
      choices: [
        { id: "fast", label: "The quickest, lightest route", weights: { none: 2, affidavit: 2, trust: 2, summary: 1 }, reason: "You want the fastest route with the least paperwork" },
        { id: "clear", label: "A clear process, without asking the judge at every step", weights: { independent: 3, trust: 1 }, reason: "You want authority to act without a court order for each step" },
        { id: "cover", label: "A judge's approval behind every big decision", weights: { supervised: 4 }, reason: "You want court approval as protection from second-guessing" },
      ],
    },
  ],
  resultNote:
    "Many estates use more than one path, such as a small estate affidavit for a bank account plus ancillary probate for a cabin out of state. A short consult with an Illinois probate attorney confirms which path fits and what the current limits are.",
  shortcuts: [
    { when: "Every account named a living beneficiary and the house was joint with a surviving spouse", pick: "none" },
    { when: "The house and main accounts were titled to a living trust", pick: "trust" },
    { when: `Sole-name accounts total ${IL_SMALL_ESTATE} or less and there is no real estate`, pick: "affidavit" },
    { when: "The estate is small, it includes a modest piece of real estate, and every heir agrees", pick: "summary" },
    { when: "There is an Illinois house in the person's name alone and the family gets along", pick: "independent" },
    { when: "Heirs are fighting, a will contest is likely, or a minor heir is involved", pick: "supervised" },
    { when: "The person owned a vacation home in another state in their own name", pick: "ancillary" },
  ],
  diagrams: ["ProbateTimeline", "ProbateVsTrustComparison"],
  howTo: {
    name: "How to figure out which type of probate an estate needs",
    steps: [
      { name: "File the original will", text: "In Illinois, whoever holds the original will must deliver it to the circuit clerk in the county where the person lived within 30 days of learning of the death." },
      { name: "Sort assets into two piles", text: "Put accounts with a beneficiary, joint property and trust property in one pile. Put everything in the person's name alone, with no beneficiary, in the other." },
      { name: "Total the second pile", text: `Add up the sole-name assets and note any real estate. Under ${IL_SMALL_ESTATE} with no real estate points to a small estate affidavit.` },
      { name: "Check for property in other states", text: "Look for deeds to a vacation home, timeshare or land outside Illinois. Each one in the person's own name may need ancillary probate there." },
      { name: "Weigh the family and the debts", text: "Agreement and simple debts favor the lighter paths. Disputes, unknown creditors or a minor heir point toward a full case." },
      { name: "Talk to a probate attorney before signing", text: "An affidavit carries personal liability, and a court case has deadlines. A short meeting confirms the path and the current limits." },
    ],
  },
  faqs: [
    {
      q: "What is supervised vs unsupervised probate?",
      a: "In unsupervised probate, called independent administration in Illinois, the executor sells property, pays bills and distributes assets without a court order for each step. In supervised probate, the judge approves major steps and reviews accountings. Independent administration is the usual Illinois route, and a judge can switch a case to supervised if an heir objects for good reason.",
    },
    {
      q: "What is a small estate affidavit?",
      a: `It is a sworn form that lets an heir collect a person's money and belongings without a court case. In Illinois it works for estates with ${IL_SMALL_ESTATE} or less of personal property and no real estate. The heir gives a copy to each bank or holder. The person who signs it is personally responsible if the facts are wrong or a debt is left unpaid.`,
    },
    {
      q: "Can a small estate include real estate?",
      a: "Not under the Illinois small estate affidavit. If the person owned a house or land in their name alone, the family usually needs a probate case, even when the total value is low. A house held in joint tenancy, in a living trust or under a recorded transfer on death instrument can pass without that case.",
    },
    {
      q: "What is summary probate?",
      a: "Summary probate is a shortened court case for small estates. Illinois has a version called summary administration, which works when every heir and beneficiary agrees in writing and debts and taxes are paid or covered. It is less common than the affidavit or independent administration, and its dollar limit is fairly low, so check the current limit first.",
    },
    {
      q: "How long does probate take for a small estate?",
      a: "With an Illinois small estate affidavit, families often collect accounts within weeks, depending on how fast each bank responds. A full probate case takes longer because creditors get at least six months from the first published notice to file claims. Most straightforward Illinois cases close in roughly 6 to 12 months.",
    },
    {
      q: "What if I inherit a house in another state?",
      a: "If the person who died owned the house in their name alone, the estate usually needs ancillary probate in the state where the house sits. That is a second, smaller case that runs alongside the main one. If the house was in a living trust or passed by a transfer-on-death deed, it can usually skip that second case.",
    },
    {
      q: "Does a trust go through probate after death?",
      a: "Assets titled in a living trust do not go through probate. The successor trustee handles them under the trust's terms, which is called trust administration. Anything the person forgot to move into the trust may still need probate, often through a pour-over will, unless a small estate affidavit covers it.",
    },
    {
      q: "Can I do probate myself in Illinois?",
      a: "Sometimes, but Illinois probate has strict forms, notices and deadlines, and a missed step can leave the executor personally liable. Families often handle a small estate affidavit without a lawyer, though the person who signs takes on that liability. In a full case, most executors hire a lawyer for at least the opening filings and the creditor notice.",
    },
  ],
  related: [
    { href: "/learn/probate/what-is-probate", label: "What probate is and how it works" },
    { href: "/learn/probate/how-long-does-probate-take", label: "How long probate takes" },
    { href: "/decide/ways-to-avoid-probate", label: "Ways to avoid probate, compared" },
    { href: "/decide/ways-to-hold-title-to-property", label: "Ways to hold title to property" },
    { href: "/tools/small-estate-checker", label: "Small estate checker" },
    { href: "/estate-planning/illinois", label: "Estate planning in Illinois" },
  ],
};
