import type { DecisionGuide } from "./types";

export const SECOND_MARRIAGE_OPTIONS: DecisionGuide = {
  slug: "estate-planning-for-second-marriages",
  title: "Estate planning in a second marriage: 8 options compared",
  h1: "Estate planning in a second marriage: ways to protect your spouse and your children",
  description: `Eight ways to provide for a new spouse and children from a first marriage, compared: QTIP trust, separate trusts, prenup, life insurance and more. Six questions to pick.`,
  kicker: "Blended family decision guide",
  art: "HeroBlendedFamily",
  tone: "accent",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "In a second marriage, most couples protect both sides by holding assets in trust or by splitting them on purpose. A QTIP or marital trust pays your spouse for life, then sends what is left to your children. Separate trusts, a prenup and life insurance for the children also help. Leaving everything to your spouse is simple, but your spouse can then leave it all to their own family.",
  takeaways: [
    "Leaving everything to your spouse and trusting them to pass it on is the most common way children from a first marriage get left out.",
    "A trust locks in who gets what after your spouse dies. A will your spouse inherits under does not.",
    "In Illinois, a spouse left out of a will can renounce it and take a share set by law. A signed prenup or postnup can waive that right.",
    "Your 401(k) goes to your spouse by federal law unless your spouse signs a waiver after the wedding.",
    "Life insurance can give your children money right away, so they are not waiting for a stepparent to die.",
  ],
  noun: "way to plan",
  families: [
    { id: "hold", name: "Hold it in trust for both", text: "Your spouse is supported for life, and your children inherit what is left after your spouse dies.", tone: "accent" },
    { id: "separate", name: "Keep things separate", text: "Each spouse's money goes where that spouse chose, with clear lines drawn now.", tone: "sage" },
    { id: "add", name: "Add money for the children", text: "A separate pot of money reaches your children without touching your spouse's share.", tone: "gold" },
    { id: "trust", name: "Trust your spouse to decide", text: "Everything goes to your spouse, who then decides what your children get.", tone: "clay" },
  ],
  dimensions: [
    { id: "spouse", label: "Supports your spouse", help: "Does your spouse have enough to live on after you die?" },
    { id: "kids", label: "Protects your children's share", help: "Can your spouse, or a new partner, cut your children out later?" },
    { id: "timing", label: "Children inherit at your death", help: "Do your children get something without waiting for your spouse to die?" },
    { id: "peace", label: "Keeps spouse and children apart", help: "Fewer ties between stepparent and stepchildren over money after you are gone." },
    { id: "flex", label: "Survivor can adapt", help: "Can your spouse adjust to new needs, such as a move or health costs?" },
    { id: "effort", label: "Setup cost and effort", help: "Relative cost, paperwork and ongoing work. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "qtip",
      name: "QTIP or marital trust",
      short: "QTIP trust",
      family: "hold",
      icon: "Lock",
      what: "At your death, assets go into a trust that pays your spouse income for life. When your spouse dies, the rest goes to your children, and your spouse cannot change that.",
      bestFor: ["A spouse who needs income from your assets", "Larger estates, since it can delay federal and Illinois estate tax until the second death", "Anyone who wants the final split locked in"],
      watchOut: ["Your children may wait decades if your spouse is close to their age", "The trustee sits between your spouse and your children, so pick that person carefully"],
      cells: {
        spouse: { level: 3, text: "Income for life, more if allowed" },
        kids: { level: 3, text: "Locked in at your death" },
        timing: { level: 0, text: "Wait for spouse's death" },
        peace: { level: 1, text: "Trustee balances both sides" },
        flex: { level: 1, text: "Only what the trust allows" },
        effort: { level: 3, text: "Trust, tax election, trustee" },
      },
      map: { x: 36, y: 14 },
      learn: { href: "/learn/blended-families/qtip-and-marital-trusts", label: "QTIP and marital trusts explained" },
    },
    {
      id: "separate",
      name: "Separate revocable trusts",
      short: "Separate trusts",
      family: "separate",
      icon: "Split",
      what: "Each spouse has a living trust for their own assets. Each trust says how much goes to the other spouse and how much to that spouse's own children.",
      bestFor: ["Spouses who each brought savings or a home into the marriage", "Couples who want clear lines between \"yours\" and \"mine\""],
      watchOut: ["Only works if each trust is funded and joint accounts are sorted out", "Your spouse can change their own trust at any time"],
      cells: {
        spouse: { level: 2, text: "What you choose to leave" },
        kids: { level: 3, text: "Your trust, your terms" },
        timing: { level: 2, text: "Can pay children at your death" },
        peace: { level: 2, text: "Clear lines, fewer ties" },
        flex: { level: 2, text: "Each spouse controls their own" },
        effort: { level: 2, text: "Two trusts to fund" },
      },
      map: { x: 62, y: 56 },
      learn: { href: "/learn/trusts/revocable-living-trust", label: "How a revocable living trust works" },
    },
    {
      id: "joint",
      name: "Joint trust that locks at the first death",
      short: "Joint trust",
      family: "hold",
      icon: "Handshake",
      what: "You and your spouse share one living trust. When the first spouse dies, that spouse's part becomes irrevocable so it must follow the plan you both agreed to.",
      bestFor: ["Couples who have merged most of their money", "Spouses who get along well with each other's children"],
      watchOut: ["The survivor can still change the plan for their own half", "Splitting the trust at the first death takes careful records of who owned what"],
      cells: {
        spouse: { level: 3, text: "Survivor runs the trust" },
        kids: { level: 2, text: "Locked for the first half only" },
        timing: { level: 0, text: "Usually wait for both deaths" },
        peace: { level: 1, text: "Survivor and stepchildren tied" },
        flex: { level: 2, text: "Survivor's half stays open" },
        effort: { level: 3, text: "Careful drafting and split" },
      },
      map: { x: 22, y: 24 },
      learn: { href: "/learn/trusts/irrevocable-trusts", label: "What irrevocable means" },
    },
    {
      id: "prenup",
      name: "Prenup or postnup",
      short: "Prenup",
      family: "separate",
      icon: "FileSignature",
      what: "A signed agreement between spouses that says what each keeps and can waive the rights a spouse would otherwise have at death, such as Illinois's right to renounce a will.",
      bestFor: ["Couples about to marry who each have children or savings", "Already-married couples who want a postnup to back up their estate plans"],
      watchOut: ["It does not move any money. You still need a will, trust and beneficiary forms", "A prenup cannot waive your spouse's 401(k) rights. Your spouse must sign a separate waiver after the wedding"],
      cells: {
        spouse: { level: 1, text: "Only what the deal provides" },
        kids: { level: 3, text: "Blocks spousal claims" },
        timing: { level: 1, text: "Depends on your other papers" },
        peace: { level: 2, text: "Rules agreed in advance" },
        flex: { level: 1, text: "Changed only by both of you" },
        effort: { level: 2, text: "A lawyer for each spouse" },
      },
      map: { x: 66, y: 40 },
      learn: { href: "/learn/blended-families/prenuptial-agreements-and-estate-plans", label: "Prenups and your estate plan" },
    },
    {
      id: "insurance",
      name: "Life insurance for the children",
      short: "Life insurance",
      family: "add",
      icon: "Umbrella",
      what: "You buy a policy that names your children, or a trust for them, as beneficiaries. They get cash at your death while your other assets support your spouse.",
      bestFor: ["Couples whose main assets are a house and a retirement account", "Children who should not wait for a stepparent to die", "Evening things out when your spouse gets the bulk"],
      watchOut: ["Premiums rise with age and health, and you may not qualify", "Name a trust, not the children directly, if any child is under 18"],
      cells: {
        spouse: { level: 2, text: "Leaves other assets for spouse" },
        kids: { level: 3, text: "Paid straight to children" },
        timing: { level: 3, text: "Paid within weeks" },
        peace: { level: 3, text: "No shared money" },
        flex: { level: 2, text: "Spouse keeps the rest" },
        effort: { level: 1, text: "Premiums, little paperwork" },
      },
      map: { x: 76, y: 90 },
      learn: { href: "/learn/beneficiary-designations/life-insurance-beneficiaries", label: "Naming life insurance beneficiaries" },
    },
    {
      id: "house",
      name: "Right to live in the house",
      short: "House rights",
      family: "hold",
      icon: "House",
      what: "Your spouse gets a life estate or a right to live in your house, often through a trust. When your spouse dies or moves out, the house goes to your children.",
      bestFor: ["A home you owned before the marriage", "A spouse who needs a place to live but has other income"],
      watchOut: ["Spell out who pays taxes, insurance and repairs, and what happens if your spouse moves or remarries", "Your children cannot sell or live in the house until the right ends"],
      cells: {
        spouse: { level: 2, text: "A home, not money" },
        kids: { level: 3, text: "House goes to them later" },
        timing: { level: 0, text: "Wait until the right ends" },
        peace: { level: 1, text: "Shared costs can cause friction" },
        flex: { level: 1, text: "Hard to sell or move" },
        effort: { level: 2, text: "Deed or trust terms" },
      },
      map: { x: 46, y: 22 },
      learn: { href: "/learn/blended-families/family-home-in-second-marriage", label: "The family home in a second marriage" },
    },
    {
      id: "iloveyou",
      name: "Everything to your spouse (\"I love you\" will)",
      short: "All to spouse",
      family: "trust",
      icon: "Heart",
      what: "Your will and beneficiary forms leave everything to your spouse, who is expected to leave something to your children later.",
      bestFor: ["Couples with no children from earlier relationships", "Spouses who trust each other fully and have a small estate"],
      watchOut: ["Your spouse can change their will and leave everything to their own family or a new partner", "Your children have no legal claim to what you left your spouse"],
      cells: {
        spouse: { level: 3, text: "Gets everything" },
        kids: { level: 0, text: "No protection" },
        timing: { level: 0, text: "Only if spouse leaves them some" },
        peace: { level: 1, text: "Children depend on stepparent" },
        flex: { level: 3, text: "Spouse decides everything" },
        effort: { level: 0, text: "Simple wills" },
      },
      map: { x: 6, y: 10 },
      learn: { href: "/learn/blended-families/protecting-children-from-first-marriage", label: "Protecting children from a first marriage" },
    },
    {
      id: "split",
      name: "Split it at the first death",
      short: "Direct split",
      family: "separate",
      icon: "Scale",
      what: "When you die, part of your estate goes straight to your children and part to your spouse, with no trust holding anything back.",
      bestFor: ["A spouse with enough savings or income of their own", "Children close in age to your spouse, who would wait a long time otherwise"],
      watchOut: ["Your spouse gets less to live on", "What your spouse receives can still go to their own family later"],
      cells: {
        spouse: { level: 1, text: "Only their portion" },
        kids: { level: 3, text: "Their share paid now" },
        timing: { level: 3, text: "At your death" },
        peace: { level: 3, text: "No ongoing ties" },
        flex: { level: 2, text: "Spouse owns their part outright" },
        effort: { level: 1, text: "Simple will or trust terms" },
      },
      map: { x: 90, y: 84 },
    },
  ],
  map: {
    title: "The second marriage map",
    lead: "Options on the left put your spouse first. Moving right, your children's share is better protected. Options higher up get money to your children at your death instead of after your spouse dies.",
    x: { low: "Spouse comes first", high: "Children's share protected" },
    y: { low: "Children wait for the second death", high: "Children inherit at your death" },
  },
  questions: [
    {
      id: "support",
      prompt: "If you die first, how much would your spouse rely on your assets?",
      choices: [
        { id: "relies", label: "A lot. My spouse needs my income or savings", weights: { qtip: 3, joint: 1, house: 1, iloveyou: 1, split: -1 }, reason: "Your spouse relies on your assets, so they need income for life" },
        { id: "own", label: "Not much. My spouse has their own money", weights: { separate: 3, split: 3, prenup: 2, qtip: -1 }, reason: "Your spouse has their own money, so you can keep finances separate" },
        { id: "some", label: "Somewhat", weights: { separate: 1, qtip: 1, insurance: 1 } },
      ],
    },
    {
      id: "ages",
      prompt: "How close in age are your spouse and your children?",
      help: "With a trust for your spouse, your children inherit only after your spouse dies.",
      choices: [
        { id: "close", label: "Close. My children could wait decades", weights: { split: 3, insurance: 3, qtip: -2, house: -1, joint: -1 }, reason: "Your spouse is close in age to your children, who should not wait decades to inherit" },
        { id: "apart", label: "My spouse is a generation older than my children", weights: { qtip: 2, house: 2 }, reason: "Your children are much younger than your spouse, so waiting is reasonable" },
      ],
    },
    {
      id: "home",
      prompt: "How do you own your home and savings?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "myhouse", label: "I own the home, and my spouse would need to stay there", weights: { house: 4, qtip: 1 }, reason: "Your spouse needs to stay in a home that should go to your children later" },
        { id: "together", label: "We own almost everything together", weights: { joint: 3, iloveyou: 1, separate: -1 }, reason: "You own most things together, so one shared trust fits how you live" },
        { id: "apart", label: "We each brought our own home or savings and keep them apart", weights: { separate: 4, split: 1, prenup: 1 }, reason: "You each keep your own assets, so separate trusts match how you live" },
      ],
    },
    {
      id: "relations",
      prompt: "How do your spouse and your children get along?",
      choices: [
        { id: "well", label: "Well. They trust each other", weights: { joint: 3, iloveyou: 3 }, reason: "Your spouse and children trust each other" },
        { id: "okay", label: "Fine, but I would rather not tie them together over money", weights: { insurance: 3, split: 3, separate: 2, joint: -1 }, reason: "You want your spouse and children to have no shared money to argue over" },
        { id: "tense", label: "There is tension", weights: { insurance: 3, split: 2, prenup: 2, qtip: 1, joint: -3, iloveyou: -4 }, reason: "There is tension, so your children need a share your spouse cannot touch" },
      ],
    },
    {
      id: "married",
      prompt: "Are you married yet?",
      choices: [
        { id: "soon", label: "Not yet. We are getting married", weights: { prenup: 4 }, reason: "You are not yet married, so a prenup can settle each spouse's rights before the wedding" },
        { id: "yes", label: "Yes, we are married", weights: { prenup: 1 } },
      ],
    },
    {
      id: "size",
      prompt: "What do you own besides your home?",
      choices: [
        { id: "large", label: "A lot. My estate could top $4 million", detail: "Illinois taxes estates over $4 million.", weights: { qtip: 3, separate: 1 }, reason: "Your estate is large enough that a marital trust can delay estate tax" },
        { id: "enough", label: "Enough to give my spouse and my children each a share now", weights: { split: 3, separate: 1 }, reason: "You have enough to give both your spouse and your children a share right away" },
        { id: "modest", label: "Mostly a retirement account and some savings", weights: { insurance: 3, house: 2, iloveyou: 1 }, reason: "Your estate is modest, so insurance can create a separate gift for your children" },
      ],
    },
    {
      id: "faith",
      prompt: "Would you trust your spouse to leave your share to your children?",
      choices: [
        { id: "fully", label: "Yes, completely", weights: { iloveyou: 4, joint: 1, qtip: -2 }, reason: "You fully trust your spouse to provide for your children later" },
        { id: "locked", label: "Yes, but I want my half locked in", weights: { joint: 4, qtip: 2 }, reason: "You trust your spouse but want your half of the plan locked in" },
        { id: "no", label: "No, or not sure. My spouse could remarry or change their mind", weights: { qtip: 3, separate: 2, split: 1, iloveyou: -4 }, reason: "Your spouse could remarry or change their will, so your children's share should be protected" },
      ],
    },
  ],
  resultNote: "Most second-marriage plans combine two or three of these, such as a QTIP trust plus life insurance for the children. Update your 401(k), IRA and insurance forms to match, because they skip your will.",
  shortcuts: [
    { when: "Your spouse needs income from your assets and your children can wait", pick: "qtip" },
    { when: "Your spouse is close in age to your children", pick: "insurance" },
    { when: "You each came into the marriage with your own savings", pick: "separate" },
    { when: "You are engaged and either of you has children", pick: "prenup" },
    { when: "You own the house and your spouse needs to stay in it", pick: "house" },
    { when: "You have merged everything and trust each other's children", pick: "joint" },
    { when: "Your spouse has their own money and your children should not wait", pick: "split" },
    { when: "Neither of you has children from earlier relationships", pick: "iloveyou" },
  ],
  diagrams: ["BlendedFamilyPlan", "BeneficiaryBeatsWill"],
  howTo: {
    name: "How to plan for a spouse and children in a second marriage",
    steps: [
      { name: "List what each of you owns", text: "Note what each spouse brought into the marriage, what you bought together, and how each item is titled." },
      { name: "Decide what your spouse needs", text: "Work out what your spouse would need to live on, and whether they need to stay in your house." },
      { name: "Decide when your children inherit", text: "Choose whether your children get something at your death, after your spouse dies, or both." },
      { name: "Sign an agreement if you need one", text: "A prenup or postnup can waive the right to renounce your will. Each spouse should have their own lawyer." },
      { name: "Set up the trust or will", text: "Sign the trust or will that carries out your plan, and retitle accounts and the house into any trust." },
      { name: "Match every beneficiary form", text: "Update your 401(k), IRA, life insurance and bank forms. Your spouse must sign a waiver to name anyone else on a 401(k)." },
    ],
  },
  faqs: [
    { q: "Should each spouse have their own revocable trust in a second marriage?", a: "Often, yes. Separate trusts keep each spouse's assets apart, and each spouse decides how much goes to the other spouse and to their own children. A joint trust can work for couples who have merged everything, but the survivor usually keeps control of their own half." },
    { q: "What is a joint trust and why is it risky in a blended family?", a: "A joint trust holds both spouses' assets in one trust. If it stays fully revocable after the first death, the survivor can rewrite it and cut out the first spouse's children. Writing it so the first spouse's share locks at death helps, but the survivor's own share can still change." },
    { q: "Can a surviving spouse disinherit my kids from my first marriage?", a: "Yes, if you leave everything to your spouse outright. Once your spouse owns it, they can leave it to anyone. A QTIP trust, separate trusts, a direct split or life insurance for your children prevents that." },
    { q: "Can I leave my spouse out of my will in Illinois?", a: "You can, but in Illinois your spouse may renounce the will and take a share set by law, one-third of the estate if you have descendants. Assets in a funded living trust have often been treated as outside that right, but courts look at the facts, so do not rely on it alone. A prenup or postnup is the usual way to waive this right." },
    { q: "Can I leave my house to my children and still let my spouse live there?", a: "Yes. You can give your spouse a life estate or a right to live in the house, often through a trust, with the house passing to your children when the right ends. Write down who pays taxes, insurance and repairs, and what happens if your spouse moves out or remarries." },
    { q: "Who should be the beneficiary of my 401(k) in a second marriage?", a: "Federal law gives your spouse your 401(k) unless your spouse signs a written waiver after the wedding. A waiver in a prenup is not enough. An IRA has no such rule, so you can name your children or a trust, but check whether that leaves your spouse enough to live on." },
    { q: "Does a prenup protect inheritance for my children?", a: "It can. A prenup or postnup can waive your spouse's right to claim part of your estate at death. But it does not leave anything to your children by itself, so you still need a will or trust and up-to-date beneficiary forms." },
    { q: "Should I use life insurance to equalize inheritances in a blended family?", a: "It is one of the simplest tools. A policy paid to your children, or to a trust for them, gives them money at your death while your other assets support your spouse. Consider the cost of premiums, and use a trust if any child is a minor." },
  ],
  related: [
    { href: "/learn/blended-families/protecting-children-from-first-marriage", label: "Protecting children from a first marriage" },
    { href: "/learn/blended-families/qtip-and-marital-trusts", label: "QTIP and marital trusts" },
    { href: "/learn/blended-families/family-home-in-second-marriage", label: "Who gets the house in a second marriage" },
    { href: "/quizzes/blended-family-check", label: "Blended family plan check" },
    { href: "/decide/types-of-trusts", label: "Types of trusts: which one fits you" },
    { href: "/decide/per-stirpes-vs-per-capita", label: "Per stirpes vs per capita" },
  ],
};
