import { FIGURES, usdFigure } from "@/config/figures";
import type { DecisionGuide } from "./types";

const ABLE_LIMIT = usdFigure(FIGURES.ableAnnualContributionLimit);

export const TYPES_OF_SPECIAL_NEEDS_TRUSTS: DecisionGuide = {
  slug: "types-of-special-needs-trusts",
  title: "Types of special needs trusts: 5 options compared",
  h1: "Types of special needs trusts, and which one fits your family",
  description: `Third-party, first-party, pooled and testamentary special needs trusts, plus ABLE accounts, compared. Answer six questions to see which protects SSI and Medicaid.`,
  kicker: "Special needs decision guide",
  art: "HeroSpecialNeeds",
  tone: "sage",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "It depends on whose money it is. If parents or relatives are leaving money, use a third-party special needs trust, set up now or written into a will. It has no Medicaid payback. If the money already belongs to the person, such as a settlement, use a first-party trust before age 65 or a pooled trust run by a nonprofit. An ABLE account adds a spending account the person can use directly.",
  takeaways: [
    "Start with one question: whose money is it? Family money and the person's own money follow different rules.",
    "Never leave an inheritance outright to someone on SSI or Medicaid. Name a third-party special needs trust instead.",
    "Trusts that hold the person's own money must repay Medicaid at death. Trusts funded by family do not.",
    `An ABLE account lets the person spend for themselves. Family can add up to ${ABLE_LIMIT} a year, and SSI ignores the first $100,000.`,
    "Most families use two tools together: a third-party trust for the big money and an ABLE account for everyday costs.",
  ],
  noun: "special needs option",
  families: [
    { id: "family", name: "Family money", text: "Parents, grandparents or others leave money for the person. No Medicaid payback.", tone: "sage" },
    { id: "own", name: "The person's own money", text: "A settlement, back benefits or an inheritance left to them directly. Medicaid is repaid at death.", tone: "clay" },
    { id: "account", name: "A spending account", text: "A tax-free account the person controls for everyday disability costs.", tone: "gold" },
  ],
  dimensions: [
    { id: "payback", label: "Medicaid payback at death", help: "Must leftover money repay the state for Medicaid first? More dots means more goes to the state.", inverse: true },
    { id: "age", label: "Open at any age", help: "Are there age limits on who can use it or when it is funded?" },
    { id: "now", label: "Works during your life", help: "Is it ready while you are alive, or only after your death?" },
    { id: "direct", label: "Person can spend directly", help: "Can the person with the disability pay for things on their own?" },
    { id: "housing", label: "Pays rent without an SSI cut", help: "Can it cover rent or a mortgage without lowering the SSI check?" },
    { id: "size", label: "Holds large sums", help: "Is there a cap on how much can go in or stay in?" },
    { id: "effort", label: "Setup and upkeep", help: "Drafting, tax filings, fees and records. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "thirdparty",
      name: "Third-party special needs trust",
      short: "Third-party",
      family: "family",
      icon: "HandHeart",
      what: "A trust that parents or other relatives set up and fund with their own money, to pay for extras for a person with a disability without counting as that person's money.",
      bestFor: ["Parents of a child or adult on SSI or Medicaid, or likely to need it", "Grandparents and siblings who want to leave money safely", "A place to name as beneficiary on life insurance and retirement accounts"],
      watchOut: ["Never put the person's own money in it, or you can lose the no-payback protection", "Relatives must name the trust, not the person, on their wills and beneficiary forms"],
      cells: {
        payback: { level: 0, text: "None" },
        age: { level: 3, text: "No age limit" },
        now: { level: 3, text: "Yes, set up today" },
        direct: { level: 0, text: "No, trustee pays" },
        housing: { level: 1, text: "Can, but SSI may drop" },
        size: { level: 3, text: "No cap" },
        effort: { level: 2, text: "Careful drafting, tax returns" },
      },
      map: { x: 10, y: 12 },
      learn: { href: "/learn/special-needs/first-party-vs-third-party-special-needs-trust", label: "First-party vs third-party trusts" },
    },
    {
      id: "testamentary",
      name: "Testamentary special needs trust",
      short: "Testamentary",
      family: "family",
      icon: "ScrollText",
      what: "A third-party special needs trust written into your will. It does not exist until you die and the will goes through probate.",
      bestFor: ["Parents of a young child who want a low-cost plan today", "Families whose main assets will pass through a will anyway"],
      watchOut: ["Nothing is in place while you are alive, so grandparents have no trust to name", "Probate delays funding, and it is public"],
      cells: {
        payback: { level: 0, text: "None" },
        age: { level: 3, text: "No age limit" },
        now: { level: 0, text: "No, starts after probate" },
        direct: { level: 0, text: "No, trustee pays" },
        housing: { level: 1, text: "Can, but SSI may drop" },
        size: { level: 3, text: "No cap" },
        effort: { level: 1, text: "Low now, probate later" },
      },
      map: { x: 22, y: 6 },
      learn: { href: "/learn/special-needs/special-needs-trust", label: "Special needs trusts explained" },
    },
    {
      id: "firstparty",
      name: "First-party (d)(4)(A) special needs trust",
      short: "First-party",
      family: "own",
      icon: "ShieldCheck",
      what: "A trust that holds the person's own money, such as an injury settlement or an inheritance left to them directly, so they keep SSI and Medicaid. It must repay Medicaid when they die.",
      bestFor: ["A person under 65 who receives a settlement, back pay or a direct inheritance", "Large sums that need a family trustee or a professional"],
      watchOut: ["The person must be under 65 when it is set up and funded", "Medicaid is repaid from what is left before family gets anything"],
      cells: {
        payback: { level: 3, text: "Yes, Medicaid is repaid first" },
        age: { level: 1, text: "Set up and funded before 65" },
        now: { level: 3, text: "Yes, when the money arrives" },
        direct: { level: 0, text: "No, trustee pays" },
        housing: { level: 1, text: "Can, but SSI may drop" },
        size: { level: 3, text: "No cap" },
        effort: { level: 2, text: "Moderate, strict reporting" },
      },
      map: { x: 92, y: 10 },
      learn: { href: "/learn/special-needs/first-party-vs-third-party-special-needs-trust", label: "First-party vs third-party trusts" },
    },
    {
      id: "pooled",
      name: "Pooled (d)(4)(C) trust",
      short: "Pooled",
      family: "own",
      icon: "UsersRound",
      what: "A trust run by a nonprofit that keeps a separate account for each person and invests the accounts together. It can hold the person's own money, and some also take family money.",
      bestFor: ["Smaller sums that would not justify a stand-alone trust", "People with no family member able to serve as trustee", "People 65 or older, in states where that does not trigger a Medicaid penalty"],
      watchOut: ["For people 65 and older, transfer penalty rules vary by state, so check before funding", "Enrollment and yearly fees, and the nonprofit may keep part of what is left"],
      cells: {
        payback: { level: 2, text: "Nonprofit keeps some, Medicaid the rest" },
        age: { level: 2, text: "Any age, 65+ varies by state" },
        now: { level: 3, text: "Yes, join any time" },
        direct: { level: 0, text: "No, nonprofit pays" },
        housing: { level: 1, text: "Can, but SSI may drop" },
        size: { level: 2, text: "Small to mid sums" },
        effort: { level: 1, text: "Low, plus fees" },
      },
      map: { x: 76, y: 30 },
      learn: { href: "/learn/elder-care/medicaid-planning", label: "Medicaid planning explained" },
    },
    {
      id: "able",
      name: "ABLE account",
      short: "ABLE",
      family: "account",
      icon: "PiggyBank",
      what: "A tax-free savings account owned by the person with the disability, for everyday disability costs such as rent, transportation, school and therapy.",
      bestFor: ["A person whose disability began before age 46 who wants some control over spending", "Rent and food money that a trust cannot pay without an SSI cut", "Families adding a small amount each year"],
      watchOut: [`Contributions from everyone combined are capped at ${ABLE_LIMIT} a year`, "SSI counts any balance over $100,000, and the state may claim what is left for Medicaid at death"],
      cells: {
        payback: { level: 2, text: "State may claim the balance" },
        age: { level: 1, text: "Disability began before 46" },
        now: { level: 3, text: "Yes, open online" },
        direct: { level: 3, text: "Yes, often with a debit card" },
        housing: { level: 3, text: "Yes, no SSI cut" },
        size: { level: 1, text: `${ABLE_LIMIT} a year in` },
        effort: { level: 0, text: "Low" },
      },
      map: { x: 50, y: 88 },
      learn: { href: "/learn/special-needs/able-accounts", label: "ABLE accounts explained" },
    },
  ],
  map: {
    title: "The special needs map",
    lead: "Options on the left hold money from family. Moving right, they hold the person's own money and must repay Medicaid. Options higher up let the person spend the money directly.",
    x: { low: "Family's money", high: "The person's own money" },
    y: { low: "Trustee decides each payment", high: "Person can spend it directly" },
  },
  questions: [
    {
      id: "whose",
      prompt: "Whose money will go in?",
      help: "This is the key fork. The rules follow from the answer.",
      choices: [
        { id: "family", label: "Ours. Parents or relatives are setting money aside", weights: { thirdparty: 4, testamentary: 3, able: 1, firstparty: -4, pooled: -1 }, reason: "You are using family money, which can go in a trust with no Medicaid payback" },
        { id: "own", label: "Theirs. A settlement, back pay or an inheritance left to them", weights: { firstparty: 4, pooled: 3, able: 2, thirdparty: -4, testamentary: -4 }, reason: "You are protecting the person's own money, which needs a first-party or pooled trust" },
        { id: "both", label: "Both", weights: { thirdparty: 2, firstparty: 2, pooled: 1, able: 2 }, reason: "You have both kinds of money, which should be kept in separate places" },
      ],
    },
    {
      id: "age",
      prompt: "How old is the person, and when did the disability begin?",
      help: "ABLE accounts require that the disability began before age 46. First-party trusts must be set up before 65.",
      choices: [
        { id: "under46", label: "Under 65, and the disability began before 46", weights: { able: 2, firstparty: 1 }, reason: "You qualify by age for an ABLE account" },
        { id: "late", label: "Under 65, but the disability began at 46 or later", weights: { able: -5, firstparty: 1, thirdparty: 1 } },
        { id: "over65", label: "65 or older", weights: { firstparty: -6, pooled: 3, thirdparty: 1 }, reason: "You are 65 or older, so a pooled trust may be the only option for the person's own money" },
      ],
    },
    {
      id: "amount",
      prompt: "Roughly how much money are you planning for?",
      choices: [
        { id: "small", label: `A modest amount, up to about ${ABLE_LIMIT} a year`, weights: { able: 4, pooled: 2, thirdparty: -1 }, reason: "You are planning for a modest amount that fits an ABLE account" },
        { id: "mid", label: "Tens of thousands of dollars", weights: { pooled: 2, thirdparty: 1, firstparty: 1, able: 1 } },
        { id: "large", label: "$100,000 or more, such as a life insurance payout or settlement", weights: { thirdparty: 3, firstparty: 3, testamentary: 1, able: -2 }, reason: "You are planning for a large sum that needs a full trust" },
      ],
    },
    {
      id: "when",
      prompt: "When does this need to start working?",
      choices: [
        { id: "now", label: "Now, so relatives can name it in their plans", weights: { thirdparty: 4, able: 1, testamentary: -2 }, reason: "You want the trust in place now, so others can name it" },
        { id: "death", label: "At my death. I want the lowest cost today", weights: { testamentary: 6, thirdparty: -2 }, reason: "You want a low-cost plan that sets up the trust through your will" },
        { id: "arriving", label: "Money is arriving soon, such as a settlement", weights: { firstparty: 2, pooled: 2 }, reason: "You have money arriving that needs a home before it is counted" },
      ],
    },
    {
      id: "trustee",
      prompt: "Who will manage the money?",
      choices: [
        { id: "family", label: "A parent, sibling or other trusted relative", weights: { thirdparty: 2, firstparty: 2, testamentary: 1 }, reason: "You have a trusted relative ready to serve as trustee" },
        { id: "nonprofit", label: "No one in the family. We want an organization to do it", weights: { pooled: 5 }, reason: "You want a nonprofit to handle the trustee work" },
        { id: "self", label: "The person can manage some money themselves", weights: { able: 4 }, reason: "The person can manage some spending money on their own" },
      ],
    },
    {
      id: "goals",
      prompt: "What matters most to you?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "rent", label: "Paying rent or housing without cutting SSI", weights: { able: 3 }, reason: "You want to pay housing costs without lowering SSI" },
        { id: "leftover", label: "Leftover money goes to siblings, not the state", weights: { thirdparty: 3, testamentary: 3, firstparty: -2, pooled: -1, able: -1 }, reason: "You want what is left to go to family, with no Medicaid payback" },
        { id: "extras", label: "Paying for therapy, equipment, trips and other extras", weights: { thirdparty: 1, testamentary: 1, firstparty: 1, pooled: 1 } },
        { id: "simple", label: "Keeping it simple and low cost", weights: { able: 2, pooled: 2, testamentary: 1 }, reason: "You want a simple, low-cost setup" },
      ],
    },
  ],
  resultNote:
    "SSI and Medicaid rules are strict and change often, and pooled trust rules differ from state to state. Before you sign or move money, have the plan reviewed by an attorney who handles special needs planning.",
  shortcuts: [
    { when: "You are a parent leaving money to a child on SSI or Medicaid", pick: "thirdparty" },
    { when: "Grandparents or siblings want to leave money too", pick: "thirdparty" },
    { when: "Your child is young and you need a low-cost plan today", pick: "testamentary" },
    { when: "The person is under 65 and receives a settlement or a direct inheritance", pick: "firstparty" },
    { when: "The person is 65 or older and has their own money to protect", pick: "pooled" },
    { when: "No family member can serve as trustee and the sum is modest", pick: "pooled" },
    { when: "The disability began before 46 and the person wants spending money for rent and daily costs", pick: "able" },
  ],
  diagrams: ["SpecialNeedsTrust"],
  howTo: {
    name: "How to choose a special needs trust",
    steps: [
      { name: "Name whose money it is", text: "Separate family money from money that belongs to the person. Each needs its own home, and mixing them can bring a Medicaid payback." },
      { name: "Check age and benefits", text: "Note the person's age, when the disability began and which benefits they get, such as SSI, SSDI or Medicaid. These set which options are open." },
      { name: "Pick the trust and the trustee", text: "Choose a family trustee and a backup, or a nonprofit pooled trust. Write down how you want money spent." },
      { name: "Add an ABLE account for daily costs", text: `If the disability began before 46, open an ABLE account for rent, food and everyday spending. Family can add up to ${ABLE_LIMIT} a year in total.` },
      { name: "Point every gift at the trust", text: "Change your will, life insurance and retirement beneficiary forms to name the trust. Ask grandparents and siblings to do the same." },
      { name: "Write a letter of intent", text: "Describe routines, doctors, likes and goals so the next trustee and caregiver know the person well." },
    ],
  },
  faqs: [
    {
      q: "What is a pay-back provision in a special needs trust?",
      a: "It is a clause that says Medicaid gets repaid from what is left in the trust when the beneficiary dies, before anyone else receives money. Federal law requires it in first-party trusts that hold the person's own money. Third-party trusts funded by parents or relatives do not need one.",
    },
    {
      q: "Can a special needs trust be set up after a person turns 65?",
      a: "A third-party trust funded by family can be set up at any age. A first-party trust for the person's own money generally must be set up and funded before 65. After that, a pooled trust may be the only option, and whether a transfer into it triggers a Medicaid penalty depends on your state.",
    },
    {
      q: "What is a (d)(4)(C) pooled trust?",
      a: "It is a special needs trust run by a nonprofit, named for the section of federal Medicaid law that allows it. The nonprofit keeps a separate account for each person but invests the money together, which keeps costs down for smaller sums. When the person dies, the nonprofit may keep some of what is left, and the rest repays Medicaid.",
    },
    {
      q: "What is the ABLE account age limit of 46?",
      a: "Starting January 1, 2026, a person can open an ABLE account if their disability began before age 46. Before 2026 the cutoff was 26. The test is when the disability started, not how old the person is today, so a 60-year-old whose disability began at 40 can now qualify.",
    },
    {
      q: "Can a special needs trust fund an ABLE account?",
      a: `Yes. A trustee can deposit trust money into the person's ABLE account, and it counts toward the ${ABLE_LIMIT} yearly limit. Families often do this so the person can pay rent or buy food from the ABLE account, which does not reduce SSI the way a direct trust payment for housing can.`,
    },
    {
      q: "Who gets the money left in a special needs trust after death?",
      a: "With a third-party trust, the money goes to whoever the parents named, often siblings or a charity. With a first-party trust, Medicaid is repaid first and any balance goes to the named people. With a pooled trust, the nonprofit may keep part of it under its rules.",
    },
    {
      q: "Can a parent be trustee of a special needs trust?",
      a: "Yes, and many parents serve as the first trustee. The job takes care: the trustee pays providers directly, keeps records and learns which payments can lower SSI. Name a backup trustee, such as a sibling, a trust company or a pooled trust, for when you can no longer serve.",
    },
    {
      q: "Does an inheritance affect SSI benefits?",
      a: "Yes. Money left directly to a person on SSI counts as income in the month it arrives and as an asset after that. SSI has a $2,000 asset limit for an individual, so even a modest inheritance can stop benefits and threaten Medicaid. Leaving the money to a third-party special needs trust avoids this.",
    },
  ],
  related: [
    { href: "/learn/special-needs/special-needs-trust", label: "Special needs trusts explained" },
    { href: "/learn/special-needs/letter-of-intent", label: "Writing a letter of intent" },
    { href: "/estate-planning-for/special-needs-families", label: "Estate planning for special needs families" },
    { href: "/decide/types-of-trusts", label: "Types of trusts, and which one fits" },
    { href: "/decide/alternatives-to-guardianship", label: "Alternatives to guardianship" },
  ],
};
