import { FIGURES, usdMillions } from "@/config/figures";
import type { DecisionGuide } from "./types";

const EXEMPTION = usdMillions(FIGURES.federalExemption);

export const TYPES_OF_TRUSTS: DecisionGuide = {
  slug: "types-of-trusts",
  title: "Types of trusts: which one should you pick?",
  h1: "Types of trusts, and which one fits you",
  description: `Twelve common types of trusts compared on one page: who each is for, control, probate, taxes and protection. Answer six questions to see which trust fits your family.`,
  kicker: "Trust decision guide",
  art: "HeroTrusts",
  tone: "accent",
  updated: "2026-10-06",
  reviewed: false,
  answer:
    "Most families need one trust: a revocable living trust, which avoids probate and covers incapacity while you keep full control. Other trusts solve one specific problem. A special needs trust protects a disabled person's benefits, a spendthrift trust protects a heir from debts, and irrevocable trusts such as an ILIT or a Medicaid trust trade control for tax or nursing home protection.",
  takeaways: [
    "Start with the problem, not the trust. Each type exists to solve one or two problems well.",
    "A revocable living trust is the base of most trust plans. You can change it, and it avoids probate if you fund it.",
    "Irrevocable trusts give up control in exchange for tax savings, creditor protection or Medicaid planning.",
    "Several trusts can live inside one plan. A living trust often holds a special needs or children's trust for later.",
    "A trust only controls what you put into it, so funding matters as much as the document.",
  ],
  noun: "trust",
  families: [
    { id: "control", name: "Trusts you control", text: "You keep the keys, can change your mind, and your family skips probate.", tone: "accent" },
    { id: "people", name: "Trusts that look after someone", text: "Rules for money left to a child, a vulnerable adult or even a pet.", tone: "sage" },
    { id: "tax", name: "Trusts that cut taxes", text: "Used by larger estates and married couples to lower or delay estate tax.", tone: "gold" },
    { id: "protect", name: "Trusts that protect assets", text: "You give up control so savings are harder for creditors or nursing home costs to reach.", tone: "clay" },
  ],
  dimensions: [
    { id: "change", label: "You can change it", help: "Can you amend or cancel it later?" },
    { id: "probate", label: "Avoids probate", help: "Do assets pass without a court process?" },
    { id: "tax", label: "Can lower estate tax", help: `Matters mainly above ${EXEMPTION} per person, or in states with their own estate tax.` },
    { id: "creditors", label: "Shields from creditors", help: "Protection from lawsuits, debts or a divorcing spouse." },
    { id: "benefits", label: "Protects benefits", help: "Keeps Medicaid or SSI eligibility intact." },
    { id: "effort", label: "Setup and upkeep", help: "Relative cost and paperwork. More dots means more work.", inverse: true },
  ],
  options: [
    {
      id: "revocable",
      name: "Revocable living trust",
      short: "Living trust",
      family: "control",
      icon: "House",
      what: "A trust you create and control during your life. You can change it any time, and your successor trustee takes over if you become unable to manage or after you die.",
      bestFor: ["Homeowners who want their family to skip probate", "People with property in more than one state", "Anyone who wants a plan for incapacity and privacy"],
      watchOut: ["Only works for assets you retitle into it", "No tax savings and no protection from your own creditors"],
      cells: {
        change: { level: 3, text: "Yes, any time" },
        probate: { level: 3, text: "Yes, for funded assets" },
        tax: { level: 0, text: "No" },
        creditors: { level: 0, text: "No, you still own it" },
        benefits: { level: 0, text: "No, counted as yours" },
        effort: { level: 2, text: "Moderate, plus funding" },
      },
      map: { x: 8, y: 14 },
      learn: { href: "/learn/trusts/revocable-living-trust", label: "Revocable living trusts explained" },
    },
    {
      id: "testamentary",
      name: "Testamentary trust",
      short: "Testamentary",
      family: "people",
      icon: "FileText",
      what: "A trust written into your will. It does not exist until you die and your will goes through probate, then it holds money for the people you name.",
      bestFor: ["Parents of young children on a budget", "People who want a trust for heirs but do not need to avoid probate"],
      watchOut: ["Your estate still goes through probate first", "Some states keep the court involved with the trust"],
      cells: {
        change: { level: 3, text: "Yes, by changing your will" },
        probate: { level: 0, text: "No, starts after probate" },
        tax: { level: 1, text: "Only if drafted for it" },
        creditors: { level: 2, text: "For heirs, with spendthrift terms" },
        benefits: { level: 1, text: "Can hold a needs trust" },
        effort: { level: 1, text: "Low, part of your will" },
      },
      map: { x: 20, y: 34 },
      learn: { href: "/learn/trusts/trusts-for-children", label: "Trusts for children" },
    },
    {
      id: "special-needs",
      name: "Special needs trust",
      short: "Special needs",
      family: "people",
      icon: "HandHeart",
      what: "A trust that pays for extras for a person with a disability without counting as their money, so they keep SSI and Medicaid.",
      bestFor: ["Families with a child or adult who receives, or may need, SSI or Medicaid", "Anyone leaving money to a person with a disability"],
      watchOut: ["Leaving money to the person directly can end their benefits", "First-party trusts must repay Medicaid at death"],
      cells: {
        change: { level: 1, text: "Third-party: often, during life" },
        probate: { level: 2, text: "Yes, if set up during life" },
        tax: { level: 0, text: "No" },
        creditors: { level: 2, text: "For the beneficiary" },
        benefits: { level: 3, text: "Yes, that is its purpose" },
        effort: { level: 2, text: "Moderate, careful drafting" },
      },
      map: { x: 22, y: 70 },
      learn: { href: "/learn/special-needs/special-needs-trust", label: "Special needs trusts explained" },
    },
    {
      id: "spendthrift",
      name: "Spendthrift trust",
      short: "Spendthrift",
      family: "people",
      icon: "Wallet",
      what: "A trust that pays a beneficiary over time and stops their creditors, or the beneficiary, from reaching money before it is paid out.",
      bestFor: ["Heirs who struggle with money, addiction or debt", "Young adults you want paid in stages", "Heirs at risk of divorce or lawsuits"],
      watchOut: ["Protects your heirs, not you", "Some creditors, such as child support, can still reach it in many states"],
      cells: {
        change: { level: 2, text: "Yes, if inside a living trust" },
        probate: { level: 2, text: "Yes, if inside a living trust" },
        tax: { level: 0, text: "No" },
        creditors: { level: 3, text: "Strong, for the heir" },
        benefits: { level: 1, text: "Not by itself" },
        effort: { level: 1, text: "Low, often a clause" },
      },
      map: { x: 36, y: 58 },
      learn: { href: "/learn/trusts/spendthrift-trusts", label: "Spendthrift trusts explained" },
    },
    {
      id: "pet",
      name: "Pet trust",
      short: "Pet trust",
      family: "people",
      icon: "PawPrint",
      what: "A trust that sets aside money and names a caregiver for your animals after you die or if you cannot care for them.",
      bestFor: ["Pet owners without a family member ready to take them", "Owners of long-lived animals such as horses or parrots"],
      watchOut: ["Courts can reduce a fund that is far more than the animal needs", "Name a backup caregiver"],
      cells: {
        change: { level: 3, text: "Yes, if revocable" },
        probate: { level: 2, text: "Yes, if inside a living trust" },
        tax: { level: 0, text: "No" },
        creditors: { level: 0, text: "No" },
        benefits: { level: 0, text: "Not applicable" },
        effort: { level: 1, text: "Low" },
      },
      map: { x: 30, y: 12 },
      learn: { href: "/learn/property-and-assets/pet-trusts", label: "Pet trusts explained" },
    },
    {
      id: "qtip",
      name: "QTIP or marital trust",
      short: "QTIP",
      family: "tax",
      icon: "Users",
      what: "A trust that supports your surviving spouse for life, delays estate tax until their death, and then passes what is left to the people you chose.",
      bestFor: ["Blended families who want to support a spouse and still protect children from a first marriage", "Larger estates that want to delay estate tax"],
      watchOut: ["Your spouse usually gets income, not free access to principal", "Assets count in the surviving spouse's taxable estate"],
      cells: {
        change: { level: 1, text: "Locked once the first spouse dies" },
        probate: { level: 3, text: "Yes, if funded" },
        tax: { level: 2, text: "Delays tax to second death" },
        creditors: { level: 2, text: "Some, for the spouse" },
        benefits: { level: 0, text: "No" },
        effort: { level: 2, text: "Moderate, tax election" },
      },
      map: { x: 52, y: 38 },
      learn: { href: "/learn/blended-families/qtip-and-marital-trusts", label: "QTIP and marital trusts" },
    },
    {
      id: "bypass",
      name: "Bypass or credit shelter trust",
      short: "Bypass (AB)",
      family: "tax",
      icon: "Scale",
      what: "A trust that uses the first spouse's estate tax exemption at death, so the assets and their growth stay out of the surviving spouse's taxable estate.",
      bestFor: ["Married couples in states with their own estate tax", "Couples whose assets may grow past the federal exemption"],
      watchOut: ["Portability now does part of this job for federal tax", "Assets miss a second step-up in basis"],
      cells: {
        change: { level: 1, text: "Locked once the first spouse dies" },
        probate: { level: 3, text: "Yes, if funded" },
        tax: { level: 3, text: "Shelters growth" },
        creditors: { level: 2, text: "Some, for the spouse" },
        benefits: { level: 0, text: "No" },
        effort: { level: 2, text: "Moderate" },
      },
      map: { x: 64, y: 56 },
      learn: { href: "/learn/estate-tax/portability-for-married-couples", label: "Portability for married couples" },
    },
    {
      id: "ilit",
      name: "Irrevocable life insurance trust",
      short: "ILIT",
      family: "tax",
      icon: "Umbrella",
      what: "A trust that owns your life insurance policy so the payout stays out of your taxable estate and is managed for your family.",
      bestFor: ["People with large policies whose estate may be taxed", "Parents who want insurance money managed for children"],
      watchOut: ["Moving an existing policy in counts back if you die within 3 years", "Annual gift notices and a separate trustee"],
      cells: {
        change: { level: 0, text: "No" },
        probate: { level: 3, text: "Yes" },
        tax: { level: 3, text: "Removes the payout" },
        creditors: { level: 3, text: "Strong" },
        benefits: { level: 1, text: "Not by itself" },
        effort: { level: 3, text: "High, yearly paperwork" },
      },
      map: { x: 76, y: 72 },
      learn: { href: "/learn/estate-tax/irrevocable-life-insurance-trust", label: "Life insurance trusts explained" },
    },
    {
      id: "charitable",
      name: "Charitable remainder trust",
      short: "Charitable",
      family: "tax",
      icon: "Gift",
      what: "A trust that pays you or your family an income for years or for life, then gives what remains to charity, with tax benefits along the way.",
      bestFor: ["People who want to give to charity and keep an income", "Owners of highly appreciated stock or property they want to sell"],
      watchOut: ["Gifts to the trust cannot be taken back", "Heirs receive less unless you replace it, often with insurance"],
      cells: {
        change: { level: 0, text: "No" },
        probate: { level: 3, text: "Yes" },
        tax: { level: 3, text: "Income, gains and estate tax" },
        creditors: { level: 2, text: "Some" },
        benefits: { level: 0, text: "No" },
        effort: { level: 3, text: "High" },
      },
      map: { x: 84, y: 40 },
      learn: { href: "/learn/estate-tax/charitable-remainder-trust", label: "Charitable remainder trusts" },
    },
    {
      id: "dynasty",
      name: "Dynasty trust",
      short: "Dynasty",
      family: "tax",
      icon: "TreePine",
      what: "A long-lasting irrevocable trust that holds wealth for children, grandchildren and later generations without estate tax at each generation.",
      bestFor: [`Estates well above ${EXEMPTION} per person`, "Families who want to protect wealth across generations"],
      watchOut: ["Some states limit how long a trust can last", "Complex and costly to set up and run"],
      cells: {
        change: { level: 0, text: "No" },
        probate: { level: 3, text: "Yes" },
        tax: { level: 3, text: "Skips taxes on later generations" },
        creditors: { level: 3, text: "Strong, for heirs" },
        benefits: { level: 1, text: "Not by itself" },
        effort: { level: 3, text: "High" },
      },
      map: { x: 88, y: 88 },
    },
    {
      id: "medicaid",
      name: "Medicaid asset protection trust",
      short: "Medicaid trust",
      family: "protect",
      icon: "Hourglass",
      what: "An irrevocable trust that holds your home or savings so they are not counted for Medicaid nursing home coverage once the look-back period passes.",
      bestFor: ["People in their 60s or 70s who are healthy today", "Homeowners who want to pass the house on even if long-term care is needed"],
      watchOut: [`Transfers within the ${FIGURES.medicaidLookbackMonths / 12}-year look-back can delay coverage`, "You give up access to the principal"],
      cells: {
        change: { level: 0, text: "No" },
        probate: { level: 3, text: "Yes" },
        tax: { level: 1, text: "Can keep the step-up in basis" },
        creditors: { level: 2, text: "Some" },
        benefits: { level: 3, text: "Yes, after the look-back" },
        effort: { level: 2, text: "Moderate" },
      },
      map: { x: 56, y: 84 },
      learn: { href: "/learn/elder-care/medicaid-planning", label: "Medicaid planning explained" },
    },
    {
      id: "asset-protection",
      name: "Domestic asset protection trust",
      short: "Asset protection",
      family: "protect",
      icon: "ShieldCheck",
      what: "An irrevocable trust, allowed in about 20 states, that you can benefit from while making assets harder for your future creditors to reach.",
      bestFor: ["Doctors, business owners and landlords facing lawsuit risk", "People with significant savings and no current claims"],
      watchOut: ["Does not work against debts or claims you already have", "Less tested if you live in a state that does not allow them"],
      cells: {
        change: { level: 0, text: "No" },
        probate: { level: 3, text: "Yes" },
        tax: { level: 1, text: "Depends on design" },
        creditors: { level: 3, text: "Strong, for future claims" },
        benefits: { level: 0, text: "No" },
        effort: { level: 3, text: "High, independent trustee" },
      },
      map: { x: 90, y: 62 },
      learn: { href: "/learn/trusts/irrevocable-trusts", label: "Irrevocable trusts explained" },
    },
  ],
  map: {
    title: "The trust map",
    lead: "Trusts on the left keep you in control. Moving right, you give up more control, and in return the trust can do more to protect money or cut taxes.",
    x: { low: "You keep control", high: "You give up control" },
    y: { low: "Simple, for most families", high: "Protection and tax power" },
  },
  questions: [
    {
      id: "goals",
      prompt: "What do you want a trust to do?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "probate", label: "Keep my family out of probate", weights: { revocable: 4, testamentary: -2 }, reason: "You want to avoid probate" },
        { id: "incapacity", label: "Plan for if I cannot manage my money", weights: { revocable: 3 }, reason: "You want someone ready to step in if you cannot manage" },
        { id: "kids", label: "Control when my children inherit", weights: { revocable: 2, testamentary: 2, spendthrift: 2 }, reason: "You want to control when children inherit" },
        { id: "disability", label: "Provide for someone with a disability", weights: { "special-needs": 6 }, reason: "You are providing for someone with a disability" },
        { id: "nursing", label: "Protect savings from nursing home costs", weights: { medicaid: 5 }, reason: "You want to protect savings from long-term care costs" },
        { id: "lawsuits", label: "Protect assets from lawsuits", weights: { "asset-protection": 5, spendthrift: 1 }, reason: "You want protection from lawsuits" },
        { id: "taxes", label: "Lower estate taxes", weights: { bypass: 2, ilit: 2, dynasty: 2, charitable: 1, qtip: 1 }, reason: "You want to lower estate taxes" },
        { id: "charity", label: "Give to charity", weights: { charitable: 5 }, reason: "You want to give to charity" },
        { id: "pet", label: "Care for a pet", weights: { pet: 6 }, reason: "You want a plan for your pet" },
      ],
    },
    {
      id: "home",
      prompt: "Do you own a home or other real estate?",
      choices: [
        { id: "multi", label: "Yes, in more than one state", weights: { revocable: 4, testamentary: -2 }, reason: "Property in two states can mean probate in each one" },
        { id: "one", label: "Yes, in one state", weights: { revocable: 3, testamentary: -1 }, reason: "A home is the asset most likely to need probate" },
        { id: "none", label: "No", weights: { testamentary: 1 } },
      ],
    },
    {
      id: "family",
      prompt: "Who will inherit from you?",
      help: "Pick all that apply.",
      multi: true,
      choices: [
        { id: "spouse", label: "My spouse, then our children", weights: { revocable: 1 } },
        { id: "blended", label: "Children from an earlier relationship", weights: { qtip: 5, revocable: 1 }, reason: "You want to support a spouse and still protect children from an earlier relationship" },
        { id: "minors", label: "Children under 18", weights: { testamentary: 3, revocable: 2, spendthrift: 1 }, reason: "Minor children cannot inherit directly" },
        { id: "struggles", label: "Someone who struggles with money or debt", weights: { spendthrift: 5 }, reason: "An heir may need protection from creditors or spending" },
        { id: "benefits", label: "Someone who gets SSI or Medicaid", weights: { "special-needs": 6 }, reason: "A direct gift could end someone's benefits" },
        { id: "grandkids", label: "Grandchildren and later generations", weights: { dynasty: 3, spendthrift: 1 }, reason: "You are planning for several generations" },
      ],
    },
    {
      id: "size",
      prompt: "Roughly how much is everything you own worth?",
      help: "Include your home, retirement accounts and life insurance. A rough guess is fine.",
      choices: [
        { id: "small", label: "Under $1 million", weights: { testamentary: 1 } },
        { id: "mid", label: "$1 million to $5 million", weights: { revocable: 1, bypass: 1 }, reason: "Some states tax estates of this size" },
        { id: "large", label: `$5 million to ${EXEMPTION}`, weights: { bypass: 3, ilit: 2, qtip: 1 }, reason: "Your estate could grow toward the federal limit" },
        { id: "xl", label: `More than ${EXEMPTION}`, weights: { ilit: 4, dynasty: 4, bypass: 3, charitable: 2, qtip: 2 }, reason: "Your estate is above the federal estate tax exemption" },
      ],
    },
    {
      id: "insurance",
      prompt: "Do you have life insurance of $1 million or more?",
      choices: [
        { id: "yes", label: "Yes", weights: { ilit: 3 }, reason: "A large policy can push your estate into tax" },
        { id: "no", label: "No or not sure", weights: {} },
      ],
    },
    {
      id: "care",
      prompt: "Could you need long-term care in the next 5 to 10 years?",
      choices: [
        { id: "likely", label: "Yes, it is likely", weights: { medicaid: 3 }, reason: "Long-term care is a real possibility" },
        { id: "maybe", label: "Possibly", weights: { medicaid: 1 } },
        { id: "no", label: "Unlikely", weights: { medicaid: -2 } },
      ],
    },
    {
      id: "control",
      prompt: "How much control do you want to keep?",
      choices: [
        { id: "full", label: "I want to be able to change everything", weights: { revocable: 3, medicaid: -2, "asset-protection": -2, ilit: -1, dynasty: -1 }, reason: "You want to keep full control" },
        { id: "trade", label: "I would give up some control for protection or tax savings", weights: { medicaid: 2, "asset-protection": 2, ilit: 1, dynasty: 1, charitable: 1 }, reason: "You are open to giving up control for protection" },
      ],
    },
  ],
  resultNote: "Most trust plans are built on a revocable living trust, with the other trusts written inside it or added next to it. A short consult confirms which pieces you need under your state's law.",
  shortcuts: [
    { when: "You own a home and want your family to skip probate", pick: "revocable" },
    { when: "A child or relative receives SSI or Medicaid", pick: "special-needs" },
    { when: "An heir is young, in debt or not good with money", pick: "spendthrift" },
    { when: "You remarried and have children from before", pick: "qtip" },
    { when: "You are healthy, over 60 and worried about nursing home costs", pick: "medicaid" },
    { when: "You have a large life insurance policy and a taxable estate", pick: "ilit" },
    { when: "You want an income now and a gift to charity later", pick: "charitable" },
    { when: "You want someone to care for your pet", pick: "pet" },
  ],
  diagrams: ["LivingTrustFlow", "RevocableVsIrrevocable"],
  howTo: {
    name: "How to choose the right type of trust",
    steps: [
      { name: "Name the problem", text: "Write down what worries you most: probate, incapacity, a child who is young or struggling, a disability, nursing home costs, lawsuits or taxes." },
      { name: "Start with a living trust if you own a home", text: "For most families a revocable living trust is the base. It avoids probate for funded assets and names who steps in if you cannot manage." },
      { name: "Add a trust for each person who needs one", text: "Add a special needs, spendthrift or children's trust inside your plan for heirs who should not receive money outright." },
      { name: "Check whether taxes or protection apply", text: `Irrevocable trusts make sense if your estate is near ${EXEMPTION}, your state taxes estates, long-term care is likely, or you face lawsuit risk.` },
      { name: "Choose your trustees", text: "Name a successor trustee and a backup. For irrevocable trusts, ask whether an independent or professional trustee is required." },
      { name: "Sign and fund the trust", text: "Sign the documents the way your state requires, then retitle your home and accounts into the trust and update beneficiary forms." },
    ],
  },
  faqs: [
    { q: "What are the main types of trusts?", a: "Trusts are grouped two ways. Revocable trusts can be changed and irrevocable trusts generally cannot. Living trusts start during your life and testamentary trusts start at death through your will. Within those groups, special-purpose trusts include special needs, spendthrift, life insurance, charitable, Medicaid, marital and pet trusts." },
    { q: "Which type of trust is best for most families?", a: "For most families the right fit is a revocable living trust. It avoids probate for the assets you put in it, plans for incapacity and can be changed any time. Other trusts are added only when there is a specific need, such as a disabled heir or a taxable estate." },
    { q: "What is the difference between a revocable and an irrevocable trust?", a: "You can change or cancel a revocable trust, so the law still treats the assets as yours. An irrevocable trust generally cannot be changed, which is why it can remove assets from your taxable estate or from the reach of some creditors and Medicaid rules." },
    { q: "Can I have more than one type of trust?", a: "Yes. Many plans have a revocable living trust that creates other trusts later, such as a children's trust, a special needs trust or a marital trust after the first spouse dies. Some families also add a separate irrevocable trust, such as a life insurance trust." },
    { q: "Does a trust protect assets from a nursing home?", a: "A revocable living trust does not. An irrevocable Medicaid asset protection trust can, but only for assets moved into it more than five years before applying in most states, and you give up access to the principal." },
    { q: "Do I need a trust if I have a will?", a: "Not always. A will can be enough if you rent, have modest savings and your heirs are adults. A trust adds value when you own a home, have property in more than one state, want to plan for incapacity, or have heirs who should not inherit outright." },
    { q: "How much does a trust cost?", a: "A revocable living trust plan usually costs more than a will-based plan because it includes more documents and funding. Irrevocable trusts cost more again because of tax rules and ongoing paperwork. Fees vary by state and complexity, so ask for a flat-fee quote." },
  ],
  related: [
    { href: "/learn/trusts", label: "Trusts explained, the full guide" },
    { href: "/compare/revocable-vs-irrevocable-trust", label: "Revocable vs irrevocable trust" },
    { href: "/learn/trusts/will-vs-trust", label: "Will vs trust" },
    { href: "/tools/will-or-trust", label: "Will or trust quiz" },
    { href: "/learn/trusts/how-to-fund-a-trust", label: "How to fund a trust" },
    { href: "/learn/trusts/choosing-a-trustee", label: "Choosing a trustee" },
  ],
};
