/**
 * Review and testimonial display policy (B17).
 *
 * Sources: research/local-seo-and-reviews.md (FTC fake-review rule, Google structured data
 * guidance) and research/attorney-advertising-rules-by-state.md section 1c. Pending attorney review.
 */

export const REVIEW_POLICY = {
  /**
   * Never emit AggregateRating or Review structured data for the firm. Self-collected reviews on a
   * business's own site are not eligible for review rich results, and a rating built from
   * reviews we chose to show can mislead. A test fails if either appears in src/.
   */
  aggregateRatingMarkup: false,
  /** No star ratings unless drawn live from a verifiable third-party source (for example the Google Business Profile). */
  selfReportedStarRatings: false,
  rules: [
    "Only real reviews from real clients, shown with the client's written consent on file.",
    "Never paid for, discounted, gifted or otherwise incentivized; never conditioned on a positive review.",
    "Never edited, except to remove confidential details, with the client's approval.",
    "Never written or generated by the firm, staff, vendors or AI tools.",
    "No outcome, dollar or comparative claims; no results section in v1.",
    "The state-required disclaimer sits next to every testimonial and under the list.",
    "Do not imply the testimonials shown are all the feedback received.",
    "Keep the consent record for as long as the testimonial is shown plus the retention period.",
  ],
} as const;

export interface Testimonial {
  id: string;
  /** Exact words, unedited. */
  quote: string;
  /** How the client agreed to be named, e.g. first name and last initial. */
  attribution: string;
  /** Where the review was originally given, e.g. "Google review" or "Client email". */
  source: string;
  date: string;
  consent: {
    /** Date written consent to display was received. */
    obtainedOn: string;
    /** Where the signed consent is filed (CRM record id or document path). */
    recordRef: string;
  };
  /** Must be false. Anything of value given for the review disqualifies it. */
  compensated: boolean;
  /** Set true only after the attorney checks the review against the client file. */
  attorneyApproved: boolean;
}

/**
 * Displayed testimonials. EMPTY until the firm has real, consented reviews.
 * Never add placeholders, samples or invented quotes here.
 */
export const testimonials: Testimonial[] = [];

/** Testimonials that meet every display rule. */
export function displayableTestimonials(list: Testimonial[] = testimonials): Testimonial[] {
  return list.filter(
    (t) =>
      t.quote.trim().length > 0 &&
      t.attribution.trim().length > 0 &&
      Boolean(t.consent.obtainedOn) &&
      Boolean(t.consent.recordRef) &&
      !t.compensated &&
      t.attorneyApproved,
  );
}
