export interface GuideSection { heading: string; intro?: string; items: string[] }
export interface Guide {
  slug: string;
  title: string;
  summary: string;
  pages: number;
  segments: string[];
  sections: GuideSection[];
}

export const GUIDES: Guide[] = [
  {
    slug: "estate-planning-checklist",
    title: "The Complete Estate Planning Checklist",
    summary:
      "A plain-language checklist of the documents, people, accounts and details many families review when putting an estate plan in place.",
    pages: 8,
    segments: ["general", "homeowner"],
    sections: [
      {
        heading: "Core documents",
        intro: "These are the documents many families consider as the foundation of a plan. Which ones fit your situation is a question for a licensed attorney, and rules vary by state.",
        items: [
          "Last will and testament, which can name an executor and, for parents, a guardian for minor children",
          "Revocable living trust, which many families consider to manage assets and plan for incapacity",
          "Durable financial power of attorney, naming someone to handle money matters if you cannot",
          "Healthcare power of attorney or healthcare proxy, naming someone to make medical decisions",
          "Living will or advance healthcare directive, describing your wishes about medical treatment",
          "HIPAA authorization, allowing named people to speak with your doctors",
          "Pour-over will, if a trust is used, to catch assets not yet placed in it",
          "Letter of instruction (non-binding) with personal wishes and practical details",
        ],
      },
      {
        heading: "People to name",
        intro: "Many plans depend as much on the people chosen as on the paperwork. Think about each role and about backups.",
        items: [
          "Executor or personal representative, plus at least one backup",
          "Successor trustee, plus at least one backup",
          "Agent under your financial power of attorney, plus a backup",
          "Agent for healthcare decisions, plus a backup",
          "Guardian for minor children or for a dependent adult, plus a backup",
          "Beneficiaries and contingent (backup) beneficiaries for each account",
          "Anyone who should receive specific personal items or keepsakes",
          "Trusted professionals: attorney, accountant, financial advisor, insurance agent",
        ],
      },
      {
        heading: "Accounts and beneficiary designations",
        intro: "Many accounts pass by beneficiary designation rather than by a will, so these forms are worth reviewing.",
        items: [
          "Retirement accounts such as 401(k) and IRA plans: primary and contingent beneficiaries",
          "Life insurance policies: owner, insured and beneficiaries",
          "Annuities: beneficiary and any survivor options",
          "Bank and brokerage accounts: payable-on-death or transfer-on-death designations, where available",
          "Real estate: how title is held and whether a transfer-on-death deed is available in your state",
          "Vehicles and other titled property: how title is held",
          "Check whether any beneficiary is a minor, which may call for extra planning",
          "Confirm that named beneficiaries still match your current wishes after marriage, divorce, births or deaths",
        ],
      },
      {
        heading: "Digital assets and online life",
        intro: "Online accounts and digital property are part of many estates today.",
        items: [
          "A list of important online accounts: email, banking, social media, cloud storage",
          "A secure way to share access, such as a reputable password manager with emergency access",
          "Device passcodes for phones, tablets and computers",
          "Digital items with value or sentiment: photos, domain names, online businesses, digital media",
          "Wishes for social media accounts, such as memorialize or close",
          "Two-factor authentication details and recovery methods",
          "Subscriptions and automatic payments that may need to be cancelled",
          "Whether a person named in your documents has authority over digital accounts under state law and each provider's terms",
        ],
      },
      {
        heading: "Where to keep originals and copies",
        items: [
          "Decide where signed originals will be kept, such as a fireproof home safe or with your attorney",
          "Tell your executor and trustee where the documents are and how to reach them",
          "Keep a list of document locations and professional contacts together",
          "Consider secure digital copies, understanding that some documents may require originals",
          "Be cautious with safe deposit boxes: ask whether your named people could access the box when needed",
          "Give copies of healthcare directives to your agent and your doctors",
          "Keep a record of the date each document was signed",
        ],
      },
      {
        heading: "Review schedule",
        intro: "A plan is a snapshot. Many families revisit it periodically and after major life events.",
        items: [
          "Review the full plan every few years as a general habit",
          "Review after marriage, divorce or remarriage",
          "Review after a birth or adoption",
          "Review after a death in the family or the death of a named agent or beneficiary",
          "Review after a significant change in assets, a business sale or a move to another state",
          "Review after a change in health for you or a family member",
          "Review beneficiary designations whenever you open or change an account",
          "Note the date of your last review somewhere your family can find it",
        ],
      },
      {
        heading: "Questions to bring to an attorney",
        items: [
          "Which documents do you recommend I consider given my family and assets, and why?",
          "How do the laws in my state affect my plan?",
          "How should my accounts and beneficiary designations work together with my documents?",
          "Who are the best candidates to name in each role, and what should I tell them?",
          "How often should the plan be reviewed, and what events should prompt an update?",
          "What are your fees, and what is included?",
        ],
      },
    ],
  },
  {
    slug: "new-parents-guide",
    title: "Estate Planning for New Parents",
    summary:
      "A friendly guide to the decisions many new parents think about: guardians, money for children, life insurance and beneficiary forms.",
    pages: 6,
    segments: ["new_parent", "general"],
    sections: [
      {
        heading: "Choosing a guardian",
        intro: "A guardian is the person a court may appoint to raise your children if both parents are unable to. Courts generally consider a parent's wishes, but the final decision rests with the court, and rules vary by state.",
        items: [
          "List the qualities that matter most to you: values, parenting style, health, location, stability",
          "Think about both a primary guardian and at least one backup",
          "Consider the guardian's own family situation, finances and willingness",
          "Talk with the people you are considering before naming them",
          "Consider whether the person who cares for your children should also manage the money, or whether to split those roles",
          "Think about how your children would stay connected to extended family",
          "Revisit your choice as children grow and circumstances change",
          "Put your choice in a legally valid document, since verbal wishes may not be followed",
        ],
      },
      {
        heading: "Money for your children",
        intro: "Minors generally cannot manage significant assets on their own. Many families consider ways to set money aside with someone responsible overseeing it.",
        items: [
          "Learn how your state treats assets left directly to a minor",
          "Ask about a trust for children, which can hold money and set rules for how it is used",
          "Ask about custodial accounts and how they differ from trusts",
          "Think about the ages at which your children might receive money, and whether in stages",
          "Consider what the money should cover: daily needs, education, health, other goals",
          "Name a trustee or custodian who is good with money and has time for the role, plus a backup",
          "Consider the needs of any child who may need lifelong support",
          "Think about how you would want money handled if a child has special circumstances",
        ],
      },
      {
        heading: "Life insurance basics",
        intro: "Life insurance is one tool many parents consider to replace income and cover expenses. This guide does not recommend any product; an insurance professional and an attorney can discuss options.",
        items: [
          "Estimate what your family might need to cover: housing, childcare, education, debts, daily costs",
          "Learn the general difference between term and permanent insurance",
          "Check what coverage you may already have through an employer",
          "Consider coverage for each working parent and for a parent who stays home, since their contribution has value",
          "Ask who should own the policy and who should be the beneficiary",
          "Avoid naming a minor child directly as beneficiary without understanding the consequences",
          "Review coverage when your family or finances change",
          "Compare quotes and read policy terms carefully",
        ],
      },
      {
        heading: "Beneficiary designations",
        items: [
          "Review beneficiaries on retirement accounts, life insurance and workplace benefits",
          "Name contingent beneficiaries in case your first choice cannot inherit",
          "Update forms after a birth or adoption, since old forms may name only a prior person",
          "Understand that beneficiary forms generally override what a will says for those accounts",
          "Ask whether a trust should be a beneficiary of certain accounts",
          "Check bank and investment accounts for payable-on-death options",
          "Keep a record of every designation you have made",
          "Review forms every year or two and after major life events",
        ],
      },
      {
        heading: "What to tell the guardian",
        intro: "A guardian does better with information in advance. A written letter of instruction can help; it is generally not legally binding.",
        items: [
          "Your children's routines, health needs, allergies and doctors",
          "School, childcare and activity details and contacts",
          "Your values, traditions, religious or cultural preferences",
          "Who the important people are in your children's lives",
          "Where your legal documents are kept and who your attorney is",
          "Where insurance, financial accounts and the trustee's contact details can be found",
          "Your hopes for how your children are raised and educated",
          "How to reach family, friends and professionals who can help",
        ],
      },
      {
        heading: "Questions to bring to an attorney",
        items: [
          "How is a guardian named in my state, and what happens if I do not name one?",
          "Should I consider a trust for my children, and how would it work?",
          "How do my will, trust, insurance and beneficiary forms fit together?",
          "What should I do about my children's potential inheritance at different ages?",
          "Who should serve in each role, and what are the backup options?",
          "How often should I update these documents as my children grow?",
        ],
      },
    ],
  },
  {
    slug: "after-a-death-checklist",
    title: "What to Do After a Loved One Dies: The First 30 Days and Beyond",
    summary:
      "A gentle, step-by-step checklist for the days and weeks after a death, including documents to gather, who to notify and common missteps to avoid.",
    pages: 9,
    segments: ["estate_administration", "widowed", "general"],
    sections: [
      {
        heading: "The first few days",
        intro: "Take things one step at a time. Few tasks must be done in the first hours, and it is fine to ask others for help. Procedures vary by state and by circumstance.",
        items: [
          "If the death occurred at home, follow the guidance of hospice, emergency services or your local authorities",
          "Obtain an official pronouncement of death where required",
          "Notify close family and friends, and ask someone to help you make calls",
          "Arrange care for dependents and pets",
          "Secure the home, valuables and any vehicles",
          "Contact the funeral home or arrange for the person's remains, following any written wishes",
          "Look for a will, trust, prearranged funeral plan or letter of instruction",
          "Forward mail or collect it regularly, and note anything that looks time-sensitive",
        ],
      },
      {
        heading: "Documents to gather",
        items: [
          "Certified copies of the death certificate; many institutions require them, so ask how many may be needed",
          "Original will and any codicils, and any trust documents",
          "Birth and marriage certificates, and military discharge papers if applicable",
          "Social Security number and recent tax returns",
          "Deeds, vehicle titles and mortgage or loan statements",
          "Insurance policies: life, health, auto, home, long-term care",
          "Recent bank, investment and retirement account statements",
          "Powers of attorney and healthcare directives, noting that a power of attorney generally ends at death",
          "A list of contacts: attorney, accountant, financial advisor, employer",
        ],
      },
      {
        heading: "Who to notify",
        items: [
          "Social Security Administration, usually through the funeral home or directly",
          "Employer or former employer, regarding pay, benefits and retirement plans",
          "Life insurance companies, to ask about the claim process",
          "Pension administrators and retirement plan providers",
          "Veterans Affairs, if the person served in the military",
          "Banks and credit card companies",
          "Credit reporting agencies, to request a deceased flag and help prevent fraud",
          "Health insurers, Medicare or Medicaid, and long-term care providers",
          "Utilities, phone, internet and subscription services",
        ],
      },
      {
        heading: "Accounts and ongoing tasks",
        items: [
          "Make a full list of assets and debts as you find them",
          "Ask each financial institution what it needs to retire or transfer an account",
          "Check for accounts with beneficiaries, which often pass outside probate",
          "Do not close accounts hastily; ask first what is needed to pay ongoing bills and expenses",
          "Cancel or pause automatic payments and subscriptions that are no longer needed",
          "Look for safe deposit boxes and ask the bank how access works",
          "Review digital accounts and decide with advice how to preserve or close them",
          "Keep careful records of every payment, receipt and communication",
          "Ask a tax professional about final income tax returns and any estate tax filings",
        ],
      },
      {
        heading: "The probate question",
        intro: "Probate is the court-supervised process of settling an estate. Whether it is needed, and how simple or complex it is, depends on the state and on how assets were owned.",
        items: [
          "Ask an attorney whether probate is needed in your state for this estate",
          "Learn who is named as executor or personal representative and whether that person is willing to serve",
          "Find out the deadlines for filing a will with the court, which vary by state",
          "Identify which assets pass by beneficiary, joint ownership or trust and which may pass through probate",
          "Ask about small-estate procedures that some states offer",
          "Understand that a personal representative generally has legal duties, including duties to creditors and beneficiaries",
          "Ask whether an estate bank account should be opened",
          "Keep beneficiaries informed in a respectful, documented way",
        ],
      },
      {
        heading: "Things not to do",
        intro: "Good intentions can create problems. Many families speak with an attorney before taking these steps.",
        items: [
          "Do not distribute assets or personal property to heirs before you understand the legal and creditor obligations",
          "Do not pay the person's debts out of your own pocket without first talking to a lawyer; many debts are not personally owed by family members, though rules vary",
          "Do not sign anything from a creditor or collector without understanding what you are agreeing to",
          "Do not rush to sell a home, vehicle or investments",
          "Do not throw away financial papers, mail or devices until they have been reviewed",
          "Do not let others take items from the home without a record",
          "Do not share personal information with unsolicited callers, as scams targeting the bereaved exist",
          "Do not make major personal financial decisions while in the early stages of grief when you can avoid it",
        ],
      },
      {
        heading: "Longer-term steps",
        items: [
          "Update your own estate plan and beneficiary designations if you were named in the other person's documents",
          "Review your own insurance, income and budget",
          "File required final tax returns on time",
          "Transfer vehicle titles and real estate deeds as advised",
          "Distribute assets only when the proper steps have been completed",
          "Keep estate records for as long as your attorney or accountant advises",
          "Consider support for yourself, such as counseling, grief groups or trusted friends",
        ],
      },
      {
        heading: "Questions to bring to an attorney",
        items: [
          "Is probate required in this situation, and what would the process look like?",
          "What are my duties if I am named executor or personal representative?",
          "Which debts, if any, am I responsible for, and which are not mine?",
          "What deadlines apply to filings, creditor claims and tax returns?",
          "When is it appropriate to distribute assets or property?",
          "What are the expected costs and how are your fees structured?",
        ],
      },
    ],
  },
  {
    slug: "probate-vs-trust-guide",
    title: "Probate vs. Living Trust: A Plain-English Comparison",
    summary:
      "What probate is, what a revocable living trust does, and how they compare in cost, time and privacy, with common myths explained.",
    pages: 7,
    segments: ["homeowner", "blended_family", "business_owner", "general"],
    sections: [
      {
        heading: "What probate is",
        intro: "Probate is the legal process of proving a will, paying debts and distributing assets under court supervision. How it works varies by state.",
        items: [
          "A court generally confirms the will and appoints an executor or personal representative",
          "If there is no will, state law decides who inherits, which is called intestacy",
          "Creditors are typically given a period to make claims",
          "The personal representative inventories assets, pays valid debts and taxes, and distributes what remains",
          "Probate court records are often public",
          "Some states have simplified procedures for smaller estates",
          "Assets that pass by beneficiary designation or joint ownership usually do not go through probate",
          "Time and cost can vary widely, from relatively simple to quite lengthy depending on the state and the estate",
        ],
      },
      {
        heading: "What a revocable living trust does",
        intro: "A revocable living trust is a legal arrangement you create during life. You can usually change or end it while you are alive and capable.",
        items: [
          "You generally serve as trustee while living and capable, keeping control of assets",
          "A successor trustee you name can step in if you become incapacitated or after your death",
          "Assets titled in the trust can generally be distributed under its terms without court-supervised probate",
          "The trust can set conditions or stages for beneficiaries, such as ages for distributions",
          "It can help plan for incapacity because a successor can manage trust assets without a court conservatorship, in many cases",
          "It can be useful when property is located in more than one state, which many families ask an attorney about",
          "It works alongside a pour-over will and other documents",
          "A trust is a tool; whether it fits a family depends on facts an attorney should review",
        ],
      },
      {
        heading: "Costs and time in general terms",
        intro: "No two situations are alike. These are general points only.",
        items: [
          "Probate costs can include court fees, attorney fees, executor fees and appraisal costs, and these differ by state",
          "A trust usually costs more to set up than a simple will",
          "A trust still needs administration after death, including paying debts and filing taxes",
          "Probate timelines depend on the court, creditor periods and any disputes",
          "Trust administration is often faster than probate but can still take months or longer",
          "Costs and time can increase if family members disagree or if documents are unclear",
          "Ask any attorney for a written explanation of fees before moving forward",
        ],
      },
      {
        heading: "Privacy and control",
        items: [
          "A will filed in probate generally becomes a public record",
          "A trust is generally not filed with a court, though some information may still become known to beneficiaries and others",
          "Probate may give some families comfort because a court supervises the process",
          "A trust can give a family more flexibility and private administration",
          "Think about whether privacy matters in your family situation",
          "Think about who you trust to serve and how involved a court should be",
          "Consider how each approach would work with blended families or beneficiaries who may disagree",
        ],
      },
      {
        heading: "Funding a trust",
        intro: "A trust generally controls only the assets that are properly placed in it. This step is called funding, and it is often where plans fall short.",
        items: [
          "Retitle real estate into the trust by deed, as the attorney advises, and check how this affects insurance and property tax in your state",
          "Change ownership of bank and brokerage accounts as appropriate",
          "Be careful with retirement accounts; changing ownership may cause tax consequences, so ask before acting",
          "Review beneficiary designations on life insurance and retirement accounts to see whether the trust should be named",
          "Consider assignment of personal property and business interests",
          "Keep a schedule of which assets are in the trust",
          "Add new assets to the trust after you acquire them",
          "Revisit funding after major purchases, sales or moves",
        ],
      },
      {
        heading: "Common myths",
        items: [
          "Myth: A trust avoids all taxes. Reality: A revocable trust generally does not eliminate income or estate taxes by itself",
          "Myth: A trust is only for the wealthy. Reality: Many families consider trusts for reasons unrelated to wealth, such as privacy or incapacity planning",
          "Myth: A will avoids probate. Reality: A will generally goes through probate",
          "Myth: Once a trust is signed, everything is covered. Reality: Assets generally must be funded into the trust",
          "Myth: A trust protects assets from all creditors. Reality: A revocable trust typically offers limited creditor protection during your life",
          "Myth: Probate always takes years. Reality: Timing varies widely by state and estate",
          "Myth: You never need a will if you have a trust. Reality: Many plans include a pour-over will as a backup",
          "Myth: Everyone needs the same documents. Reality: The right approach depends on the family, assets and state",
        ],
      },
      {
        heading: "Questions to bring to an attorney",
        items: [
          "Based on my family and assets, how might probate work in my state?",
          "Would a revocable trust make sense for me, and what are the trade-offs?",
          "What would the cost be to create the plan, and what ongoing costs might there be?",
          "How would you help me fund the trust, and what is my responsibility?",
          "How would my plan handle incapacity?",
          "What would happen if I own property in more than one state?",
        ],
      },
    ],
  },
  {
    slug: "family-meeting-worksheet",
    title: "Personal Information and Family Meeting Worksheet",
    summary:
      "A fill-in worksheet to organize key contacts, accounts, insurance and wishes, with prompts to guide an open family conversation.",
    pages: 6,
    segments: ["general", "caregiver", "blended_family"],
    sections: [
      {
        heading: "Key contacts",
        intro: "Fill in each prompt. Store the finished worksheet securely and tell a trusted person where it is.",
        items: [
          "Your full legal name, date of birth and primary phone number",
          "Name and phone of your spouse or partner",
          "Name and phone of your closest family member or emergency contact",
          "Name and phone of your attorney",
          "Name and phone of your financial advisor",
          "Name and phone of your accountant or tax preparer",
          "Name and phone of your insurance agent",
          "Name and phone of your primary doctor",
          "Name and phone of your clergy member, close friend or trusted neighbor",
        ],
      },
      {
        heading: "Accounts list",
        intro: "Write down where things are, not passwords. Keep passwords in a secure password manager.",
        items: [
          "Bank name, account type and where to find statements for each checking and savings account",
          "Brokerage or investment account names and contacts",
          "Retirement accounts (401(k), IRA, pension) and the plan administrator's phone number",
          "Credit cards and loans, with the lender's name",
          "Mortgage or rent: lender or landlord and payment details",
          "Location of safe deposit box and where the key is kept",
          "Name of your password manager and who can access it in an emergency",
          "Important online accounts such as email and cloud storage",
          "Vehicles: make, model and where the titles are kept",
        ],
      },
      {
        heading: "Insurance and benefits",
        items: [
          "Life insurance company, policy number, and named beneficiary",
          "Health insurance provider, plan and member ID location",
          "Medicare or Medicaid details, if applicable",
          "Long-term care insurance company and policy location, if any",
          "Disability insurance details, if any",
          "Homeowner's or renter's insurance company and agent",
          "Auto insurance company and agent",
          "Employer benefits contact and benefits summary location",
          "Social Security or veterans' benefits information location",
        ],
      },
      {
        heading: "Documents and where they are",
        items: [
          "Where is your will located, and who knows about it?",
          "Where are your trust documents, if you have any?",
          "Where is your financial power of attorney kept?",
          "Where are your healthcare directive and HIPAA authorization kept?",
          "Where are deeds, titles and mortgage papers?",
          "Where are birth, marriage and military records?",
          "Where are recent tax returns?",
          "Who has copies of which documents?",
        ],
      },
      {
        heading: "Your wishes",
        intro: "These prompts help you think through personal wishes. Share them with the people you trust.",
        items: [
          "My wishes for medical care if I cannot speak for myself",
          "Who I want making healthcare decisions for me",
          "My preference for burial, cremation or another arrangement",
          "Any funeral or memorial service preferences",
          "Items I want specific people to have",
          "Charities or causes I care about",
          "Pets and who I would like to care for them",
          "A message or values I want my family to remember",
          "Anything I would like my family to know about my digital accounts",
        ],
      },
      {
        heading: "Family meeting prompts",
        intro: "A family meeting can be short. Choose a calm time, keep the tone supportive, and remember that you are sharing information, not asking anyone to agree to everything.",
        items: [
          "Who should be invited, and who should not?",
          "What is the goal of the meeting: information, questions, or decisions?",
          "Which topics will we cover, and which will we leave for another time?",
          "What do we want everyone to know about where documents and contacts are kept?",
          "Who has agreed to serve in each role, and do they have questions?",
          "What concerns does each person have?",
          "What follow-up steps will we take, and by when?",
          "When will we meet again to review the plan?",
        ],
      },
      {
        heading: "Questions to bring to an attorney",
        items: [
          "Which of the items on this worksheet should be reflected in legal documents?",
          "How should I store this information safely?",
          "Who should receive a copy of this worksheet?",
          "How can I make sure my wishes are followed in my state?",
          "Should my family meet with you to understand the plan?",
        ],
      },
    ],
  },
  {
    slug: "caregiver-planning-guide",
    title: "Planning for an Aging Parent: A Caregiver's Guide",
    summary:
      "A practical guide for adult children covering legal documents, family conversations, long-term care costs and benefits, and cautious steps around gifting assets.",
    pages: 8,
    segments: ["caregiver", "general"],
    sections: [
      {
        heading: "Essential legal documents",
        intro: "These documents are signed by the parent, and generally while that parent still has legal capacity to understand them. Rules vary by state.",
        items: [
          "Durable financial power of attorney, naming an agent to handle money if the parent cannot",
          "Healthcare power of attorney or proxy, naming someone to make medical decisions",
          "Advance healthcare directive or living will describing treatment wishes",
          "HIPAA authorization so that family can speak with doctors",
          "Will and, for some families, a revocable trust",
          "Beneficiary designations on retirement accounts and insurance",
          "Understand that a power of attorney is a serious responsibility with legal duties",
          "If capacity has declined, an attorney can explain what options may be available in your state",
        ],
      },
      {
        heading: "Starting the conversation",
        intro: "Many families find these talks difficult. A gentle, respectful approach tends to help.",
        items: [
          "Pick a calm time and place with no rush",
          "Start with your concern for their wishes rather than their money",
          "Ask open questions: what matters most to you if your health changes?",
          "Listen first, and avoid taking over decisions",
          "Include siblings early so no one feels left out or surprised",
          "Use a recent news story or a friend's experience as a natural opening",
          "Be ready for more than one conversation",
          "Offer to attend an attorney appointment if your parent wants support",
          "Respect that your parent may keep some things private",
        ],
      },
      {
        heading: "Long-term care costs and benefits",
        intro: "Costs and benefits differ widely by location, type of care and individual situation. The points below are general and rules change.",
        items: [
          "Long-term care can include in-home help, assisted living, memory care or nursing home care",
          "Costs can be significant and differ by region and level of care",
          "Original Medicare generally does not pay for ongoing custodial long-term care",
          "Medicaid may help with long-term care costs for people who meet eligibility rules, which vary by state",
          "Long-term care insurance, if a parent has it, has its own terms, waiting periods and benefit triggers",
          "Veterans benefits may be available to some veterans and spouses",
          "Some families look at hybrid life insurance or annuity products; read the terms carefully and ask questions",
          "Local Area Agency on Aging offices can often explain community resources",
        ],
      },
      {
        heading: "Medicaid and the look-back period",
        intro: "Medicaid has a look-back rule that reviews transfers made before an application. The details vary by state and change over time.",
        items: [
          "Medicaid generally looks at past asset transfers for a set period before an application",
          "Gifts or transfers for less than fair value may cause a penalty period of ineligibility",
          "The length of the look-back and the penalty calculation depend on current law in your state",
          "Some transfers may be treated differently, such as certain transfers to a spouse or to a disabled child; ask an attorney",
          "Do not give away assets, add names to deeds or move accounts without advice first",
          "Keep records of any gifts, payments and care expenses",
          "Rules about the home, spousal protections and income can be complex",
          "Planning ahead with a qualified elder law attorney may offer more options than waiting for a crisis",
        ],
      },
      {
        heading: "Caring for yourself and the family",
        items: [
          "Be honest about how much care you can provide, and for how long",
          "Look into respite care, adult day programs and support groups",
          "Check whether your employer offers family leave or caregiver support",
          "Keep a written log of care provided and money spent on behalf of your parent",
          "Keep parent and personal finances separate",
          "Share responsibilities with siblings in writing when possible",
          "Learn the signs of financial exploitation and scams that target older adults",
          "Consider your own estate plan, since caregivers also need documents in place",
        ],
      },
      {
        heading: "Questions to bring to an attorney",
        items: [
          "Which documents should my parent consider, and how should they be signed in our state?",
          "How can my parent make sure their wishes are followed if capacity declines?",
          "How does the Medicaid look-back rule work in our state, and how might it affect us?",
          "Is it safe to make gifts or retitle property, and what are the risks?",
          "What are my duties and potential liability as an agent under a power of attorney?",
          "What are the fees, and what planning options exist for long-term care costs?",
        ],
      },
    ],
  },
];

export function findGuide(slug: string): Guide | undefined {
  return GUIDES.find((g) => g.slug === slug);
}
